/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (revoke refresh token) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user info */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request password reset */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset password with token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/security/users/{userId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Set user password (admin) */
        put: operations["setUserPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List object definitions */
        get: operations["listObjects"];
        put?: never;
        /** Create object definition */
        post: operations["createObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects/{objectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        /** Get object definition */
        get: operations["getObject"];
        /** Update object definition */
        put: operations["updateObject"];
        post?: never;
        /** Delete object definition */
        delete: operations["deleteObject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects/{objectId}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        /** List field definitions for object */
        get: operations["listFields"];
        put?: never;
        /** Create field definition */
        post: operations["createField"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects/{objectId}/fields/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                fieldId: components["parameters"]["FieldId"];
            };
            cookie?: never;
        };
        /** Get field definition */
        get: operations["getField"];
        /** Update field definition */
        put: operations["updateField"];
        post?: never;
        /** Delete field definition */
        delete: operations["deleteField"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execute SOQL query (GET) */
        get: operations["executeQueryGet"];
        put?: never;
        /** Execute SOQL query (POST) */
        post: operations["executeQueryPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute DML statement */
        post: operations["executeDML"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available application templates */
        get: operations["listTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/templates/{templateId}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply an application template */
        post: operations["applyTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accessible objects for navigation */
        get: operations["listDescribeObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/describe/{objectName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        /** Describe object with fields */
        get: operations["describeObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{objectName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        /** List records for an object */
        get: operations["listRecords"];
        put?: never;
        /** Create a record */
        post: operations["createRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{objectName}/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
                recordId: string;
            };
            cookie?: never;
        };
        /** Get a record by ID */
        get: operations["getRecord"];
        /** Update a record */
        put: operations["updateRecord"];
        post?: never;
        /** Delete a record */
        delete: operations["deleteRecord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects/{objectId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        /** List validation rules for object */
        get: operations["listValidationRules"];
        put?: never;
        /** Create validation rule */
        post: operations["createValidationRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/metadata/objects/{objectId}/rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        /** Get validation rule */
        get: operations["getValidationRule"];
        /** Update validation rule */
        put: operations["updateValidationRule"];
        post?: never;
        /** Delete validation rule */
        delete: operations["deleteValidationRule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all custom functions */
        get: operations["listFunctions"];
        put?: never;
        /** Create a custom function */
        post: operations["createFunction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/functions/{functionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionId: components["parameters"]["FunctionId"];
            };
            cookie?: never;
        };
        /** Get a custom function by ID */
        get: operations["getFunction"];
        /** Update a custom function */
        put: operations["updateFunction"];
        post?: never;
        /** Delete a custom function */
        delete: operations["deleteFunction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/object-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List object views */
        get: operations["listObjectViews"];
        put?: never;
        /** Create an object view */
        post: operations["createObjectView"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/object-views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        /** Get an object view by ID */
        get: operations["getObjectView"];
        /** Update an object view */
        put: operations["updateObjectView"];
        post?: never;
        /** Delete an object view */
        delete: operations["deleteObjectView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cel/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a CEL expression */
        post: operations["validateCelExpression"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/soql/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a SOQL query */
        post: operations["validateSoqlQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/soql/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a SOQL query for testing (no security enforcement) */
        post: operations["testSoqlQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/soql/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all queryable objects (no OLS filtering) */
        get: operations["listSoqlObjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/soql/objects/{objectName}/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all fields for an object (no FLS filtering) */
        get: operations["listSoqlObjectFields"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profile-navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all profile navigation configs */
        get: operations["listProfileNavigations"];
        put?: never;
        /** Create a profile navigation config */
        post: operations["createProfileNavigation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/profile-navigation/{navId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                navId: components["parameters"]["NavId"];
            };
            cookie?: never;
        };
        /** Get a profile navigation config by ID */
        get: operations["getProfileNavigation"];
        /** Update a profile navigation config */
        put: operations["updateProfileNavigation"];
        post?: never;
        /** Delete a profile navigation config */
        delete: operations["deleteProfileNavigation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve navigation for current user's profile
         * @description Returns the resolved sidebar navigation for the authenticated user's profile. Object items are filtered by OLS (read permission). If no config exists for the profile, returns a fallback with a single "_default" group containing all OLS-accessible objects.
         */
        get: operations["resolveNavigation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/view/{ovApiName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ovApiName: string;
            };
            cookie?: never;
        };
        /**
         * Get an object view config by API name
         * @description Returns the full object view config for the given API name. Used by frontend to render pages assigned via Navigation config.
         */
        get: operations["getViewByAPIName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/view/{ovApiName}/query/{queryName}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ovApiName: string;
                queryName: string;
            };
            cookie?: never;
        };
        /**
         * Execute a named query from an Object View
         * @description Finds the named query in the Object View config, substitutes URL query parameters into SOQL :paramName placeholders, and executes via the SOQL service with full security enforcement.
         */
        get: operations["executeViewQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        ForgotPasswordRequest: {
            /** Format: email */
            email: string;
        };
        ResetPasswordRequest: {
            token: string;
            password: string;
        };
        SetPasswordRequest: {
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
        };
        TokenPairResponse: {
            data?: components["schemas"]["TokenPair"];
        };
        UserInfo: {
            /** Format: uuid */
            id: string;
            username: string;
            email: string;
            first_name: string;
            last_name: string;
            /** Format: uuid */
            profile_id: string;
            /** Format: uuid */
            role_id?: string | null;
            is_active: boolean;
        };
        UserInfoResponse: {
            data?: components["schemas"]["UserInfo"];
        };
        CreateObjectRequest: {
            /** @example Invoice__c */
            api_name: string;
            /** @example Invoice */
            label: string;
            /** @example Invoices */
            plural_label: string;
            /** @default  */
            description: string;
            /** @enum {string} */
            object_type: "standard" | "custom";
            /** @default true */
            is_visible_in_setup: boolean;
            /** @default true */
            is_custom_fields_allowed: boolean;
            /** @default true */
            is_deleteable_object: boolean;
            /** @default true */
            is_createable: boolean;
            /** @default true */
            is_updateable: boolean;
            /** @default true */
            is_deleteable: boolean;
            /** @default true */
            is_queryable: boolean;
            /** @default false */
            is_searchable: boolean;
            /** @default false */
            has_activities: boolean;
            /** @default false */
            has_notes: boolean;
            /** @default false */
            has_history_tracking: boolean;
            /** @default false */
            has_sharing_rules: boolean;
            /**
             * @default private
             * @enum {string}
             */
            visibility: "private" | "public_read" | "public_read_write" | "controlled_by_parent";
        };
        CreateObjectViewRequest: {
            /** Format: uuid */
            profile_id?: string | null;
            api_name: string;
            label: string;
            description?: string;
            config?: components["schemas"]["ObjectViewConfig"];
        };
        UpdateObjectRequest: {
            label: string;
            plural_label: string;
            description?: string;
            is_visible_in_setup?: boolean;
            is_custom_fields_allowed?: boolean;
            is_deleteable_object?: boolean;
            is_createable?: boolean;
            is_updateable?: boolean;
            is_deleteable?: boolean;
            is_queryable?: boolean;
            is_searchable?: boolean;
            has_activities?: boolean;
            has_notes?: boolean;
            has_history_tracking?: boolean;
            has_sharing_rules?: boolean;
            /** @enum {string} */
            visibility?: "private" | "public_read" | "public_read_write" | "controlled_by_parent";
        };
        ObjectDefinition: {
            /** Format: uuid */
            id: string;
            api_name: string;
            label: string;
            plural_label: string;
            description: string;
            /** @enum {string} */
            object_type: "standard" | "custom";
            is_platform_managed: boolean;
            is_visible_in_setup: boolean;
            is_custom_fields_allowed: boolean;
            is_deleteable_object: boolean;
            is_createable: boolean;
            is_updateable: boolean;
            is_deleteable: boolean;
            is_queryable: boolean;
            is_searchable: boolean;
            has_activities: boolean;
            has_notes: boolean;
            has_history_tracking: boolean;
            has_sharing_rules: boolean;
            /** @enum {string} */
            visibility: "private" | "public_read" | "public_read_write" | "controlled_by_parent";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ObjectResponse: {
            data?: components["schemas"]["ObjectDefinition"];
        };
        ObjectListResponse: {
            data?: components["schemas"]["ObjectDefinition"][];
            pagination?: components["schemas"]["PaginationMeta"];
        };
        CreateFieldRequest: {
            api_name: string;
            label: string;
            /** @default  */
            description: string;
            /** @default  */
            help_text: string;
            /** @enum {string} */
            field_type: "text" | "number" | "boolean" | "datetime" | "picklist" | "reference";
            /** @enum {string} */
            field_subtype?: "plain" | "area" | "rich" | "email" | "phone" | "url" | "integer" | "decimal" | "currency" | "percent" | "auto_number" | "date" | "datetime" | "time" | "single" | "multi" | "association" | "composition" | "polymorphic";
            /** Format: uuid */
            referenced_object_id?: string;
            /** @default false */
            is_required: boolean;
            /** @default false */
            is_unique: boolean;
            config?: components["schemas"]["FieldConfig"];
            /** @default false */
            is_custom: boolean;
            /** @default 0 */
            sort_order: number;
        };
        UpdateFieldRequest: {
            label: string;
            description?: string;
            help_text?: string;
            is_required?: boolean;
            is_unique?: boolean;
            config?: components["schemas"]["FieldConfig"];
            sort_order?: number;
        };
        FieldConfig: {
            max_length?: number;
            precision?: number;
            scale?: number;
            format?: string;
            start_value?: number;
            relationship_name?: string;
            /** @enum {string} */
            on_delete?: "set_null" | "cascade" | "restrict";
            is_reparentable?: boolean;
            default_value?: string;
            /** @description CEL expression for dynamic default value */
            default_expr?: string;
            /** @description When to apply default (create, update, create,update) */
            default_on?: string;
        };
        CreateValidationRuleRequest: {
            api_name: string;
            label: string;
            /** @description CEL expression that must return true for valid data */
            expression: string;
            error_message: string;
            /** @default validation_failed */
            error_code: string;
            /**
             * @default error
             * @enum {string}
             */
            severity: "error" | "warning";
            /** @description Optional CEL condition for when this rule applies */
            when_expression?: string;
            /** @default create,update */
            applies_to: string;
            /** @default 0 */
            sort_order: number;
            /** @default true */
            is_active: boolean;
            description?: string;
        };
        UpdateValidationRuleRequest: {
            label: string;
            expression: string;
            error_message: string;
            error_code?: string;
            /** @enum {string} */
            severity?: "error" | "warning";
            when_expression?: string;
            applies_to?: string;
            sort_order?: number;
            is_active?: boolean;
            description?: string;
        };
        ValidationRule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            object_id: string;
            api_name: string;
            label: string;
            description: string;
            expression: string;
            error_message: string;
            error_code: string;
            /** @enum {string} */
            severity: "error" | "warning";
            when_expression?: string | null;
            applies_to: string;
            sort_order: number;
            is_active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ValidationRuleResponse: {
            data?: components["schemas"]["ValidationRule"];
        };
        ValidationRuleListResponse: {
            data?: components["schemas"]["ValidationRule"][];
        };
        FieldDefinitionSchema: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            object_id: string;
            api_name: string;
            label: string;
            description: string;
            help_text: string;
            /** @enum {string} */
            field_type: "text" | "number" | "boolean" | "datetime" | "picklist" | "reference";
            /** @enum {string} */
            field_subtype?: "plain" | "area" | "rich" | "email" | "phone" | "url" | "integer" | "decimal" | "currency" | "percent" | "auto_number" | "date" | "datetime" | "time" | "single" | "multi" | "association" | "composition" | "polymorphic";
            /** Format: uuid */
            referenced_object_id?: string;
            is_required: boolean;
            is_unique: boolean;
            config: components["schemas"]["FieldConfig"];
            is_system_field: boolean;
            is_custom: boolean;
            is_platform_managed: boolean;
            sort_order: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FieldResponse: {
            data?: components["schemas"]["FieldDefinitionSchema"];
        };
        FieldListResponse: {
            data?: components["schemas"]["FieldDefinitionSchema"][];
        };
        SOQLRequest: {
            /**
             * @description SOQL query string
             * @example SELECT Id, Name FROM Account LIMIT 10
             */
            query: string;
            /**
             * @description Maximum number of records per page
             * @default 100
             */
            pageSize: number;
        };
        SOQLResult: {
            /** @description Total number of records returned */
            totalSize?: number;
            /** @description Whether all records have been returned */
            done?: boolean;
            /** @description Query result records */
            records?: {
                [key: string]: unknown;
            }[];
            /** @description Cursor for fetching the next page (empty if done) */
            nextRecordsUrl?: string;
        };
        DMLRequest: {
            /**
             * @description DML statement string
             * @example INSERT INTO Account (Name, Industry) VALUES ('Acme', 'Technology')
             */
            statement: string;
        };
        DMLResult: {
            /**
             * Format: int64
             * @description Number of rows affected
             */
            rowsAffected?: number;
            /** @description IDs of inserted records */
            insertedIds?: string[];
            /** @description IDs of updated records */
            updatedIds?: string[];
            /** @description IDs of deleted records */
            deletedIds?: string[];
        };
        TemplateInfo: {
            id?: string;
            label?: string;
            description?: string;
            /** @enum {string} */
            status?: "available" | "applied" | "blocked";
            objects?: number;
            fields?: number;
        };
        TemplateListResponse: {
            data?: components["schemas"]["TemplateInfo"][];
        };
        TemplateApplyResponse: {
            data?: {
                template_id?: string;
                message?: string;
            };
        };
        ObjectNavItem: {
            api_name: string;
            label: string;
            plural_label: string;
            is_createable: boolean;
            is_queryable: boolean;
        };
        ObjectDescribe: {
            api_name: string;
            label: string;
            plural_label: string;
            is_createable: boolean;
            is_updateable: boolean;
            is_deleteable: boolean;
            fields: components["schemas"]["FieldDescribe"][];
            form?: components["schemas"]["FormDescribe"];
        };
        FieldDescribe: {
            api_name: string;
            label: string;
            field_type: string;
            field_subtype?: string | null;
            is_required: boolean;
            is_read_only: boolean;
            is_system_field: boolean;
            sort_order: number;
            config: {
                max_length?: number;
                precision?: number;
                scale?: number;
                default_value?: string;
                values?: {
                    id: string;
                    value: string;
                    label: string;
                    sort_order: number;
                    is_default: boolean;
                    is_active: boolean;
                }[];
            };
        };
        FormDescribe: {
            sections?: components["schemas"]["FormSection"][];
            highlight_fields?: string[];
            actions?: components["schemas"]["FormAction"][];
            related_lists?: components["schemas"]["FormRelatedList"][];
            list_fields?: string[];
            list_default_sort?: string;
            queries?: components["schemas"]["FormQuery"][];
        };
        FormQuery: {
            name: string;
            /** @enum {string} */
            type: "scalar" | "list";
            default?: boolean;
        };
        FormSection: {
            key?: string;
            label?: string;
            columns?: number;
            collapsed?: boolean;
            fields?: string[];
        };
        FormAction: {
            key?: string;
            label?: string;
            type?: string;
            icon?: string;
            visibility_expr?: string;
        };
        FormRelatedList: {
            object?: string;
            label?: string;
            fields?: string[];
            sort?: string;
            limit?: number;
        };
        PaginationMeta: {
            page: number;
            per_page: number;
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            total_pages: number;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        Function: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            params?: components["schemas"]["FunctionParam"][];
            /** @enum {string} */
            return_type?: "string" | "number" | "boolean" | "list" | "map" | "any";
            body?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        FunctionParam: {
            name: string;
            /** @enum {string} */
            type: "string" | "number" | "boolean" | "list" | "map" | "any";
            description?: string;
        };
        CreateFunctionRequest: {
            name: string;
            description?: string;
            params?: components["schemas"]["FunctionParam"][];
            /** @enum {string} */
            return_type?: "string" | "number" | "boolean" | "list" | "map" | "any";
            body: string;
        };
        UpdateFunctionRequest: {
            description?: string;
            params?: components["schemas"]["FunctionParam"][];
            /** @enum {string} */
            return_type?: "string" | "number" | "boolean" | "list" | "map" | "any";
            body: string;
        };
        ObjectView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            profile_id?: string | null;
            api_name: string;
            label: string;
            description: string;
            config: components["schemas"]["ObjectViewConfig"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ObjectViewConfig: {
            view: components["schemas"]["OVViewConfig"];
            edit?: components["schemas"]["OVEditConfig"];
        };
        OVViewConfig: {
            fields?: components["schemas"]["OVViewField"][];
            actions?: components["schemas"]["OVAction"][];
            queries?: components["schemas"]["OVQuery"][];
        };
        OVEditConfig: {
            fields?: string[];
            validation?: components["schemas"]["OVValidation"][];
            defaults?: components["schemas"]["OVDefault"][];
            computed?: components["schemas"]["OVComputed"][];
            mutations?: components["schemas"]["OVMutation"][];
        };
        OVAction: {
            key: string;
            label: string;
            type: string;
            icon: string;
            visibility_expr: string;
        };
        OVQuery: {
            name: string;
            soql: string;
            /** @enum {string} */
            type: "scalar" | "list";
            default?: boolean;
            when?: string;
        };
        OVMutation: {
            dml: string;
            foreach?: string;
            sync?: components["schemas"]["OVMutSync"];
            when?: string;
        };
        OVMutSync: {
            key: string;
            value: string;
        };
        OVViewField: {
            name: string;
            /** @enum {string} */
            type?: "string" | "int" | "float" | "bool" | "timestamp";
            expr?: string;
            when?: string;
        };
        OVValidation: {
            expr: string;
            message: string;
            code?: string;
            /** @enum {string} */
            severity: "error" | "warning";
            when?: string;
        };
        OVDefault: {
            field: string;
            expr: string;
            /** @enum {string} */
            on: "create" | "update" | "create,update";
            when?: string;
        };
        OVComputed: {
            field: string;
            expr: string;
        };
        UpdateObjectViewRequest: {
            label: string;
            description?: string;
            config?: components["schemas"]["ObjectViewConfig"];
        };
        CelValidateRequest: {
            expression: string;
            /** @enum {string} */
            context: "validation_rule" | "when_expression" | "default_expr" | "function_body" | "visibility_expr";
            object_api_name?: string;
            params?: components["schemas"]["CelParamDef"][];
        };
        CelParamDef: {
            name: string;
            type: string;
        };
        CelValidateResponse: {
            valid: boolean;
            return_type?: string;
            errors?: components["schemas"]["CelValidateError"][];
        };
        CelValidateError: {
            message: string;
            line?: number;
            column?: number;
        };
        SoqlValidateRequest: {
            query: string;
        };
        SoqlValidateResponse: {
            valid: boolean;
            object?: string;
            fields?: string[];
            errors?: components["schemas"]["SoqlValidateError"][];
        };
        SoqlValidateError: {
            message: string;
            line?: number;
            column?: number;
            code?: string;
        };
        NavItem: {
            /** @enum {string} */
            type: "object" | "link" | "divider" | "page";
            object_api_name?: string;
            ov_api_name?: string;
            label?: string;
            url?: string;
            icon?: string;
        };
        NavGroup: {
            key: string;
            label: string;
            icon?: string;
            items: components["schemas"]["NavItem"][];
        };
        NavConfig: {
            groups: components["schemas"]["NavGroup"][];
        };
        ProfileNavigation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            profile_id: string;
            config: components["schemas"]["NavConfig"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateProfileNavigationRequest: {
            /** Format: uuid */
            profile_id: string;
            config?: components["schemas"]["NavConfig"];
        };
        UpdateProfileNavigationRequest: {
            config?: components["schemas"]["NavConfig"];
        };
        ResolvedNavItem: {
            /** @enum {string} */
            type: "object" | "link" | "divider" | "page";
            object_api_name?: string;
            ov_api_name?: string;
            label?: string;
            plural_label?: string;
            url?: string;
            icon?: string;
        };
        ResolvedNavGroup: {
            key: string;
            label: string;
            icon?: string;
            items: components["schemas"]["ResolvedNavItem"][];
        };
        ResolvedNavigation: {
            groups: components["schemas"]["ResolvedNavGroup"][];
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description Validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Action not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Duplicate or conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ObjectId: string;
        FieldId: string;
        RuleId: string;
        FunctionId: string;
        ViewId: string;
        NavId: string;
        Page: number;
        PerPage: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token?: string;
                };
            };
        };
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description If the email exists, a reset link has been sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password has been reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    setUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPasswordRequest"];
            };
        };
        responses: {
            /** @description Password updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listObjects: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
                object_type?: "standard" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectListResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createObject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectRequest"];
            };
        };
        responses: {
            /** @description Object created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateObjectRequest"];
            };
        };
        responses: {
            /** @description Object updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listFields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFieldRequest"];
            };
        };
        responses: {
            /** @description Field created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    getField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                fieldId: components["parameters"]["FieldId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field definition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    updateField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                fieldId: components["parameters"]["FieldId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFieldRequest"];
            };
        };
        responses: {
            /** @description Field updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteField: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                fieldId: components["parameters"]["FieldId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    executeQueryGet: {
        parameters: {
            query: {
                /**
                 * @description SOQL query string
                 * @example SELECT Id, Name FROM Account WHERE Name = 'Acme'
                 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOQLResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    executeQueryPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SOQLRequest"];
            };
        };
        responses: {
            /** @description Query result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SOQLResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    executeDML: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DMLRequest"];
            };
        };
        responses: {
            /** @description DML result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DMLResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    applyTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template applied successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateApplyResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["InternalError"];
        };
    };
    listDescribeObjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of queryable objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectNavItem"][];
                    };
                };
            };
        };
    };
    describeObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object description with fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectDescribe"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRecords: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                per_page?: components["parameters"]["PerPage"];
            };
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            [key: string]: unknown;
                        }[];
                        pagination?: components["schemas"]["PaginationMeta"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Record created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            id?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Record updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
                recordId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Record deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listValidationRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of validation rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRuleListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createValidationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateValidationRuleRequest"];
            };
        };
        responses: {
            /** @description Validation rule created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getValidationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation rule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRuleResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateValidationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateValidationRuleRequest"];
            };
        };
        responses: {
            /** @description Validation rule updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRuleResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteValidationRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
                ruleId: components["parameters"]["RuleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation rule deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listFunctions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of functions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Function"][];
                    };
                };
            };
        };
    };
    createFunction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFunctionRequest"];
            };
        };
        responses: {
            /** @description Function created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Function"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionId: components["parameters"]["FunctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Function details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Function"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionId: components["parameters"]["FunctionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFunctionRequest"];
            };
        };
        responses: {
            /** @description Function updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Function"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionId: components["parameters"]["FunctionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Function deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listObjectViews: {
        parameters: {
            query?: {
                /** @description Filter by object ID */
                object_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of object views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectView"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createObjectView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectViewRequest"];
            };
        };
        responses: {
            /** @description Object view created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectView"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getObjectView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object view details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectView"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateObjectView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateObjectViewRequest"];
            };
        };
        responses: {
            /** @description Object view updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectView"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteObjectView: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: components["parameters"]["ViewId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object view deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    validateCelExpression: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CelValidateRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CelValidateResponse"];
                };
            };
        };
    };
    validateSoqlQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoqlValidateRequest"];
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoqlValidateResponse"];
                };
            };
        };
    };
    testSoqlQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    query: string;
                    /** @default 5 */
                    pageSize?: number;
                };
            };
        };
        responses: {
            /** @description Query execution result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        totalSize?: number;
                        records?: {
                            [key: string]: unknown;
                        }[];
                        error?: string;
                    };
                };
            };
        };
    };
    listSoqlObjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of queryable objects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            api_name?: string;
                            label?: string;
                        }[];
                    };
                };
            };
        };
    };
    listSoqlObjectFields: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            api_name?: string;
                            label?: string;
                            field_type?: string;
                        }[];
                    };
                };
            };
            /** @description Object not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProfileNavigations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of navigation configs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProfileNavigation"][];
                    };
                };
            };
        };
    };
    createProfileNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileNavigationRequest"];
            };
        };
        responses: {
            /** @description Navigation config created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProfileNavigation"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getProfileNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                navId: components["parameters"]["NavId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Navigation config details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProfileNavigation"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProfileNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                navId: components["parameters"]["NavId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileNavigationRequest"];
            };
        };
        responses: {
            /** @description Navigation config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ProfileNavigation"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProfileNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                navId: components["parameters"]["NavId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Navigation config deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveNavigation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resolved navigation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ResolvedNavigation"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getViewByAPIName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ovApiName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Object view config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["ObjectView"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    executeViewQuery: {
        parameters: {
            query?: {
                per_page?: number;
            };
            header?: never;
            path: {
                ovApiName: string;
                queryName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query execution result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["SOQLResult"];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
