// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: field_definitions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFieldDefinition = `-- name: CreateFieldDefinition :one
INSERT INTO metadata.field_definitions (
    object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14, $15
) RETURNING id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
`

type CreateFieldDefinitionParams struct {
	ObjectID           uuid.UUID   `json:"object_id"`
	ApiName            string      `json:"api_name"`
	Label              string      `json:"label"`
	Description        string      `json:"description"`
	HelpText           string      `json:"help_text"`
	FieldType          string      `json:"field_type"`
	FieldSubtype       pgtype.Text `json:"field_subtype"`
	ReferencedObjectID pgtype.UUID `json:"referenced_object_id"`
	IsRequired         bool        `json:"is_required"`
	IsUnique           bool        `json:"is_unique"`
	Config             []byte      `json:"config"`
	IsSystemField      bool        `json:"is_system_field"`
	IsCustom           bool        `json:"is_custom"`
	IsPlatformManaged  bool        `json:"is_platform_managed"`
	SortOrder          int32       `json:"sort_order"`
}

func (q *Queries) CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) (*MetadataFieldDefinition, error) {
	row := q.db.QueryRow(ctx, createFieldDefinition,
		arg.ObjectID,
		arg.ApiName,
		arg.Label,
		arg.Description,
		arg.HelpText,
		arg.FieldType,
		arg.FieldSubtype,
		arg.ReferencedObjectID,
		arg.IsRequired,
		arg.IsUnique,
		arg.Config,
		arg.IsSystemField,
		arg.IsCustom,
		arg.IsPlatformManaged,
		arg.SortOrder,
	)
	var i MetadataFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.HelpText,
		&i.FieldType,
		&i.FieldSubtype,
		&i.ReferencedObjectID,
		&i.IsRequired,
		&i.IsUnique,
		&i.Config,
		&i.IsSystemField,
		&i.IsCustom,
		&i.IsPlatformManaged,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteFieldDefinition = `-- name: DeleteFieldDefinition :exec
DELETE FROM metadata.field_definitions WHERE id = $1
`

func (q *Queries) DeleteFieldDefinition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFieldDefinition, id)
	return err
}

const getFieldDefinitionByID = `-- name: GetFieldDefinitionByID :one
SELECT id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
FROM metadata.field_definitions
WHERE id = $1
`

func (q *Queries) GetFieldDefinitionByID(ctx context.Context, id uuid.UUID) (*MetadataFieldDefinition, error) {
	row := q.db.QueryRow(ctx, getFieldDefinitionByID, id)
	var i MetadataFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.HelpText,
		&i.FieldType,
		&i.FieldSubtype,
		&i.ReferencedObjectID,
		&i.IsRequired,
		&i.IsUnique,
		&i.Config,
		&i.IsSystemField,
		&i.IsCustom,
		&i.IsPlatformManaged,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getFieldDefinitionByObjectAndName = `-- name: GetFieldDefinitionByObjectAndName :one
SELECT id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
FROM metadata.field_definitions
WHERE object_id = $1 AND api_name = $2
`

type GetFieldDefinitionByObjectAndNameParams struct {
	ObjectID uuid.UUID `json:"object_id"`
	ApiName  string    `json:"api_name"`
}

func (q *Queries) GetFieldDefinitionByObjectAndName(ctx context.Context, arg GetFieldDefinitionByObjectAndNameParams) (*MetadataFieldDefinition, error) {
	row := q.db.QueryRow(ctx, getFieldDefinitionByObjectAndName, arg.ObjectID, arg.ApiName)
	var i MetadataFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.HelpText,
		&i.FieldType,
		&i.FieldSubtype,
		&i.ReferencedObjectID,
		&i.IsRequired,
		&i.IsUnique,
		&i.Config,
		&i.IsSystemField,
		&i.IsCustom,
		&i.IsPlatformManaged,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllFieldDefinitions = `-- name: ListAllFieldDefinitions :many
SELECT id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
FROM metadata.field_definitions
ORDER BY object_id, sort_order, api_name
`

func (q *Queries) ListAllFieldDefinitions(ctx context.Context) ([]*MetadataFieldDefinition, error) {
	rows, err := q.db.Query(ctx, listAllFieldDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataFieldDefinition{}
	for rows.Next() {
		var i MetadataFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.ApiName,
			&i.Label,
			&i.Description,
			&i.HelpText,
			&i.FieldType,
			&i.FieldSubtype,
			&i.ReferencedObjectID,
			&i.IsRequired,
			&i.IsUnique,
			&i.Config,
			&i.IsSystemField,
			&i.IsCustom,
			&i.IsPlatformManaged,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefinitionsByObjectID = `-- name: ListFieldDefinitionsByObjectID :many
SELECT id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
FROM metadata.field_definitions
WHERE object_id = $1
ORDER BY sort_order, api_name
`

func (q *Queries) ListFieldDefinitionsByObjectID(ctx context.Context, objectID uuid.UUID) ([]*MetadataFieldDefinition, error) {
	rows, err := q.db.Query(ctx, listFieldDefinitionsByObjectID, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataFieldDefinition{}
	for rows.Next() {
		var i MetadataFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.ApiName,
			&i.Label,
			&i.Description,
			&i.HelpText,
			&i.FieldType,
			&i.FieldSubtype,
			&i.ReferencedObjectID,
			&i.IsRequired,
			&i.IsUnique,
			&i.Config,
			&i.IsSystemField,
			&i.IsCustom,
			&i.IsPlatformManaged,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferenceFieldDefinitions = `-- name: ListReferenceFieldDefinitions :many
SELECT id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
FROM metadata.field_definitions
WHERE field_type = 'reference'
ORDER BY object_id, api_name
`

func (q *Queries) ListReferenceFieldDefinitions(ctx context.Context) ([]*MetadataFieldDefinition, error) {
	rows, err := q.db.Query(ctx, listReferenceFieldDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataFieldDefinition{}
	for rows.Next() {
		var i MetadataFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ObjectID,
			&i.ApiName,
			&i.Label,
			&i.Description,
			&i.HelpText,
			&i.FieldType,
			&i.FieldSubtype,
			&i.ReferencedObjectID,
			&i.IsRequired,
			&i.IsUnique,
			&i.Config,
			&i.IsSystemField,
			&i.IsCustom,
			&i.IsPlatformManaged,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFieldDefinition = `-- name: UpdateFieldDefinition :one
UPDATE metadata.field_definitions SET
    label = $2,
    description = $3,
    help_text = $4,
    is_required = $5,
    is_unique = $6,
    config = $7,
    sort_order = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, object_id, api_name, label, description, help_text,
    field_type, field_subtype, referenced_object_id,
    is_required, is_unique, config,
    is_system_field, is_custom, is_platform_managed, sort_order,
    created_at, updated_at
`

type UpdateFieldDefinitionParams struct {
	ID          uuid.UUID `json:"id"`
	Label       string    `json:"label"`
	Description string    `json:"description"`
	HelpText    string    `json:"help_text"`
	IsRequired  bool      `json:"is_required"`
	IsUnique    bool      `json:"is_unique"`
	Config      []byte    `json:"config"`
	SortOrder   int32     `json:"sort_order"`
}

func (q *Queries) UpdateFieldDefinition(ctx context.Context, arg UpdateFieldDefinitionParams) (*MetadataFieldDefinition, error) {
	row := q.db.QueryRow(ctx, updateFieldDefinition,
		arg.ID,
		arg.Label,
		arg.Description,
		arg.HelpText,
		arg.IsRequired,
		arg.IsUnique,
		arg.Config,
		arg.SortOrder,
	)
	var i MetadataFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.ObjectID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.HelpText,
		&i.FieldType,
		&i.FieldSubtype,
		&i.ReferencedObjectID,
		&i.IsRequired,
		&i.IsUnique,
		&i.Config,
		&i.IsSystemField,
		&i.IsCustom,
		&i.IsPlatformManaged,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
