// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MetadataFieldDefinition struct {
	ID                 uuid.UUID   `json:"id"`
	ObjectID           uuid.UUID   `json:"object_id"`
	ApiName            string      `json:"api_name"`
	Label              string      `json:"label"`
	Description        string      `json:"description"`
	HelpText           string      `json:"help_text"`
	FieldType          string      `json:"field_type"`
	FieldSubtype       pgtype.Text `json:"field_subtype"`
	ReferencedObjectID pgtype.UUID `json:"referenced_object_id"`
	IsRequired         bool        `json:"is_required"`
	IsUnique           bool        `json:"is_unique"`
	Config             []byte      `json:"config"`
	IsSystemField      bool        `json:"is_system_field"`
	IsCustom           bool        `json:"is_custom"`
	IsPlatformManaged  bool        `json:"is_platform_managed"`
	SortOrder          int32       `json:"sort_order"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type MetadataObjectDefinition struct {
	ID                    uuid.UUID `json:"id"`
	ApiName               string    `json:"api_name"`
	Label                 string    `json:"label"`
	PluralLabel           string    `json:"plural_label"`
	Description           string    `json:"description"`
	TableName             string    `json:"table_name"`
	ObjectType            string    `json:"object_type"`
	IsPlatformManaged     bool      `json:"is_platform_managed"`
	IsVisibleInSetup      bool      `json:"is_visible_in_setup"`
	IsCustomFieldsAllowed bool      `json:"is_custom_fields_allowed"`
	IsDeleteableObject    bool      `json:"is_deleteable_object"`
	IsCreateable          bool      `json:"is_createable"`
	IsUpdateable          bool      `json:"is_updateable"`
	IsDeleteable          bool      `json:"is_deleteable"`
	IsQueryable           bool      `json:"is_queryable"`
	IsSearchable          bool      `json:"is_searchable"`
	HasActivities         bool      `json:"has_activities"`
	HasNotes              bool      `json:"has_notes"`
	HasHistoryTracking    bool      `json:"has_history_tracking"`
	HasSharingRules       bool      `json:"has_sharing_rules"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type MetadataPicklistDefinition struct {
	ID          uuid.UUID `json:"id"`
	ApiName     string    `json:"api_name"`
	Label       string    `json:"label"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type MetadataPicklistValue struct {
	ID                   uuid.UUID `json:"id"`
	PicklistDefinitionID uuid.UUID `json:"picklist_definition_id"`
	Value                string    `json:"value"`
	Label                string    `json:"label"`
	SortOrder            int32     `json:"sort_order"`
	IsDefault            bool      `json:"is_default"`
	IsActive             bool      `json:"is_active"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type MetadataPolymorphicTarget struct {
	ID        uuid.UUID `json:"id"`
	FieldID   uuid.UUID `json:"field_id"`
	ObjectID  uuid.UUID `json:"object_id"`
	CreatedAt time.Time `json:"created_at"`
}

type MetadataTranslation struct {
	ID           uuid.UUID `json:"id"`
	ResourceType string    `json:"resource_type"`
	ResourceID   uuid.UUID `json:"resource_id"`
	FieldName    string    `json:"field_name"`
	Locale       string    `json:"locale"`
	Value        string    `json:"value"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
