// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object_definitions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countObjectDefinitions = `-- name: CountObjectDefinitions :one
SELECT count(*) FROM metadata.object_definitions
`

func (q *Queries) CountObjectDefinitions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countObjectDefinitions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createObjectDefinition = `-- name: CreateObjectDefinition :one
INSERT INTO metadata.object_definitions (
    api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19
) RETURNING id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
`

type CreateObjectDefinitionParams struct {
	ApiName               string `json:"api_name"`
	Label                 string `json:"label"`
	PluralLabel           string `json:"plural_label"`
	Description           string `json:"description"`
	TableName             string `json:"table_name"`
	ObjectType            string `json:"object_type"`
	IsPlatformManaged     bool   `json:"is_platform_managed"`
	IsVisibleInSetup      bool   `json:"is_visible_in_setup"`
	IsCustomFieldsAllowed bool   `json:"is_custom_fields_allowed"`
	IsDeleteableObject    bool   `json:"is_deleteable_object"`
	IsCreateable          bool   `json:"is_createable"`
	IsUpdateable          bool   `json:"is_updateable"`
	IsDeleteable          bool   `json:"is_deleteable"`
	IsQueryable           bool   `json:"is_queryable"`
	IsSearchable          bool   `json:"is_searchable"`
	HasActivities         bool   `json:"has_activities"`
	HasNotes              bool   `json:"has_notes"`
	HasHistoryTracking    bool   `json:"has_history_tracking"`
	HasSharingRules       bool   `json:"has_sharing_rules"`
}

func (q *Queries) CreateObjectDefinition(ctx context.Context, arg CreateObjectDefinitionParams) (*MetadataObjectDefinition, error) {
	row := q.db.QueryRow(ctx, createObjectDefinition,
		arg.ApiName,
		arg.Label,
		arg.PluralLabel,
		arg.Description,
		arg.TableName,
		arg.ObjectType,
		arg.IsPlatformManaged,
		arg.IsVisibleInSetup,
		arg.IsCustomFieldsAllowed,
		arg.IsDeleteableObject,
		arg.IsCreateable,
		arg.IsUpdateable,
		arg.IsDeleteable,
		arg.IsQueryable,
		arg.IsSearchable,
		arg.HasActivities,
		arg.HasNotes,
		arg.HasHistoryTracking,
		arg.HasSharingRules,
	)
	var i MetadataObjectDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.PluralLabel,
		&i.Description,
		&i.TableName,
		&i.ObjectType,
		&i.IsPlatformManaged,
		&i.IsVisibleInSetup,
		&i.IsCustomFieldsAllowed,
		&i.IsDeleteableObject,
		&i.IsCreateable,
		&i.IsUpdateable,
		&i.IsDeleteable,
		&i.IsQueryable,
		&i.IsSearchable,
		&i.HasActivities,
		&i.HasNotes,
		&i.HasHistoryTracking,
		&i.HasSharingRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteObjectDefinition = `-- name: DeleteObjectDefinition :exec
DELETE FROM metadata.object_definitions WHERE id = $1
`

func (q *Queries) DeleteObjectDefinition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteObjectDefinition, id)
	return err
}

const getObjectDefinitionByAPIName = `-- name: GetObjectDefinitionByAPIName :one
SELECT id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
FROM metadata.object_definitions
WHERE api_name = $1
`

func (q *Queries) GetObjectDefinitionByAPIName(ctx context.Context, apiName string) (*MetadataObjectDefinition, error) {
	row := q.db.QueryRow(ctx, getObjectDefinitionByAPIName, apiName)
	var i MetadataObjectDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.PluralLabel,
		&i.Description,
		&i.TableName,
		&i.ObjectType,
		&i.IsPlatformManaged,
		&i.IsVisibleInSetup,
		&i.IsCustomFieldsAllowed,
		&i.IsDeleteableObject,
		&i.IsCreateable,
		&i.IsUpdateable,
		&i.IsDeleteable,
		&i.IsQueryable,
		&i.IsSearchable,
		&i.HasActivities,
		&i.HasNotes,
		&i.HasHistoryTracking,
		&i.HasSharingRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getObjectDefinitionByID = `-- name: GetObjectDefinitionByID :one
SELECT id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
FROM metadata.object_definitions
WHERE id = $1
`

func (q *Queries) GetObjectDefinitionByID(ctx context.Context, id uuid.UUID) (*MetadataObjectDefinition, error) {
	row := q.db.QueryRow(ctx, getObjectDefinitionByID, id)
	var i MetadataObjectDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.PluralLabel,
		&i.Description,
		&i.TableName,
		&i.ObjectType,
		&i.IsPlatformManaged,
		&i.IsVisibleInSetup,
		&i.IsCustomFieldsAllowed,
		&i.IsDeleteableObject,
		&i.IsCreateable,
		&i.IsUpdateable,
		&i.IsDeleteable,
		&i.IsQueryable,
		&i.IsSearchable,
		&i.HasActivities,
		&i.HasNotes,
		&i.HasHistoryTracking,
		&i.HasSharingRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAllObjectDefinitions = `-- name: ListAllObjectDefinitions :many
SELECT id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
FROM metadata.object_definitions
ORDER BY api_name
`

func (q *Queries) ListAllObjectDefinitions(ctx context.Context) ([]*MetadataObjectDefinition, error) {
	rows, err := q.db.Query(ctx, listAllObjectDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataObjectDefinition{}
	for rows.Next() {
		var i MetadataObjectDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ApiName,
			&i.Label,
			&i.PluralLabel,
			&i.Description,
			&i.TableName,
			&i.ObjectType,
			&i.IsPlatformManaged,
			&i.IsVisibleInSetup,
			&i.IsCustomFieldsAllowed,
			&i.IsDeleteableObject,
			&i.IsCreateable,
			&i.IsUpdateable,
			&i.IsDeleteable,
			&i.IsQueryable,
			&i.IsSearchable,
			&i.HasActivities,
			&i.HasNotes,
			&i.HasHistoryTracking,
			&i.HasSharingRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectDefinitions = `-- name: ListObjectDefinitions :many
SELECT id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
FROM metadata.object_definitions
ORDER BY api_name
LIMIT $1 OFFSET $2
`

type ListObjectDefinitionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListObjectDefinitions(ctx context.Context, arg ListObjectDefinitionsParams) ([]*MetadataObjectDefinition, error) {
	rows, err := q.db.Query(ctx, listObjectDefinitions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataObjectDefinition{}
	for rows.Next() {
		var i MetadataObjectDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ApiName,
			&i.Label,
			&i.PluralLabel,
			&i.Description,
			&i.TableName,
			&i.ObjectType,
			&i.IsPlatformManaged,
			&i.IsVisibleInSetup,
			&i.IsCustomFieldsAllowed,
			&i.IsDeleteableObject,
			&i.IsCreateable,
			&i.IsUpdateable,
			&i.IsDeleteable,
			&i.IsQueryable,
			&i.IsSearchable,
			&i.HasActivities,
			&i.HasNotes,
			&i.HasHistoryTracking,
			&i.HasSharingRules,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObjectDefinition = `-- name: UpdateObjectDefinition :one
UPDATE metadata.object_definitions SET
    label = $2,
    plural_label = $3,
    description = $4,
    is_visible_in_setup = $5,
    is_custom_fields_allowed = $6,
    is_deleteable_object = $7,
    is_createable = $8,
    is_updateable = $9,
    is_deleteable = $10,
    is_queryable = $11,
    is_searchable = $12,
    has_activities = $13,
    has_notes = $14,
    has_history_tracking = $15,
    has_sharing_rules = $16,
    updated_at = now()
WHERE id = $1
RETURNING id, api_name, label, plural_label, description, table_name, object_type,
    is_platform_managed, is_visible_in_setup, is_custom_fields_allowed, is_deleteable_object,
    is_createable, is_updateable, is_deleteable, is_queryable, is_searchable,
    has_activities, has_notes, has_history_tracking, has_sharing_rules,
    created_at, updated_at
`

type UpdateObjectDefinitionParams struct {
	ID                    uuid.UUID `json:"id"`
	Label                 string    `json:"label"`
	PluralLabel           string    `json:"plural_label"`
	Description           string    `json:"description"`
	IsVisibleInSetup      bool      `json:"is_visible_in_setup"`
	IsCustomFieldsAllowed bool      `json:"is_custom_fields_allowed"`
	IsDeleteableObject    bool      `json:"is_deleteable_object"`
	IsCreateable          bool      `json:"is_createable"`
	IsUpdateable          bool      `json:"is_updateable"`
	IsDeleteable          bool      `json:"is_deleteable"`
	IsQueryable           bool      `json:"is_queryable"`
	IsSearchable          bool      `json:"is_searchable"`
	HasActivities         bool      `json:"has_activities"`
	HasNotes              bool      `json:"has_notes"`
	HasHistoryTracking    bool      `json:"has_history_tracking"`
	HasSharingRules       bool      `json:"has_sharing_rules"`
}

func (q *Queries) UpdateObjectDefinition(ctx context.Context, arg UpdateObjectDefinitionParams) (*MetadataObjectDefinition, error) {
	row := q.db.QueryRow(ctx, updateObjectDefinition,
		arg.ID,
		arg.Label,
		arg.PluralLabel,
		arg.Description,
		arg.IsVisibleInSetup,
		arg.IsCustomFieldsAllowed,
		arg.IsDeleteableObject,
		arg.IsCreateable,
		arg.IsUpdateable,
		arg.IsDeleteable,
		arg.IsQueryable,
		arg.IsSearchable,
		arg.HasActivities,
		arg.HasNotes,
		arg.HasHistoryTracking,
		arg.HasSharingRules,
	)
	var i MetadataObjectDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.PluralLabel,
		&i.Description,
		&i.TableName,
		&i.ObjectType,
		&i.IsPlatformManaged,
		&i.IsVisibleInSetup,
		&i.IsCustomFieldsAllowed,
		&i.IsDeleteableObject,
		&i.IsCreateable,
		&i.IsUpdateable,
		&i.IsDeleteable,
		&i.IsQueryable,
		&i.IsSearchable,
		&i.HasActivities,
		&i.HasNotes,
		&i.HasHistoryTracking,
		&i.HasSharingRules,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
