// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: picklist_values.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPicklistValue = `-- name: CreatePicklistValue :one
INSERT INTO metadata.picklist_values (
    picklist_definition_id, value, label, sort_order, is_default, is_active
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, picklist_definition_id, value, label, sort_order, is_default, is_active,
    created_at, updated_at
`

type CreatePicklistValueParams struct {
	PicklistDefinitionID uuid.UUID `json:"picklist_definition_id"`
	Value                string    `json:"value"`
	Label                string    `json:"label"`
	SortOrder            int32     `json:"sort_order"`
	IsDefault            bool      `json:"is_default"`
	IsActive             bool      `json:"is_active"`
}

func (q *Queries) CreatePicklistValue(ctx context.Context, arg CreatePicklistValueParams) (*MetadataPicklistValue, error) {
	row := q.db.QueryRow(ctx, createPicklistValue,
		arg.PicklistDefinitionID,
		arg.Value,
		arg.Label,
		arg.SortOrder,
		arg.IsDefault,
		arg.IsActive,
	)
	var i MetadataPicklistValue
	err := row.Scan(
		&i.ID,
		&i.PicklistDefinitionID,
		&i.Value,
		&i.Label,
		&i.SortOrder,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePicklistValue = `-- name: DeletePicklistValue :exec
DELETE FROM metadata.picklist_values WHERE id = $1
`

func (q *Queries) DeletePicklistValue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePicklistValue, id)
	return err
}

const deletePicklistValuesByDefinitionID = `-- name: DeletePicklistValuesByDefinitionID :exec
DELETE FROM metadata.picklist_values WHERE picklist_definition_id = $1
`

func (q *Queries) DeletePicklistValuesByDefinitionID(ctx context.Context, picklistDefinitionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePicklistValuesByDefinitionID, picklistDefinitionID)
	return err
}

const getPicklistValueByID = `-- name: GetPicklistValueByID :one
SELECT id, picklist_definition_id, value, label, sort_order, is_default, is_active,
    created_at, updated_at
FROM metadata.picklist_values
WHERE id = $1
`

func (q *Queries) GetPicklistValueByID(ctx context.Context, id uuid.UUID) (*MetadataPicklistValue, error) {
	row := q.db.QueryRow(ctx, getPicklistValueByID, id)
	var i MetadataPicklistValue
	err := row.Scan(
		&i.ID,
		&i.PicklistDefinitionID,
		&i.Value,
		&i.Label,
		&i.SortOrder,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPicklistValuesByDefinitionID = `-- name: ListPicklistValuesByDefinitionID :many
SELECT id, picklist_definition_id, value, label, sort_order, is_default, is_active,
    created_at, updated_at
FROM metadata.picklist_values
WHERE picklist_definition_id = $1
ORDER BY sort_order, value
`

func (q *Queries) ListPicklistValuesByDefinitionID(ctx context.Context, picklistDefinitionID uuid.UUID) ([]*MetadataPicklistValue, error) {
	rows, err := q.db.Query(ctx, listPicklistValuesByDefinitionID, picklistDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataPicklistValue{}
	for rows.Next() {
		var i MetadataPicklistValue
		if err := rows.Scan(
			&i.ID,
			&i.PicklistDefinitionID,
			&i.Value,
			&i.Label,
			&i.SortOrder,
			&i.IsDefault,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePicklistValue = `-- name: UpdatePicklistValue :one
UPDATE metadata.picklist_values SET
    label = $2,
    sort_order = $3,
    is_default = $4,
    is_active = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, picklist_definition_id, value, label, sort_order, is_default, is_active,
    created_at, updated_at
`

type UpdatePicklistValueParams struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	SortOrder int32     `json:"sort_order"`
	IsDefault bool      `json:"is_default"`
	IsActive  bool      `json:"is_active"`
}

func (q *Queries) UpdatePicklistValue(ctx context.Context, arg UpdatePicklistValueParams) (*MetadataPicklistValue, error) {
	row := q.db.QueryRow(ctx, updatePicklistValue,
		arg.ID,
		arg.Label,
		arg.SortOrder,
		arg.IsDefault,
		arg.IsActive,
	)
	var i MetadataPicklistValue
	err := row.Scan(
		&i.ID,
		&i.PicklistDefinitionID,
		&i.Value,
		&i.Label,
		&i.SortOrder,
		&i.IsDefault,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
