// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: picklist_definitions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPicklistDefinition = `-- name: CreatePicklistDefinition :one
INSERT INTO metadata.picklist_definitions (
    api_name, label, description
) VALUES ($1, $2, $3)
RETURNING id, api_name, label, description, created_at, updated_at
`

type CreatePicklistDefinitionParams struct {
	ApiName     string `json:"api_name"`
	Label       string `json:"label"`
	Description string `json:"description"`
}

func (q *Queries) CreatePicklistDefinition(ctx context.Context, arg CreatePicklistDefinitionParams) (*MetadataPicklistDefinition, error) {
	row := q.db.QueryRow(ctx, createPicklistDefinition, arg.ApiName, arg.Label, arg.Description)
	var i MetadataPicklistDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deletePicklistDefinition = `-- name: DeletePicklistDefinition :exec
DELETE FROM metadata.picklist_definitions WHERE id = $1
`

func (q *Queries) DeletePicklistDefinition(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePicklistDefinition, id)
	return err
}

const getPicklistDefinitionByAPIName = `-- name: GetPicklistDefinitionByAPIName :one
SELECT id, api_name, label, description, created_at, updated_at
FROM metadata.picklist_definitions
WHERE api_name = $1
`

func (q *Queries) GetPicklistDefinitionByAPIName(ctx context.Context, apiName string) (*MetadataPicklistDefinition, error) {
	row := q.db.QueryRow(ctx, getPicklistDefinitionByAPIName, apiName)
	var i MetadataPicklistDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPicklistDefinitionByID = `-- name: GetPicklistDefinitionByID :one
SELECT id, api_name, label, description, created_at, updated_at
FROM metadata.picklist_definitions
WHERE id = $1
`

func (q *Queries) GetPicklistDefinitionByID(ctx context.Context, id uuid.UUID) (*MetadataPicklistDefinition, error) {
	row := q.db.QueryRow(ctx, getPicklistDefinitionByID, id)
	var i MetadataPicklistDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listPicklistDefinitions = `-- name: ListPicklistDefinitions :many
SELECT id, api_name, label, description, created_at, updated_at
FROM metadata.picklist_definitions
ORDER BY api_name
`

func (q *Queries) ListPicklistDefinitions(ctx context.Context) ([]*MetadataPicklistDefinition, error) {
	rows, err := q.db.Query(ctx, listPicklistDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataPicklistDefinition{}
	for rows.Next() {
		var i MetadataPicklistDefinition
		if err := rows.Scan(
			&i.ID,
			&i.ApiName,
			&i.Label,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePicklistDefinition = `-- name: UpdatePicklistDefinition :one
UPDATE metadata.picklist_definitions SET
    label = $2,
    description = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, api_name, label, description, created_at, updated_at
`

type UpdatePicklistDefinitionParams struct {
	ID          uuid.UUID `json:"id"`
	Label       string    `json:"label"`
	Description string    `json:"description"`
}

func (q *Queries) UpdatePicklistDefinition(ctx context.Context, arg UpdatePicklistDefinitionParams) (*MetadataPicklistDefinition, error) {
	row := q.db.QueryRow(ctx, updatePicklistDefinition, arg.ID, arg.Label, arg.Description)
	var i MetadataPicklistDefinition
	err := row.Scan(
		&i.ID,
		&i.ApiName,
		&i.Label,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
