// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polymorphic_targets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPolymorphicTarget = `-- name: CreatePolymorphicTarget :one
INSERT INTO metadata.polymorphic_targets (
    field_id, object_id
) VALUES ($1, $2)
RETURNING id, field_id, object_id, created_at
`

type CreatePolymorphicTargetParams struct {
	FieldID  uuid.UUID `json:"field_id"`
	ObjectID uuid.UUID `json:"object_id"`
}

func (q *Queries) CreatePolymorphicTarget(ctx context.Context, arg CreatePolymorphicTargetParams) (*MetadataPolymorphicTarget, error) {
	row := q.db.QueryRow(ctx, createPolymorphicTarget, arg.FieldID, arg.ObjectID)
	var i MetadataPolymorphicTarget
	err := row.Scan(
		&i.ID,
		&i.FieldID,
		&i.ObjectID,
		&i.CreatedAt,
	)
	return &i, err
}

const deletePolymorphicTarget = `-- name: DeletePolymorphicTarget :exec
DELETE FROM metadata.polymorphic_targets WHERE id = $1
`

func (q *Queries) DeletePolymorphicTarget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolymorphicTarget, id)
	return err
}

const deletePolymorphicTargetsByFieldID = `-- name: DeletePolymorphicTargetsByFieldID :exec
DELETE FROM metadata.polymorphic_targets WHERE field_id = $1
`

func (q *Queries) DeletePolymorphicTargetsByFieldID(ctx context.Context, fieldID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolymorphicTargetsByFieldID, fieldID)
	return err
}

const listAllPolymorphicTargets = `-- name: ListAllPolymorphicTargets :many
SELECT id, field_id, object_id, created_at
FROM metadata.polymorphic_targets
ORDER BY field_id, object_id
`

func (q *Queries) ListAllPolymorphicTargets(ctx context.Context) ([]*MetadataPolymorphicTarget, error) {
	rows, err := q.db.Query(ctx, listAllPolymorphicTargets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataPolymorphicTarget{}
	for rows.Next() {
		var i MetadataPolymorphicTarget
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ObjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolymorphicTargetsByFieldID = `-- name: ListPolymorphicTargetsByFieldID :many
SELECT id, field_id, object_id, created_at
FROM metadata.polymorphic_targets
WHERE field_id = $1
ORDER BY created_at
`

func (q *Queries) ListPolymorphicTargetsByFieldID(ctx context.Context, fieldID uuid.UUID) ([]*MetadataPolymorphicTarget, error) {
	rows, err := q.db.Query(ctx, listPolymorphicTargetsByFieldID, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*MetadataPolymorphicTarget{}
	for rows.Next() {
		var i MetadataPolymorphicTarget
		if err := rows.Scan(
			&i.ID,
			&i.FieldID,
			&i.ObjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
