// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CelValidateRequestContext.
const (
	CelValidateRequestContextDefaultExpr    CelValidateRequestContext = "default_expr"
	CelValidateRequestContextFunctionBody   CelValidateRequestContext = "function_body"
	CelValidateRequestContextValidationRule CelValidateRequestContext = "validation_rule"
	CelValidateRequestContextVisibilityExpr CelValidateRequestContext = "visibility_expr"
	CelValidateRequestContextWhenExpression CelValidateRequestContext = "when_expression"
)

// Defines values for CreateFieldRequestFieldSubtype.
const (
	CreateFieldRequestFieldSubtypeArea        CreateFieldRequestFieldSubtype = "area"
	CreateFieldRequestFieldSubtypeAssociation CreateFieldRequestFieldSubtype = "association"
	CreateFieldRequestFieldSubtypeAutoNumber  CreateFieldRequestFieldSubtype = "auto_number"
	CreateFieldRequestFieldSubtypeComposition CreateFieldRequestFieldSubtype = "composition"
	CreateFieldRequestFieldSubtypeCurrency    CreateFieldRequestFieldSubtype = "currency"
	CreateFieldRequestFieldSubtypeDate        CreateFieldRequestFieldSubtype = "date"
	CreateFieldRequestFieldSubtypeDatetime    CreateFieldRequestFieldSubtype = "datetime"
	CreateFieldRequestFieldSubtypeDecimal     CreateFieldRequestFieldSubtype = "decimal"
	CreateFieldRequestFieldSubtypeEmail       CreateFieldRequestFieldSubtype = "email"
	CreateFieldRequestFieldSubtypeInteger     CreateFieldRequestFieldSubtype = "integer"
	CreateFieldRequestFieldSubtypeMulti       CreateFieldRequestFieldSubtype = "multi"
	CreateFieldRequestFieldSubtypePercent     CreateFieldRequestFieldSubtype = "percent"
	CreateFieldRequestFieldSubtypePhone       CreateFieldRequestFieldSubtype = "phone"
	CreateFieldRequestFieldSubtypePlain       CreateFieldRequestFieldSubtype = "plain"
	CreateFieldRequestFieldSubtypePolymorphic CreateFieldRequestFieldSubtype = "polymorphic"
	CreateFieldRequestFieldSubtypeRich        CreateFieldRequestFieldSubtype = "rich"
	CreateFieldRequestFieldSubtypeSingle      CreateFieldRequestFieldSubtype = "single"
	CreateFieldRequestFieldSubtypeTime        CreateFieldRequestFieldSubtype = "time"
	CreateFieldRequestFieldSubtypeUrl         CreateFieldRequestFieldSubtype = "url"
)

// Defines values for CreateFieldRequestFieldType.
const (
	CreateFieldRequestFieldTypeBoolean   CreateFieldRequestFieldType = "boolean"
	CreateFieldRequestFieldTypeDatetime  CreateFieldRequestFieldType = "datetime"
	CreateFieldRequestFieldTypeNumber    CreateFieldRequestFieldType = "number"
	CreateFieldRequestFieldTypePicklist  CreateFieldRequestFieldType = "picklist"
	CreateFieldRequestFieldTypeReference CreateFieldRequestFieldType = "reference"
	CreateFieldRequestFieldTypeText      CreateFieldRequestFieldType = "text"
)

// Defines values for CreateFunctionRequestReturnType.
const (
	CreateFunctionRequestReturnTypeAny     CreateFunctionRequestReturnType = "any"
	CreateFunctionRequestReturnTypeBoolean CreateFunctionRequestReturnType = "boolean"
	CreateFunctionRequestReturnTypeList    CreateFunctionRequestReturnType = "list"
	CreateFunctionRequestReturnTypeMap     CreateFunctionRequestReturnType = "map"
	CreateFunctionRequestReturnTypeNumber  CreateFunctionRequestReturnType = "number"
	CreateFunctionRequestReturnTypeString  CreateFunctionRequestReturnType = "string"
)

// Defines values for CreateObjectRequestObjectType.
const (
	CreateObjectRequestObjectTypeCustom   CreateObjectRequestObjectType = "custom"
	CreateObjectRequestObjectTypeStandard CreateObjectRequestObjectType = "standard"
)

// Defines values for CreateObjectRequestVisibility.
const (
	CreateObjectRequestVisibilityControlledByParent CreateObjectRequestVisibility = "controlled_by_parent"
	CreateObjectRequestVisibilityPrivate            CreateObjectRequestVisibility = "private"
	CreateObjectRequestVisibilityPublicRead         CreateObjectRequestVisibility = "public_read"
	CreateObjectRequestVisibilityPublicReadWrite    CreateObjectRequestVisibility = "public_read_write"
)

// Defines values for CreateValidationRuleRequestSeverity.
const (
	CreateValidationRuleRequestSeverityError   CreateValidationRuleRequestSeverity = "error"
	CreateValidationRuleRequestSeverityWarning CreateValidationRuleRequestSeverity = "warning"
)

// Defines values for FieldConfigOnDelete.
const (
	Cascade  FieldConfigOnDelete = "cascade"
	Restrict FieldConfigOnDelete = "restrict"
	SetNull  FieldConfigOnDelete = "set_null"
)

// Defines values for FieldDefinitionSchemaFieldSubtype.
const (
	Area        FieldDefinitionSchemaFieldSubtype = "area"
	Association FieldDefinitionSchemaFieldSubtype = "association"
	AutoNumber  FieldDefinitionSchemaFieldSubtype = "auto_number"
	Composition FieldDefinitionSchemaFieldSubtype = "composition"
	Currency    FieldDefinitionSchemaFieldSubtype = "currency"
	Date        FieldDefinitionSchemaFieldSubtype = "date"
	Datetime    FieldDefinitionSchemaFieldSubtype = "datetime"
	Decimal     FieldDefinitionSchemaFieldSubtype = "decimal"
	Email       FieldDefinitionSchemaFieldSubtype = "email"
	Integer     FieldDefinitionSchemaFieldSubtype = "integer"
	Multi       FieldDefinitionSchemaFieldSubtype = "multi"
	Percent     FieldDefinitionSchemaFieldSubtype = "percent"
	Phone       FieldDefinitionSchemaFieldSubtype = "phone"
	Plain       FieldDefinitionSchemaFieldSubtype = "plain"
	Polymorphic FieldDefinitionSchemaFieldSubtype = "polymorphic"
	Rich        FieldDefinitionSchemaFieldSubtype = "rich"
	Single      FieldDefinitionSchemaFieldSubtype = "single"
	Time        FieldDefinitionSchemaFieldSubtype = "time"
	Url         FieldDefinitionSchemaFieldSubtype = "url"
)

// Defines values for FieldDefinitionSchemaFieldType.
const (
	FieldDefinitionSchemaFieldTypeBoolean   FieldDefinitionSchemaFieldType = "boolean"
	FieldDefinitionSchemaFieldTypeDatetime  FieldDefinitionSchemaFieldType = "datetime"
	FieldDefinitionSchemaFieldTypeNumber    FieldDefinitionSchemaFieldType = "number"
	FieldDefinitionSchemaFieldTypePicklist  FieldDefinitionSchemaFieldType = "picklist"
	FieldDefinitionSchemaFieldTypeReference FieldDefinitionSchemaFieldType = "reference"
	FieldDefinitionSchemaFieldTypeText      FieldDefinitionSchemaFieldType = "text"
)

// Defines values for FunctionReturnType.
const (
	FunctionReturnTypeAny     FunctionReturnType = "any"
	FunctionReturnTypeBoolean FunctionReturnType = "boolean"
	FunctionReturnTypeList    FunctionReturnType = "list"
	FunctionReturnTypeMap     FunctionReturnType = "map"
	FunctionReturnTypeNumber  FunctionReturnType = "number"
	FunctionReturnTypeString  FunctionReturnType = "string"
)

// Defines values for FunctionParamType.
const (
	FunctionParamTypeAny     FunctionParamType = "any"
	FunctionParamTypeBoolean FunctionParamType = "boolean"
	FunctionParamTypeList    FunctionParamType = "list"
	FunctionParamTypeMap     FunctionParamType = "map"
	FunctionParamTypeNumber  FunctionParamType = "number"
	FunctionParamTypeString  FunctionParamType = "string"
)

// Defines values for ObjectDefinitionObjectType.
const (
	ObjectDefinitionObjectTypeCustom   ObjectDefinitionObjectType = "custom"
	ObjectDefinitionObjectTypeStandard ObjectDefinitionObjectType = "standard"
)

// Defines values for ObjectDefinitionVisibility.
const (
	ObjectDefinitionVisibilityControlledByParent ObjectDefinitionVisibility = "controlled_by_parent"
	ObjectDefinitionVisibilityPrivate            ObjectDefinitionVisibility = "private"
	ObjectDefinitionVisibilityPublicRead         ObjectDefinitionVisibility = "public_read"
	ObjectDefinitionVisibilityPublicReadWrite    ObjectDefinitionVisibility = "public_read_write"
)

// Defines values for TemplateInfoStatus.
const (
	Applied   TemplateInfoStatus = "applied"
	Available TemplateInfoStatus = "available"
	Blocked   TemplateInfoStatus = "blocked"
)

// Defines values for UpdateFunctionRequestReturnType.
const (
	Any     UpdateFunctionRequestReturnType = "any"
	Boolean UpdateFunctionRequestReturnType = "boolean"
	List    UpdateFunctionRequestReturnType = "list"
	Map     UpdateFunctionRequestReturnType = "map"
	Number  UpdateFunctionRequestReturnType = "number"
	String  UpdateFunctionRequestReturnType = "string"
)

// Defines values for UpdateObjectRequestVisibility.
const (
	ControlledByParent UpdateObjectRequestVisibility = "controlled_by_parent"
	Private            UpdateObjectRequestVisibility = "private"
	PublicRead         UpdateObjectRequestVisibility = "public_read"
	PublicReadWrite    UpdateObjectRequestVisibility = "public_read_write"
)

// Defines values for UpdateValidationRuleRequestSeverity.
const (
	UpdateValidationRuleRequestSeverityError   UpdateValidationRuleRequestSeverity = "error"
	UpdateValidationRuleRequestSeverityWarning UpdateValidationRuleRequestSeverity = "warning"
)

// Defines values for ValidationRuleSeverity.
const (
	Error   ValidationRuleSeverity = "error"
	Warning ValidationRuleSeverity = "warning"
)

// Defines values for ListObjectsParamsObjectType.
const (
	Custom   ListObjectsParamsObjectType = "custom"
	Standard ListObjectsParamsObjectType = "standard"
)

// CelParamDef defines model for CelParamDef.
type CelParamDef struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// CelValidateError defines model for CelValidateError.
type CelValidateError struct {
	Column  *int   `json:"column,omitempty"`
	Line    *int   `json:"line,omitempty"`
	Message string `json:"message"`
}

// CelValidateRequest defines model for CelValidateRequest.
type CelValidateRequest struct {
	Context       CelValidateRequestContext `json:"context"`
	Expression    string                    `json:"expression"`
	ObjectApiName *string                   `json:"object_api_name,omitempty"`
	Params        *[]CelParamDef            `json:"params,omitempty"`
}

// CelValidateRequestContext defines model for CelValidateRequest.Context.
type CelValidateRequestContext string

// CelValidateResponse defines model for CelValidateResponse.
type CelValidateResponse struct {
	Errors     *[]CelValidateError `json:"errors,omitempty"`
	ReturnType *string             `json:"return_type,omitempty"`
	Valid      bool                `json:"valid"`
}

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	ApiName            string                          `json:"api_name"`
	Config             *FieldConfig                    `json:"config,omitempty"`
	Description        *string                         `json:"description,omitempty"`
	FieldSubtype       *CreateFieldRequestFieldSubtype `json:"field_subtype,omitempty"`
	FieldType          CreateFieldRequestFieldType     `json:"field_type"`
	HelpText           *string                         `json:"help_text,omitempty"`
	IsCustom           *bool                           `json:"is_custom,omitempty"`
	IsRequired         *bool                           `json:"is_required,omitempty"`
	IsUnique           *bool                           `json:"is_unique,omitempty"`
	Label              string                          `json:"label"`
	ReferencedObjectId *openapi_types.UUID             `json:"referenced_object_id,omitempty"`
	SortOrder          *int                            `json:"sort_order,omitempty"`
}

// CreateFieldRequestFieldSubtype defines model for CreateFieldRequest.FieldSubtype.
type CreateFieldRequestFieldSubtype string

// CreateFieldRequestFieldType defines model for CreateFieldRequest.FieldType.
type CreateFieldRequestFieldType string

// CreateFunctionRequest defines model for CreateFunctionRequest.
type CreateFunctionRequest struct {
	Body        string                           `json:"body"`
	Description *string                          `json:"description,omitempty"`
	Name        string                           `json:"name"`
	Params      *[]FunctionParam                 `json:"params,omitempty"`
	ReturnType  *CreateFunctionRequestReturnType `json:"return_type,omitempty"`
}

// CreateFunctionRequestReturnType defines model for CreateFunctionRequest.ReturnType.
type CreateFunctionRequestReturnType string

// CreateObjectRequest defines model for CreateObjectRequest.
type CreateObjectRequest struct {
	ApiName               string                         `json:"api_name"`
	Description           *string                        `json:"description,omitempty"`
	HasActivities         *bool                          `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                          `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                          `json:"has_notes,omitempty"`
	HasSharingRules       *bool                          `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool                          `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                          `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                          `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                          `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool                          `json:"is_queryable,omitempty"`
	IsSearchable          *bool                          `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                          `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                          `json:"is_visible_in_setup,omitempty"`
	Label                 string                         `json:"label"`
	ObjectType            CreateObjectRequestObjectType  `json:"object_type"`
	PluralLabel           string                         `json:"plural_label"`
	Visibility            *CreateObjectRequestVisibility `json:"visibility,omitempty"`
}

// CreateObjectRequestObjectType defines model for CreateObjectRequest.ObjectType.
type CreateObjectRequestObjectType string

// CreateObjectRequestVisibility defines model for CreateObjectRequest.Visibility.
type CreateObjectRequestVisibility string

// CreateValidationRuleRequest defines model for CreateValidationRuleRequest.
type CreateValidationRuleRequest struct {
	ApiName      string  `json:"api_name"`
	AppliesTo    *string `json:"applies_to,omitempty"`
	Description  *string `json:"description,omitempty"`
	ErrorCode    *string `json:"error_code,omitempty"`
	ErrorMessage string  `json:"error_message"`

	// Expression CEL expression that must return true for valid data
	Expression string                               `json:"expression"`
	IsActive   *bool                                `json:"is_active,omitempty"`
	Label      string                               `json:"label"`
	Severity   *CreateValidationRuleRequestSeverity `json:"severity,omitempty"`
	SortOrder  *int                                 `json:"sort_order,omitempty"`

	// WhenExpression Optional CEL condition for when this rule applies
	WhenExpression *string `json:"when_expression,omitempty"`
}

// CreateValidationRuleRequestSeverity defines model for CreateValidationRuleRequest.Severity.
type CreateValidationRuleRequestSeverity string

// DMLRequest defines model for DMLRequest.
type DMLRequest struct {
	// Statement DML statement string
	Statement string `json:"statement"`
}

// DMLResult defines model for DMLResult.
type DMLResult struct {
	// DeletedIds IDs of deleted records
	DeletedIds *[]string `json:"deletedIds,omitempty"`

	// InsertedIds IDs of inserted records
	InsertedIds *[]string `json:"insertedIds,omitempty"`

	// RowsAffected Number of rows affected
	RowsAffected *int64 `json:"rowsAffected,omitempty"`

	// UpdatedIds IDs of updated records
	UpdatedIds *[]string `json:"updatedIds,omitempty"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// FieldConfig defines model for FieldConfig.
type FieldConfig struct {
	// DefaultExpr CEL expression for dynamic default value
	DefaultExpr *string `json:"default_expr,omitempty"`

	// DefaultOn When to apply default (create, update, create,update)
	DefaultOn        *string              `json:"default_on,omitempty"`
	DefaultValue     *string              `json:"default_value,omitempty"`
	Format           *string              `json:"format,omitempty"`
	IsReparentable   *bool                `json:"is_reparentable,omitempty"`
	MaxLength        *int                 `json:"max_length,omitempty"`
	OnDelete         *FieldConfigOnDelete `json:"on_delete,omitempty"`
	Precision        *int                 `json:"precision,omitempty"`
	RelationshipName *string              `json:"relationship_name,omitempty"`
	Scale            *int                 `json:"scale,omitempty"`
	StartValue       *int                 `json:"start_value,omitempty"`
}

// FieldConfigOnDelete defines model for FieldConfig.OnDelete.
type FieldConfigOnDelete string

// FieldDefinitionSchema defines model for FieldDefinitionSchema.
type FieldDefinitionSchema struct {
	ApiName            string                             `json:"api_name"`
	Config             FieldConfig                        `json:"config"`
	CreatedAt          time.Time                          `json:"created_at"`
	Description        string                             `json:"description"`
	FieldSubtype       *FieldDefinitionSchemaFieldSubtype `json:"field_subtype,omitempty"`
	FieldType          FieldDefinitionSchemaFieldType     `json:"field_type"`
	HelpText           string                             `json:"help_text"`
	Id                 openapi_types.UUID                 `json:"id"`
	IsCustom           bool                               `json:"is_custom"`
	IsPlatformManaged  bool                               `json:"is_platform_managed"`
	IsRequired         bool                               `json:"is_required"`
	IsSystemField      bool                               `json:"is_system_field"`
	IsUnique           bool                               `json:"is_unique"`
	Label              string                             `json:"label"`
	ObjectId           openapi_types.UUID                 `json:"object_id"`
	ReferencedObjectId *openapi_types.UUID                `json:"referenced_object_id,omitempty"`
	SortOrder          int                                `json:"sort_order"`
	UpdatedAt          time.Time                          `json:"updated_at"`
}

// FieldDefinitionSchemaFieldSubtype defines model for FieldDefinitionSchema.FieldSubtype.
type FieldDefinitionSchemaFieldSubtype string

// FieldDefinitionSchemaFieldType defines model for FieldDefinitionSchema.FieldType.
type FieldDefinitionSchemaFieldType string

// FieldDescribe defines model for FieldDescribe.
type FieldDescribe struct {
	ApiName string `json:"api_name"`
	Config  struct {
		DefaultValue *string `json:"default_value,omitempty"`
		MaxLength    *int    `json:"max_length,omitempty"`
		Precision    *int    `json:"precision,omitempty"`
		Scale        *int    `json:"scale,omitempty"`
		Values       *[]struct {
			Id        string `json:"id"`
			IsActive  bool   `json:"is_active"`
			IsDefault bool   `json:"is_default"`
			Label     string `json:"label"`
			SortOrder int    `json:"sort_order"`
			Value     string `json:"value"`
		} `json:"values,omitempty"`
	} `json:"config"`
	FieldSubtype  *string `json:"field_subtype"`
	FieldType     string  `json:"field_type"`
	IsReadOnly    bool    `json:"is_read_only"`
	IsRequired    bool    `json:"is_required"`
	IsSystemField bool    `json:"is_system_field"`
	Label         string  `json:"label"`
	SortOrder     int     `json:"sort_order"`
}

// FieldListResponse defines model for FieldListResponse.
type FieldListResponse struct {
	Data *[]FieldDefinitionSchema `json:"data,omitempty"`
}

// FieldResponse defines model for FieldResponse.
type FieldResponse struct {
	Data *FieldDefinitionSchema `json:"data,omitempty"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Function defines model for Function.
type Function struct {
	Body        *string             `json:"body,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Params      *[]FunctionParam    `json:"params,omitempty"`
	ReturnType  *FunctionReturnType `json:"return_type,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// FunctionReturnType defines model for Function.ReturnType.
type FunctionReturnType string

// FunctionParam defines model for FunctionParam.
type FunctionParam struct {
	Description *string           `json:"description,omitempty"`
	Name        string            `json:"name"`
	Type        FunctionParamType `json:"type"`
}

// FunctionParamType defines model for FunctionParam.Type.
type FunctionParamType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ObjectDefinition defines model for ObjectDefinition.
type ObjectDefinition struct {
	ApiName               string                     `json:"api_name"`
	CreatedAt             time.Time                  `json:"created_at"`
	Description           string                     `json:"description"`
	HasActivities         bool                       `json:"has_activities"`
	HasHistoryTracking    bool                       `json:"has_history_tracking"`
	HasNotes              bool                       `json:"has_notes"`
	HasSharingRules       bool                       `json:"has_sharing_rules"`
	Id                    openapi_types.UUID         `json:"id"`
	IsCreateable          bool                       `json:"is_createable"`
	IsCustomFieldsAllowed bool                       `json:"is_custom_fields_allowed"`
	IsDeleteable          bool                       `json:"is_deleteable"`
	IsDeleteableObject    bool                       `json:"is_deleteable_object"`
	IsPlatformManaged     bool                       `json:"is_platform_managed"`
	IsQueryable           bool                       `json:"is_queryable"`
	IsSearchable          bool                       `json:"is_searchable"`
	IsUpdateable          bool                       `json:"is_updateable"`
	IsVisibleInSetup      bool                       `json:"is_visible_in_setup"`
	Label                 string                     `json:"label"`
	ObjectType            ObjectDefinitionObjectType `json:"object_type"`
	PluralLabel           string                     `json:"plural_label"`
	UpdatedAt             time.Time                  `json:"updated_at"`
	Visibility            ObjectDefinitionVisibility `json:"visibility"`
}

// ObjectDefinitionObjectType defines model for ObjectDefinition.ObjectType.
type ObjectDefinitionObjectType string

// ObjectDefinitionVisibility defines model for ObjectDefinition.Visibility.
type ObjectDefinitionVisibility string

// ObjectDescribe defines model for ObjectDescribe.
type ObjectDescribe struct {
	ApiName      string          `json:"api_name"`
	Fields       []FieldDescribe `json:"fields"`
	IsCreateable bool            `json:"is_createable"`
	IsDeleteable bool            `json:"is_deleteable"`
	IsUpdateable bool            `json:"is_updateable"`
	Label        string          `json:"label"`
	PluralLabel  string          `json:"plural_label"`
}

// ObjectListResponse defines model for ObjectListResponse.
type ObjectListResponse struct {
	Data       *[]ObjectDefinition `json:"data,omitempty"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

// ObjectNavItem defines model for ObjectNavItem.
type ObjectNavItem struct {
	ApiName      string `json:"api_name"`
	IsCreateable bool   `json:"is_createable"`
	IsQueryable  bool   `json:"is_queryable"`
	Label        string `json:"label"`
	PluralLabel  string `json:"plural_label"`
}

// ObjectResponse defines model for ObjectResponse.
type ObjectResponse struct {
	Data *ObjectDefinition `json:"data,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int   `json:"page"`
	PerPage    int   `json:"per_page"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"total_pages"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// SOQLRequest defines model for SOQLRequest.
type SOQLRequest struct {
	// PageSize Maximum number of records per page
	PageSize *int `json:"pageSize,omitempty"`

	// Query SOQL query string
	Query string `json:"query"`
}

// SOQLResult defines model for SOQLResult.
type SOQLResult struct {
	// Done Whether all records have been returned
	Done *bool `json:"done,omitempty"`

	// NextRecordsUrl Cursor for fetching the next page (empty if done)
	NextRecordsUrl *string `json:"nextRecordsUrl,omitempty"`

	// Records Query result records
	Records *[]map[string]interface{} `json:"records,omitempty"`

	// TotalSize Total number of records returned
	TotalSize *int `json:"totalSize,omitempty"`
}

// SetPasswordRequest defines model for SetPasswordRequest.
type SetPasswordRequest struct {
	Password string `json:"password"`
}

// TemplateApplyResponse defines model for TemplateApplyResponse.
type TemplateApplyResponse struct {
	Data *struct {
		Message    *string `json:"message,omitempty"`
		TemplateId *string `json:"template_id,omitempty"`
	} `json:"data,omitempty"`
}

// TemplateInfo defines model for TemplateInfo.
type TemplateInfo struct {
	Description *string             `json:"description,omitempty"`
	Fields      *int                `json:"fields,omitempty"`
	Id          *string             `json:"id,omitempty"`
	Label       *string             `json:"label,omitempty"`
	Objects     *int                `json:"objects,omitempty"`
	Status      *TemplateInfoStatus `json:"status,omitempty"`
}

// TemplateInfoStatus defines model for TemplateInfo.Status.
type TemplateInfoStatus string

// TemplateListResponse defines model for TemplateListResponse.
type TemplateListResponse struct {
	Data *[]TemplateInfo `json:"data,omitempty"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// TokenPairResponse defines model for TokenPairResponse.
type TokenPairResponse struct {
	Data *TokenPair `json:"data,omitempty"`
}

// UpdateFieldRequest defines model for UpdateFieldRequest.
type UpdateFieldRequest struct {
	Config      *FieldConfig `json:"config,omitempty"`
	Description *string      `json:"description,omitempty"`
	HelpText    *string      `json:"help_text,omitempty"`
	IsRequired  *bool        `json:"is_required,omitempty"`
	IsUnique    *bool        `json:"is_unique,omitempty"`
	Label       string       `json:"label"`
	SortOrder   *int         `json:"sort_order,omitempty"`
}

// UpdateFunctionRequest defines model for UpdateFunctionRequest.
type UpdateFunctionRequest struct {
	Body        string                           `json:"body"`
	Description *string                          `json:"description,omitempty"`
	Params      *[]FunctionParam                 `json:"params,omitempty"`
	ReturnType  *UpdateFunctionRequestReturnType `json:"return_type,omitempty"`
}

// UpdateFunctionRequestReturnType defines model for UpdateFunctionRequest.ReturnType.
type UpdateFunctionRequestReturnType string

// UpdateObjectRequest defines model for UpdateObjectRequest.
type UpdateObjectRequest struct {
	Description           *string                        `json:"description,omitempty"`
	HasActivities         *bool                          `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                          `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                          `json:"has_notes,omitempty"`
	HasSharingRules       *bool                          `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool                          `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                          `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                          `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                          `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool                          `json:"is_queryable,omitempty"`
	IsSearchable          *bool                          `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                          `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                          `json:"is_visible_in_setup,omitempty"`
	Label                 string                         `json:"label"`
	PluralLabel           string                         `json:"plural_label"`
	Visibility            *UpdateObjectRequestVisibility `json:"visibility,omitempty"`
}

// UpdateObjectRequestVisibility defines model for UpdateObjectRequest.Visibility.
type UpdateObjectRequestVisibility string

// UpdateValidationRuleRequest defines model for UpdateValidationRuleRequest.
type UpdateValidationRuleRequest struct {
	AppliesTo      *string                              `json:"applies_to,omitempty"`
	Description    *string                              `json:"description,omitempty"`
	ErrorCode      *string                              `json:"error_code,omitempty"`
	ErrorMessage   string                               `json:"error_message"`
	Expression     string                               `json:"expression"`
	IsActive       *bool                                `json:"is_active,omitempty"`
	Label          string                               `json:"label"`
	Severity       *UpdateValidationRuleRequestSeverity `json:"severity,omitempty"`
	SortOrder      *int                                 `json:"sort_order,omitempty"`
	WhenExpression *string                              `json:"when_expression,omitempty"`
}

// UpdateValidationRuleRequestSeverity defines model for UpdateValidationRuleRequest.Severity.
type UpdateValidationRuleRequestSeverity string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email     string              `json:"email"`
	FirstName string              `json:"first_name"`
	Id        openapi_types.UUID  `json:"id"`
	IsActive  bool                `json:"is_active"`
	LastName  string              `json:"last_name"`
	ProfileId openapi_types.UUID  `json:"profile_id"`
	RoleId    *openapi_types.UUID `json:"role_id"`
	Username  string              `json:"username"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Data *UserInfo `json:"data,omitempty"`
}

// ValidationRule defines model for ValidationRule.
type ValidationRule struct {
	ApiName        string                 `json:"api_name"`
	AppliesTo      string                 `json:"applies_to"`
	CreatedAt      time.Time              `json:"created_at"`
	Description    string                 `json:"description"`
	ErrorCode      string                 `json:"error_code"`
	ErrorMessage   string                 `json:"error_message"`
	Expression     string                 `json:"expression"`
	Id             openapi_types.UUID     `json:"id"`
	IsActive       bool                   `json:"is_active"`
	Label          string                 `json:"label"`
	ObjectId       openapi_types.UUID     `json:"object_id"`
	Severity       ValidationRuleSeverity `json:"severity"`
	SortOrder      int                    `json:"sort_order"`
	UpdatedAt      time.Time              `json:"updated_at"`
	WhenExpression *string                `json:"when_expression"`
}

// ValidationRuleSeverity defines model for ValidationRule.Severity.
type ValidationRuleSeverity string

// ValidationRuleListResponse defines model for ValidationRuleListResponse.
type ValidationRuleListResponse struct {
	Data *[]ValidationRule `json:"data,omitempty"`
}

// ValidationRuleResponse defines model for ValidationRuleResponse.
type ValidationRuleResponse struct {
	Data *ValidationRule `json:"data,omitempty"`
}

// FieldId defines model for FieldId.
type FieldId = openapi_types.UUID

// FunctionId defines model for FunctionId.
type FunctionId = openapi_types.UUID

// ObjectId defines model for ObjectId.
type ObjectId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// RuleId defines model for RuleId.
type RuleId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListObjectsParams defines parameters for ListObjects.
type ListObjectsParams struct {
	Page       *int                         `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int                         `form:"per_page,omitempty" json:"per_page,omitempty"`
	ObjectType *ListObjectsParamsObjectType `form:"object_type,omitempty" json:"object_type,omitempty"`
}

// ListObjectsParamsObjectType defines parameters for ListObjects.
type ListObjectsParamsObjectType string

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// ExecuteQueryGetParams defines parameters for ExecuteQueryGet.
type ExecuteQueryGetParams struct {
	// Q SOQL query string
	Q string `form:"q" json:"q"`
}

// ListRecordsParams defines parameters for ListRecords.
type ListRecordsParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateRecordJSONBody defines parameters for CreateRecord.
type CreateRecordJSONBody map[string]interface{}

// UpdateRecordJSONBody defines parameters for UpdateRecord.
type UpdateRecordJSONBody map[string]interface{}

// ValidateCelExpressionJSONRequestBody defines body for ValidateCelExpression for application/json ContentType.
type ValidateCelExpressionJSONRequestBody = CelValidateRequest

// CreateFunctionJSONRequestBody defines body for CreateFunction for application/json ContentType.
type CreateFunctionJSONRequestBody = CreateFunctionRequest

// UpdateFunctionJSONRequestBody defines body for UpdateFunction for application/json ContentType.
type UpdateFunctionJSONRequestBody = UpdateFunctionRequest

// CreateObjectJSONRequestBody defines body for CreateObject for application/json ContentType.
type CreateObjectJSONRequestBody = CreateObjectRequest

// UpdateObjectJSONRequestBody defines body for UpdateObject for application/json ContentType.
type UpdateObjectJSONRequestBody = UpdateObjectRequest

// CreateFieldJSONRequestBody defines body for CreateField for application/json ContentType.
type CreateFieldJSONRequestBody = CreateFieldRequest

// UpdateFieldJSONRequestBody defines body for UpdateField for application/json ContentType.
type UpdateFieldJSONRequestBody = UpdateFieldRequest

// CreateValidationRuleJSONRequestBody defines body for CreateValidationRule for application/json ContentType.
type CreateValidationRuleJSONRequestBody = CreateValidationRuleRequest

// UpdateValidationRuleJSONRequestBody defines body for UpdateValidationRule for application/json ContentType.
type UpdateValidationRuleJSONRequestBody = UpdateValidationRuleRequest

// SetUserPasswordJSONRequestBody defines body for SetUserPassword for application/json ContentType.
type SetUserPasswordJSONRequestBody = SetPasswordRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ExecuteDMLJSONRequestBody defines body for ExecuteDML for application/json ContentType.
type ExecuteDMLJSONRequestBody = DMLRequest

// ExecuteQueryPostJSONRequestBody defines body for ExecuteQueryPost for application/json ContentType.
type ExecuteQueryPostJSONRequestBody = SOQLRequest

// CreateRecordJSONRequestBody defines body for CreateRecord for application/json ContentType.
type CreateRecordJSONRequestBody CreateRecordJSONBody

// UpdateRecordJSONRequestBody defines body for UpdateRecord for application/json ContentType.
type UpdateRecordJSONRequestBody UpdateRecordJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Validate a CEL expression
	// (POST /api/v1/admin/cel/validate)
	ValidateCelExpression(c *gin.Context)
	// List all custom functions
	// (GET /api/v1/admin/functions)
	ListFunctions(c *gin.Context)
	// Create a custom function
	// (POST /api/v1/admin/functions)
	CreateFunction(c *gin.Context)
	// Delete a custom function
	// (DELETE /api/v1/admin/functions/{functionId})
	DeleteFunction(c *gin.Context, functionId FunctionId)
	// Get a custom function by ID
	// (GET /api/v1/admin/functions/{functionId})
	GetFunction(c *gin.Context, functionId FunctionId)
	// Update a custom function
	// (PUT /api/v1/admin/functions/{functionId})
	UpdateFunction(c *gin.Context, functionId FunctionId)
	// List object definitions
	// (GET /api/v1/admin/metadata/objects)
	ListObjects(c *gin.Context, params ListObjectsParams)
	// Create object definition
	// (POST /api/v1/admin/metadata/objects)
	CreateObject(c *gin.Context)
	// Delete object definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId})
	DeleteObject(c *gin.Context, objectId ObjectId)
	// Get object definition
	// (GET /api/v1/admin/metadata/objects/{objectId})
	GetObject(c *gin.Context, objectId ObjectId)
	// Update object definition
	// (PUT /api/v1/admin/metadata/objects/{objectId})
	UpdateObject(c *gin.Context, objectId ObjectId)
	// List field definitions for object
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields)
	ListFields(c *gin.Context, objectId ObjectId)
	// Create field definition
	// (POST /api/v1/admin/metadata/objects/{objectId}/fields)
	CreateField(c *gin.Context, objectId ObjectId)
	// Delete field definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	DeleteField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Get field definition
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	GetField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Update field definition
	// (PUT /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	UpdateField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// List validation rules for object
	// (GET /api/v1/admin/metadata/objects/{objectId}/rules)
	ListValidationRules(c *gin.Context, objectId ObjectId)
	// Create validation rule
	// (POST /api/v1/admin/metadata/objects/{objectId}/rules)
	CreateValidationRule(c *gin.Context, objectId ObjectId)
	// Delete validation rule
	// (DELETE /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	DeleteValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// Get validation rule
	// (GET /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	GetValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// Update validation rule
	// (PUT /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	UpdateValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// Set user password (admin)
	// (PUT /api/v1/admin/security/users/{userId}/password)
	SetUserPassword(c *gin.Context, userId openapi_types.UUID)
	// List available application templates
	// (GET /api/v1/admin/templates)
	ListTemplates(c *gin.Context)
	// Apply an application template
	// (POST /api/v1/admin/templates/{templateId}/apply)
	ApplyTemplate(c *gin.Context, templateId string)
	// Request password reset
	// (POST /api/v1/auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Authenticate user
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// Logout (revoke refresh token)
	// (POST /api/v1/auth/logout)
	Logout(c *gin.Context)
	// Get current user info
	// (GET /api/v1/auth/me)
	GetMe(c *gin.Context)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(c *gin.Context)
	// Reset password with token
	// (POST /api/v1/auth/reset-password)
	ResetPassword(c *gin.Context)
	// Execute DML statement
	// (POST /api/v1/data)
	ExecuteDML(c *gin.Context)
	// List accessible objects for navigation
	// (GET /api/v1/describe)
	ListDescribeObjects(c *gin.Context)
	// Describe object with fields
	// (GET /api/v1/describe/{objectName})
	DescribeObject(c *gin.Context, objectName string)
	// Execute SOQL query (GET)
	// (GET /api/v1/query)
	ExecuteQueryGet(c *gin.Context, params ExecuteQueryGetParams)
	// Execute SOQL query (POST)
	// (POST /api/v1/query)
	ExecuteQueryPost(c *gin.Context)
	// List records for an object
	// (GET /api/v1/records/{objectName})
	ListRecords(c *gin.Context, objectName string, params ListRecordsParams)
	// Create a record
	// (POST /api/v1/records/{objectName})
	CreateRecord(c *gin.Context, objectName string)
	// Delete a record
	// (DELETE /api/v1/records/{objectName}/{recordId})
	DeleteRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Get a record by ID
	// (GET /api/v1/records/{objectName}/{recordId})
	GetRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Update a record
	// (PUT /api/v1/records/{objectName}/{recordId})
	UpdateRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Health check
	// (GET /healthz)
	HealthCheck(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ValidateCelExpression operation middleware
func (siw *ServerInterfaceWrapper) ValidateCelExpression(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateCelExpression(c)
}

// ListFunctions operation middleware
func (siw *ServerInterfaceWrapper) ListFunctions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFunctions(c)
}

// CreateFunction operation middleware
func (siw *ServerInterfaceWrapper) CreateFunction(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateFunction(c)
}

// DeleteFunction operation middleware
func (siw *ServerInterfaceWrapper) DeleteFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteFunction(c, functionId)
}

// GetFunction operation middleware
func (siw *ServerInterfaceWrapper) GetFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFunction(c, functionId)
}

// UpdateFunction operation middleware
func (siw *ServerInterfaceWrapper) UpdateFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateFunction(c, functionId)
}

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "object_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "object_type", c.Request.URL.Query(), &params.ObjectType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter object_type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjects(c, params)
}

// CreateObject operation middleware
func (siw *ServerInterfaceWrapper) CreateObject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateObject(c)
}

// DeleteObject operation middleware
func (siw *ServerInterfaceWrapper) DeleteObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteObject(c, objectId)
}

// GetObject operation middleware
func (siw *ServerInterfaceWrapper) GetObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetObject(c, objectId)
}

// UpdateObject operation middleware
func (siw *ServerInterfaceWrapper) UpdateObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateObject(c, objectId)
}

// ListFields operation middleware
func (siw *ServerInterfaceWrapper) ListFields(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFields(c, objectId)
}

// CreateField operation middleware
func (siw *ServerInterfaceWrapper) CreateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateField(c, objectId)
}

// DeleteField operation middleware
func (siw *ServerInterfaceWrapper) DeleteField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteField(c, objectId, fieldId)
}

// GetField operation middleware
func (siw *ServerInterfaceWrapper) GetField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetField(c, objectId, fieldId)
}

// UpdateField operation middleware
func (siw *ServerInterfaceWrapper) UpdateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateField(c, objectId, fieldId)
}

// ListValidationRules operation middleware
func (siw *ServerInterfaceWrapper) ListValidationRules(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListValidationRules(c, objectId)
}

// CreateValidationRule operation middleware
func (siw *ServerInterfaceWrapper) CreateValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateValidationRule(c, objectId)
}

// DeleteValidationRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteValidationRule(c, objectId, ruleId)
}

// GetValidationRule operation middleware
func (siw *ServerInterfaceWrapper) GetValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetValidationRule(c, objectId, ruleId)
}

// UpdateValidationRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateValidationRule(c, objectId, ruleId)
}

// SetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) SetUserPassword(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetUserPassword(c, userId)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTemplates(c)
}

// ApplyTemplate operation middleware
func (siw *ServerInterfaceWrapper) ApplyTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId string

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyTemplate(c, templateId)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// ExecuteDML operation middleware
func (siw *ServerInterfaceWrapper) ExecuteDML(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteDML(c)
}

// ListDescribeObjects operation middleware
func (siw *ServerInterfaceWrapper) ListDescribeObjects(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDescribeObjects(c)
}

// DescribeObject operation middleware
func (siw *ServerInterfaceWrapper) DescribeObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DescribeObject(c, objectName)
}

// ExecuteQueryGet operation middleware
func (siw *ServerInterfaceWrapper) ExecuteQueryGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteQueryGetParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteQueryGet(c, params)
}

// ExecuteQueryPost operation middleware
func (siw *ServerInterfaceWrapper) ExecuteQueryPost(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteQueryPost(c)
}

// ListRecords operation middleware
func (siw *ServerInterfaceWrapper) ListRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRecords(c, objectName, params)
}

// CreateRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRecord(c, objectName)
}

// DeleteRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRecord(c, objectName, recordId)
}

// GetRecord operation middleware
func (siw *ServerInterfaceWrapper) GetRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecord(c, objectName, recordId)
}

// UpdateRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRecord(c, objectName, recordId)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/admin/cel/validate", wrapper.ValidateCelExpression)
	router.GET(options.BaseURL+"/api/v1/admin/functions", wrapper.ListFunctions)
	router.POST(options.BaseURL+"/api/v1/admin/functions", wrapper.CreateFunction)
	router.DELETE(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.DeleteFunction)
	router.GET(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.GetFunction)
	router.PUT(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.UpdateFunction)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.ListObjects)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.CreateObject)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.DeleteObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.GetObject)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.UpdateObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.ListFields)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.CreateField)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.DeleteField)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.GetField)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.UpdateField)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules", wrapper.ListValidationRules)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules", wrapper.CreateValidationRule)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.DeleteValidationRule)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.GetValidationRule)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.UpdateValidationRule)
	router.PUT(options.BaseURL+"/api/v1/admin/security/users/:userId/password", wrapper.SetUserPassword)
	router.GET(options.BaseURL+"/api/v1/admin/templates", wrapper.ListTemplates)
	router.POST(options.BaseURL+"/api/v1/admin/templates/:templateId/apply", wrapper.ApplyTemplate)
	router.POST(options.BaseURL+"/api/v1/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/api/v1/auth/reset-password", wrapper.ResetPassword)
	router.POST(options.BaseURL+"/api/v1/data", wrapper.ExecuteDML)
	router.GET(options.BaseURL+"/api/v1/describe", wrapper.ListDescribeObjects)
	router.GET(options.BaseURL+"/api/v1/describe/:objectName", wrapper.DescribeObject)
	router.GET(options.BaseURL+"/api/v1/query", wrapper.ExecuteQueryGet)
	router.POST(options.BaseURL+"/api/v1/query", wrapper.ExecuteQueryPost)
	router.GET(options.BaseURL+"/api/v1/records/:objectName", wrapper.ListRecords)
	router.POST(options.BaseURL+"/api/v1/records/:objectName", wrapper.CreateRecord)
	router.DELETE(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.DeleteRecord)
	router.GET(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.GetRecord)
	router.PUT(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.UpdateRecord)
	router.GET(options.BaseURL+"/healthz", wrapper.HealthCheck)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9aXPbOLJ/BcW3VZO8YkZKZmZrxlXvg9dxZv3KTry2s/Mh5aeCyZaEDa8AoBKNy//9",
	"FQ4eIAEekqjx1O6XxCJxNPpCo7vRfPSCNM7SBBLOvJNHL8MUx8CByl/vCEThRSj+JIl34mWYrz3fS3AM",
	"3om31G99j8KXnFAIvRNOc/A9FqwhxqLbMqUx5t6Jl+dEtOTbTHRlnJJk5T09+d67PAk4SRP3NFWD/Wb6",
	"8PAvCLhznrR4vd8s13gF5QxfcqDbaopMvKsPF8IS5xH3Tl77XkwSEuex/FsPSxIOK6BqXKCdQwNduId/",
	"M/e9GH/T48/nvbPd5BE4MUXVy33w9CQ6syxNGEhO+xsOb+BLDoyLX0GacEjknzjLIhJgwQCzf7E0Ec+q",
	"af5CYemdeP81q7h4pt6y2TmlKb3Rk6gpQ2ABJZkYzDvx/okjEsqREYi23pPvnaXJMiLBEaF4m6uhAaUU",
	"BcX0QjBS+kDCEJLjwXIqBQ0lKUcZ0JhwDqEA5SLhQBMcyQGOB04xLWJAN0ArKr1P+bs0T8LjgXIDLM1p",
	"ABI3Szn3k+99THDO1yklv8MRYTnN+RoSrkdHhRAK/iHJRjC1FGE9npjuDKJrodjfilkfvYymGVBOlOgp",
	"oX5simghs48WHVfJ/SfVXTe+LwVdKVMpURBpQYOSfUwAgjTK46Q2U6mIfC8iCdjfxMCY1ofdABYNe4Cr",
	"qZ8meAmHb/IFJEJjfvI2peZYCF3o+d7XNSQL+JZRYExQyS90r3zo+eUutnhIQ6G2N4SRBxIRvlUt7v02",
	"AWrj2eijlrHAGVk4aSj3c7kMwkH90cV7dUYpOcDDlOJtC6/Gagsk9SJZs3ULy1K2RwFqclULWgEsz2my",
	"cLCxr6hYe/OQphHgpLVQ1c66MgqYg7SSnOxTJ0+Mv11CsuLrahMufr+x0F/sBmTVhwo5/Zlq2tQVNRPA",
	"8ywzSBNuwfKHAkkFh2cRJoKumAIWGz0JxP4PMSaR53vZOk0E1+dU/CqEUswdkBiLZ0FOKSSB4PQMaCCU",
	"ou/hnKeLJI8fVGPMQf/HidIh6j9GkpUUqjiPOBH9GEsDIuVNslqcpYzoX1kabeOUZmsSWGVIrbC5PMmr",
	"vlfCUpDeACcjweeIMC4NnSWI9YB1jjVE2aLQEd0IJ2wR5IynsdF0iSMGfosPZfOKEwd2yBPyJYdhzSP8",
	"AJHkzIoTX1vALtcfLrTWUZLTY+b5HkspX6Q0BGoANLcanXWhK8WmANIgZYcwaj3rlEepf01Z/HH+y18t",
	"sDckqfV+gFS/FhqYCyvGO/H+7xN+9fu9+Gf+6pfF/X//xYawkQq7WK7U2gOUYCEAekKrCGiej3EmZC/Z",
	"WnjebgNI1LpJo85fgxQlfMNxFoG0ATcpCWCxCCRIo/TnKFW4xmyBA042pACoX3xEnzVhPKXbBac4+CzG",
	"GtwzSfmYidgaC1ilxcEGa4NAoh4/RKZGUOc1ew+pnxZS2tgCR1H6taF9OjqHEMG46aoeWrUM7SgPwGNm",
	"YoBpsG716NSlWTgSe9Kui2BBkgUDnmeD+pVquMX3nt+nmrU+bgs4TkJMQ7kXyw3HtnNlUU5xtHDPz/oB",
	"qCxZU8gySjZqiy+NivJJlj9EJFhQwKH5a/GVEtlCGJQ0jSIIFw/bRYapMCF6FZFl1zCWaKLLraoq18BN",
	"HsEUtp08HwJb8NTEmpJXXzGet8OuJA3pRZCGJsvWzyxLTCIILfrUMVjtqFXr8ZO9h3FmMQ+uZ+eXqHqP",
	"+BpzFOeMI7VJISEeaJlSJGFFIebYYUNJRQ3jZKsG+puffuplawYboC2mVi6IiqWL318xTUTH+71soPY5",
	"soXDD/IPHCGBzCBNQmkIS6yJvoivCUNii0Caw7wdZMY42pk8YJOZt1eXThFhHHOItVOk4fm6ukTla1Ra",
	"JDUd9P72/OYOXby/+4BOgyDNE45evMcx+OgiCXPG6fYl+ufp5cfzW/Tiu9Mghu989N0dBOskjdLV9ruX",
	"vYuvwHMujElqNdeltq3wImTthV28ZShdIt0EUQhSGgpClCadw9dSmW0kYUB7xi/a7DQBTb+y0+USAl5s",
	"7vUZ3kurUEwi2iFcNPQri58k/K8/ejYeVrqrE3TdZAfInyxkkh6Av2m7vum8Ce2H/8HuIzmC3+lFMj12",
	"dtfGIK+fXEPLzyK72+atn/wtDFrzP/WpYqE+wm2CYxIg3VEo4dyxA6mRberpN6mDUql8tuVQL/Supunu",
	"I2OXe9k1iYLCRsGCEx+tOwQFZTMUtlt7Y4jxt0WkNwCbgzFNtG1qmFXAF0keSRcHZgGWvEFBTB1wu4lF",
	"ISANH15tFgqR3JTZmmRuNx4LcOTwgzKOaRtN9WO1nW/ewpIkcvO4Ld3SbuvmML4pRfZwochWqhLBBK8K",
	"H9BYe+c/LqyDu7Da8jTM2WM4t6ynoyzCXAyziHGCVxA6G9a9XvbD3JZx0KdUZ6PKFdZhF7pOVAMXfSDX",
	"mHMbHSEsjY1DTlvB5Nssvbp01bnA4DqTInXMlnqgTZM6O9hpb6DAUA7G4u/dGkzA/gA7ay77hunecfp2",
	"jB5V36HE5Zym188EzghUOI5CDveKPm6Mk4E+5nQhycaChSFR8JxB9RqI9eXYiN5vCLb2ArFVKwvAOB66",
	"dKvdkMDhIk2i7ZS6aldCjHKaW8S4WpxNgE3xVGLjlMZLwrjbBpZn+cFObat9MogDdCyuD4wdZrfOltJV",
	"yq8xY19T6g4BKpujrsQLK6RbelQrK8a1298d3mirvQlsr4E73aGi039QsGPHrdhJNAW+Zf8ZFm5y5mlM",
	"GttxOkwv0xVxR9syLRtWwHMG1LGqBhBlS78a0QaMCjFVwjvWNJhARtpxpeFxpJ640cA4kWVPGm7PG+Gj",
	"cfGiAQGi4RGh/Y4TRqxoQHBoQDBocPRnh6PHYYI5B1BjzejO8SI5rgNLI5xjnl/q6HOdOWxU6uBjB0c2",
	"haPJIE1eb3Bhk+VaaqIu6Q79YJN2g17jjlSF6tzpTKWQNtbA01PZ3N+DNM8AXdIns25h6ZGm0YHHsfyi",
	"Ueom1QEN7ta2aSFJhlckwcU21zXaddnyCrjDclYzvsebCw7xSGYbxhw9Kv8PJXwFm5u8+x1i2hS1UaFB",
	"KYv1tnI4LMrrBta3POXYPPC4o0WyrRyLDerRwL++81C7/qAmNwe2ofkGlhTY2mm6UvV+wdPPkPQzgtnc",
	"PiGD/sNi3WKux+ff/GyErH+27NUDIVXNeizp2w//uOyAcQW35HczAC8zCMxo0JW6coKSKpyoAn4oA4o0",
	"vcp7KW/mfRdTfH3rpRV2EtAi+c4WR749vzw/u0MXoY/e4xjQu5sPV2VA+fLi6uIOvZ73nsbV1G5cOeLE",
	"aQLWMBlfA0U4ikqUrPEG0ANAotMhoGaT1xRXAt/4jerykUaWyF5OWUplRG8JPFiTZIX4GpDoJ1GOXkCc",
	"8S0iSySAe2l3aqu4bGv0f0gcU7lYW/QWhyohAUfXNTQYzjeXQ09LbMVX9XnvxCsLH7VR1Rn5up1SAFua",
	"qUO87iAWtimcZlm07Vf15lN37Nr3uB54YfUYt3Hy1AHcRbJMx/spKluwLb4ON3bfgYg5Q588Z/VzCd5g",
	"Eul9VuW/CM54iNLgM4T2Q4dz9Qe0rwyEDvJj3gkdfY2J5boMDgJgzLkt+WM3LmM8f8A+VsK2n4lSLdGK",
	"gY/SOO6+W3GICxJjQ6ED/P2Dwo596Wdj/P5q0Hs3Fo+XFP+nzF93Jq4r9PUkrv8pPYDP3bX3TD12PVLb",
	"PDuOSp0+nnPNelJ18//gbOh6SvOeicsHT0UeGzs/RN7w7lnCgzKDhxF5ZDLvRwbUbviVYUyLyUcZ73DY",
	"DA43dBOka46MpksSweCsndTZtjdnYHjYSo5Xi10VYd8avurrMlbRlw1R0Gk/I6ykttUGMwV/pJuuRx1M",
	"EWsbq0JGq4wDMfJhMs+m0jS7hIks2qlHjvZOVuvQawYn1BBlMGU7EUkTbVzcxJSRAx4aG8I36NjY3Kn3",
	"UQ3N+a2+AwZBLlArs2R0KRfAFOhprrLkHuSvdwUT/e9vd0WFGikV8m3FUGvOM1XygugtyHQDnSccaEYJ",
	"A3R2c4WK8B76SvgaxcCxWNirkJINJEj7DhBOQrSiOMkjTFEB8PcyWZdL/6AY6roY6vT6wvO9DVDFx978",
	"+9ffz6VwZpDgjHgn3g/fz7//QTpQ+VoueYYzMtu8nuEwJsksgGimb1sp1KfKWhIEwEWpo4JUcAbReZ2T",
	"qTKviusMBykpYilz8WQKoBDRZk2eN/P5NBAMKsmjfIwGk3knn0z2+nT/dO97LI9jTLc1nCKMzAsOgth4",
	"xeR9DmHqilFNohX1OeTKV2AhmBDtd2WrPXG1T3Zckfs1QCO0MSxWgdIlqtY7CsOyO44ipI6GtWEqDFfP",
	"7oVhZuV+87L+VGxvrQgwiPNfH4Caw4g4hGhFa31vRtYe+lFxnG2Sci2zWlkt2eWX/i5lBaxRfKFQjXCT",
	"Lxxs4Ra/2WNV7+2pumjX5qC38rnBQQYFf2zvHiUa9c08hZMf+3FS1puaFolqSYOR6Nv11K/A3ViZP0++",
	"DoFjErEdCDIGv78CbyMXPWzRxVu3+qoVRPxkB6tqMqsVMxRTZ7mFPqZLdiLVZ/f7TrDpH41FtBm+s+qb",
	"jKsUqndXfYXZOqvFupwGyAfdpsWYBy43eYwik/Y5zBy+apoxuZCCQJOZspbsqw47qyDqk+/9NIRtzVKL",
	"khFN40sNiMIytaduepVHoGLaPgvsQ5HOOJ39ZUZPJrC++onVRSjV4riW1QF4QRtcLW7oZoZe5TN7LMrg",
	"DjC+aszTZ3p9KOCsGV4/9GOgqoG6i6m2N5K1QTYSyW67zIWw+fH5PTSSPY+PWmGLjcbrOGOsrPfcY4pN",
	"qgNtEeQj+14G88S+JtbzF2htq02oNWdV+pPbi6SaTEjy9o3MLleQAucPIYiEQQJQt2hk9mJ506JFmSI1",
	"fk+N0OWY0jdgJ/RK1RObjmwUmZdkbYcuSZB9TaJpHSuHs6Ga7NfJcjvogtmj/lLCEH9WyXi9ziwN9Z/R",
	"oBqF8Q43lx1Z82MLynOwpUaidFe96fe7wPRXQfr8XxNqWEvq6JFNroGM829jcE2nYsscR6e1ZcaxJzW7",
	"OnIBOuyvTS3oKSGc1l8pp23Oabe4qlavFGQTmlyNdIMpbS97PuORjTBHqkZPUDyP4JnbZTtEDRvM2M2A",
	"47XD7FF9sGiA+WVhwj47rEmd3WOLO4QKR2HObUj1LXv+x3P9EUKDI5E5nQmlP77VY0EdRWF2JYAf2aba",
	"XWE+99DhfvqvmG2WM8E8j+I/ofvq9xhtwULzm26q117fdHOx6y3wjwxocfFyIk61XO0czqAm/xTj7M04",
	"r/u7GJ8Qm5bbboEjQWZUcAZ6ITnoZY3hBDA2JiuulXab2ndlqwn1gPV+Zod5XYG+Q6ZbcZ8U1eCtjVgh",
	"rnrWhb3ZY/GnkFBZJHmYeFbdOkXUJpJWm1veOy4weQxqmRedLeQqGuq69SFiubyYusyjaPu8HYpDWUri",
	"AOHEykwDeCnn69lSlhx8ZSh3K4XN2oQTKV17AcRd9e7FUlYqkLdkEHwjjDMfYUSBAUcRST6jNWaqRAIT",
	"oO+ilg3vhH5aKUQ5Vbc6FESI0hVJ3KiXJfEmwrhRbu/IFlj74nf/1ykrKT7eLmrQuAYPyO1vEHlTZcg4",
	"6Sve707g0YVmLGlyfWS3HFUv09UKQiRg3x2xg/dPiST0gsIm/QxILxLJRb7sp4G6VOY6sF5Nume1rtZZ",
	"2PxMVodXBtURsCnOp0FtSiTvx/RiUWPdzcq6CNJdWfzh8BqrUWfpOeos2ahg0cIO30/t6FUjVV0DFdU1",
	"eunFYMjmbpSSmoxubIIjVbmDq632AFu4MA7KDVxeBOtHdllXx4rd828Q5BzeXl1OhNraB5OOLA7VF41s",
	"nyK/uiyvXR0pIrV3gEnTChkfk6rRPowb173CWoVL50G2qE1ZpVv/Ube9zEKJe135KktqVEnJ4w/EUp2R",
	"2iAycpTgDVnhRmSvxLQV/4Wb/j2O4clJDJMQx7/P0qiKOgjfZYZl+VCppZ3zrMYFBhSoRY5bfWYrafwB",
	"3oeKUuO8DzWyl4X7rGTWUiyry/0qT2ANoA5W7u+3v5/fnKvn/4PUN+Pk93/aFxG+jPW0TKa0a/UFLexW",
	"L8n359PbNVK++PX8rn4yYOmXqOMCQ51nrlM2VQJvvRDmkTfrfxe6X3+4tRG+pj10ucdhe4ZyDBelKceF",
	"6a7xCoaE6K6Bqqb305oGe9XTPGTJ5jb/6T4QokgbGEU90CPkrxT1P4XxgZN25koByrT7W3dGi+LBPdTS",
	"COIf6077gK9SDakx2uYmhay9c1smzojb6Uo8LfigzZw9Km72qJ4Oyl2psVufI1Aj+5jJwzvdg+/AnDuZ",
	"xYWHQ+jlMRI5nOnl6Me4+q7Q17rxfhRl6VsHK/h7ksQDlV7x3NTw3CmPzzwdeKdL8T3Kbw044uvfnbbc",
	"3+X7szUEnw8r0bXa0eXBMf085ENebTG+BbohASDCkFrPtmH0qlWgQC+jtHPl5/YEJiRq6cZ+2r1MAxyh",
	"EDYQpZl2b+U00uWyTmazSDRYp4yf/Dz/eS5tUj1F6+AsZ9RQysJYIcGrJGWcBKySSg2YkNnO4J4YoPCA",
	"F94fPYT0ubYHaN0+RerLPHpZunPrDl57oObNi+5xStdLhycB5MnEWIQ8iLQ7mR+ut/QLY1u3U0vU3wp2",
	"LWPF70s3tfVvZY21hzlrFEGxDVMrEeX3fD+8mrHqHkDkPd0//X8AAAD//+cUtUZilgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
