// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateFieldRequestFieldSubtype.
const (
	CreateFieldRequestFieldSubtypeArea        CreateFieldRequestFieldSubtype = "area"
	CreateFieldRequestFieldSubtypeAssociation CreateFieldRequestFieldSubtype = "association"
	CreateFieldRequestFieldSubtypeAutoNumber  CreateFieldRequestFieldSubtype = "auto_number"
	CreateFieldRequestFieldSubtypeComposition CreateFieldRequestFieldSubtype = "composition"
	CreateFieldRequestFieldSubtypeCurrency    CreateFieldRequestFieldSubtype = "currency"
	CreateFieldRequestFieldSubtypeDate        CreateFieldRequestFieldSubtype = "date"
	CreateFieldRequestFieldSubtypeDatetime    CreateFieldRequestFieldSubtype = "datetime"
	CreateFieldRequestFieldSubtypeDecimal     CreateFieldRequestFieldSubtype = "decimal"
	CreateFieldRequestFieldSubtypeEmail       CreateFieldRequestFieldSubtype = "email"
	CreateFieldRequestFieldSubtypeInteger     CreateFieldRequestFieldSubtype = "integer"
	CreateFieldRequestFieldSubtypeMulti       CreateFieldRequestFieldSubtype = "multi"
	CreateFieldRequestFieldSubtypePercent     CreateFieldRequestFieldSubtype = "percent"
	CreateFieldRequestFieldSubtypePhone       CreateFieldRequestFieldSubtype = "phone"
	CreateFieldRequestFieldSubtypePlain       CreateFieldRequestFieldSubtype = "plain"
	CreateFieldRequestFieldSubtypePolymorphic CreateFieldRequestFieldSubtype = "polymorphic"
	CreateFieldRequestFieldSubtypeRich        CreateFieldRequestFieldSubtype = "rich"
	CreateFieldRequestFieldSubtypeSingle      CreateFieldRequestFieldSubtype = "single"
	CreateFieldRequestFieldSubtypeTime        CreateFieldRequestFieldSubtype = "time"
	CreateFieldRequestFieldSubtypeUrl         CreateFieldRequestFieldSubtype = "url"
)

// Defines values for CreateFieldRequestFieldType.
const (
	CreateFieldRequestFieldTypeBoolean   CreateFieldRequestFieldType = "boolean"
	CreateFieldRequestFieldTypeDatetime  CreateFieldRequestFieldType = "datetime"
	CreateFieldRequestFieldTypeNumber    CreateFieldRequestFieldType = "number"
	CreateFieldRequestFieldTypePicklist  CreateFieldRequestFieldType = "picklist"
	CreateFieldRequestFieldTypeReference CreateFieldRequestFieldType = "reference"
	CreateFieldRequestFieldTypeText      CreateFieldRequestFieldType = "text"
)

// Defines values for CreateObjectRequestObjectType.
const (
	CreateObjectRequestObjectTypeCustom   CreateObjectRequestObjectType = "custom"
	CreateObjectRequestObjectTypeStandard CreateObjectRequestObjectType = "standard"
)

// Defines values for FieldConfigOnDelete.
const (
	Cascade  FieldConfigOnDelete = "cascade"
	Restrict FieldConfigOnDelete = "restrict"
	SetNull  FieldConfigOnDelete = "set_null"
)

// Defines values for ObjectDefinitionObjectType.
const (
	ObjectDefinitionObjectTypeCustom   ObjectDefinitionObjectType = "custom"
	ObjectDefinitionObjectTypeStandard ObjectDefinitionObjectType = "standard"
)

// Defines values for ListObjectsParamsObjectType.
const (
	Custom   ListObjectsParamsObjectType = "custom"
	Standard ListObjectsParamsObjectType = "standard"
)

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	ApiName            string                          `json:"api_name"`
	Config             *FieldConfig                    `json:"config,omitempty"`
	Description        *string                         `json:"description,omitempty"`
	FieldSubtype       *CreateFieldRequestFieldSubtype `json:"field_subtype,omitempty"`
	FieldType          CreateFieldRequestFieldType     `json:"field_type"`
	HelpText           *string                         `json:"help_text,omitempty"`
	IsCustom           *bool                           `json:"is_custom,omitempty"`
	IsRequired         *bool                           `json:"is_required,omitempty"`
	IsUnique           *bool                           `json:"is_unique,omitempty"`
	Label              string                          `json:"label"`
	ReferencedObjectId *openapi_types.UUID             `json:"referenced_object_id,omitempty"`
	SortOrder          *int                            `json:"sort_order,omitempty"`
}

// CreateFieldRequestFieldSubtype defines model for CreateFieldRequest.FieldSubtype.
type CreateFieldRequestFieldSubtype string

// CreateFieldRequestFieldType defines model for CreateFieldRequest.FieldType.
type CreateFieldRequestFieldType string

// CreateObjectRequest defines model for CreateObjectRequest.
type CreateObjectRequest struct {
	ApiName               string                        `json:"api_name"`
	Description           *string                       `json:"description,omitempty"`
	HasActivities         *bool                         `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                         `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                         `json:"has_notes,omitempty"`
	HasSharingRules       *bool                         `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool                         `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                         `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                         `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                         `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool                         `json:"is_queryable,omitempty"`
	IsSearchable          *bool                         `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                         `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                         `json:"is_visible_in_setup,omitempty"`
	Label                 string                        `json:"label"`
	ObjectType            CreateObjectRequestObjectType `json:"object_type"`
	PluralLabel           string                        `json:"plural_label"`
}

// CreateObjectRequestObjectType defines model for CreateObjectRequest.ObjectType.
type CreateObjectRequestObjectType string

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// FieldConfig defines model for FieldConfig.
type FieldConfig struct {
	DefaultValue     *string              `json:"default_value,omitempty"`
	Format           *string              `json:"format,omitempty"`
	IsReparentable   *bool                `json:"is_reparentable,omitempty"`
	MaxLength        *int                 `json:"max_length,omitempty"`
	OnDelete         *FieldConfigOnDelete `json:"on_delete,omitempty"`
	Precision        *int                 `json:"precision,omitempty"`
	RelationshipName *string              `json:"relationship_name,omitempty"`
	Scale            *int                 `json:"scale,omitempty"`
	StartValue       *int                 `json:"start_value,omitempty"`
}

// FieldConfigOnDelete defines model for FieldConfig.OnDelete.
type FieldConfigOnDelete string

// FieldDefinitionSchema defines model for FieldDefinitionSchema.
type FieldDefinitionSchema struct {
	ApiName            *string             `json:"api_name,omitempty"`
	Config             *FieldConfig        `json:"config,omitempty"`
	CreatedAt          *time.Time          `json:"created_at,omitempty"`
	Description        *string             `json:"description,omitempty"`
	FieldSubtype       *string             `json:"field_subtype,omitempty"`
	FieldType          *string             `json:"field_type,omitempty"`
	HelpText           *string             `json:"help_text,omitempty"`
	Id                 *openapi_types.UUID `json:"id,omitempty"`
	IsCustom           *bool               `json:"is_custom,omitempty"`
	IsPlatformManaged  *bool               `json:"is_platform_managed,omitempty"`
	IsRequired         *bool               `json:"is_required,omitempty"`
	IsSystemField      *bool               `json:"is_system_field,omitempty"`
	IsUnique           *bool               `json:"is_unique,omitempty"`
	Label              *string             `json:"label,omitempty"`
	ObjectId           *openapi_types.UUID `json:"object_id,omitempty"`
	ReferencedObjectId *openapi_types.UUID `json:"referenced_object_id,omitempty"`
	SortOrder          *int                `json:"sort_order,omitempty"`
	UpdatedAt          *time.Time          `json:"updated_at,omitempty"`
}

// FieldListResponse defines model for FieldListResponse.
type FieldListResponse struct {
	Data *[]FieldDefinitionSchema `json:"data,omitempty"`
}

// FieldResponse defines model for FieldResponse.
type FieldResponse struct {
	Data *FieldDefinitionSchema `json:"data,omitempty"`
}

// ObjectDefinition defines model for ObjectDefinition.
type ObjectDefinition struct {
	ApiName               *string                     `json:"api_name,omitempty"`
	CreatedAt             *time.Time                  `json:"created_at,omitempty"`
	Description           *string                     `json:"description,omitempty"`
	HasActivities         *bool                       `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                       `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                       `json:"has_notes,omitempty"`
	HasSharingRules       *bool                       `json:"has_sharing_rules,omitempty"`
	Id                    *openapi_types.UUID         `json:"id,omitempty"`
	IsCreateable          *bool                       `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                       `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                       `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                       `json:"is_deleteable_object,omitempty"`
	IsPlatformManaged     *bool                       `json:"is_platform_managed,omitempty"`
	IsQueryable           *bool                       `json:"is_queryable,omitempty"`
	IsSearchable          *bool                       `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                       `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                       `json:"is_visible_in_setup,omitempty"`
	Label                 *string                     `json:"label,omitempty"`
	ObjectType            *ObjectDefinitionObjectType `json:"object_type,omitempty"`
	PluralLabel           *string                     `json:"plural_label,omitempty"`
	UpdatedAt             *time.Time                  `json:"updated_at,omitempty"`
}

// ObjectDefinitionObjectType defines model for ObjectDefinition.ObjectType.
type ObjectDefinitionObjectType string

// ObjectListResponse defines model for ObjectListResponse.
type ObjectListResponse struct {
	Data       *[]ObjectDefinition `json:"data,omitempty"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

// ObjectResponse defines model for ObjectResponse.
type ObjectResponse struct {
	Data *ObjectDefinition `json:"data,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       *int   `json:"page,omitempty"`
	PerPage    *int   `json:"per_page,omitempty"`
	Total      *int64 `json:"total,omitempty"`
	TotalPages *int64 `json:"total_pages,omitempty"`
}

// UpdateFieldRequest defines model for UpdateFieldRequest.
type UpdateFieldRequest struct {
	Config      *FieldConfig `json:"config,omitempty"`
	Description *string      `json:"description,omitempty"`
	HelpText    *string      `json:"help_text,omitempty"`
	IsRequired  *bool        `json:"is_required,omitempty"`
	IsUnique    *bool        `json:"is_unique,omitempty"`
	Label       string       `json:"label"`
	SortOrder   *int         `json:"sort_order,omitempty"`
}

// UpdateObjectRequest defines model for UpdateObjectRequest.
type UpdateObjectRequest struct {
	Description           *string `json:"description,omitempty"`
	HasActivities         *bool   `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool   `json:"has_history_tracking,omitempty"`
	HasNotes              *bool   `json:"has_notes,omitempty"`
	HasSharingRules       *bool   `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool   `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool   `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool   `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool   `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool   `json:"is_queryable,omitempty"`
	IsSearchable          *bool   `json:"is_searchable,omitempty"`
	IsUpdateable          *bool   `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool   `json:"is_visible_in_setup,omitempty"`
	Label                 string  `json:"label"`
	PluralLabel           string  `json:"plural_label"`
}

// FieldId defines model for FieldId.
type FieldId = openapi_types.UUID

// ObjectId defines model for ObjectId.
type ObjectId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListObjectsParams defines parameters for ListObjects.
type ListObjectsParams struct {
	Page       *int                         `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int                         `form:"per_page,omitempty" json:"per_page,omitempty"`
	ObjectType *ListObjectsParamsObjectType `form:"object_type,omitempty" json:"object_type,omitempty"`
}

// ListObjectsParamsObjectType defines parameters for ListObjects.
type ListObjectsParamsObjectType string

// CreateObjectJSONRequestBody defines body for CreateObject for application/json ContentType.
type CreateObjectJSONRequestBody = CreateObjectRequest

// UpdateObjectJSONRequestBody defines body for UpdateObject for application/json ContentType.
type UpdateObjectJSONRequestBody = UpdateObjectRequest

// CreateFieldJSONRequestBody defines body for CreateField for application/json ContentType.
type CreateFieldJSONRequestBody = CreateFieldRequest

// UpdateFieldJSONRequestBody defines body for UpdateField for application/json ContentType.
type UpdateFieldJSONRequestBody = UpdateFieldRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List object definitions
	// (GET /api/v1/admin/metadata/objects)
	ListObjects(c *gin.Context, params ListObjectsParams)
	// Create object definition
	// (POST /api/v1/admin/metadata/objects)
	CreateObject(c *gin.Context)
	// Delete object definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId})
	DeleteObject(c *gin.Context, objectId ObjectId)
	// Get object definition
	// (GET /api/v1/admin/metadata/objects/{objectId})
	GetObject(c *gin.Context, objectId ObjectId)
	// Update object definition
	// (PUT /api/v1/admin/metadata/objects/{objectId})
	UpdateObject(c *gin.Context, objectId ObjectId)
	// List field definitions for object
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields)
	ListFields(c *gin.Context, objectId ObjectId)
	// Create field definition
	// (POST /api/v1/admin/metadata/objects/{objectId}/fields)
	CreateField(c *gin.Context, objectId ObjectId)
	// Delete field definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	DeleteField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Get field definition
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	GetField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Update field definition
	// (PUT /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	UpdateField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Health check
	// (GET /healthz)
	HealthCheck(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "object_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "object_type", c.Request.URL.Query(), &params.ObjectType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter object_type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjects(c, params)
}

// CreateObject operation middleware
func (siw *ServerInterfaceWrapper) CreateObject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateObject(c)
}

// DeleteObject operation middleware
func (siw *ServerInterfaceWrapper) DeleteObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteObject(c, objectId)
}

// GetObject operation middleware
func (siw *ServerInterfaceWrapper) GetObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetObject(c, objectId)
}

// UpdateObject operation middleware
func (siw *ServerInterfaceWrapper) UpdateObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateObject(c, objectId)
}

// ListFields operation middleware
func (siw *ServerInterfaceWrapper) ListFields(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFields(c, objectId)
}

// CreateField operation middleware
func (siw *ServerInterfaceWrapper) CreateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateField(c, objectId)
}

// DeleteField operation middleware
func (siw *ServerInterfaceWrapper) DeleteField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteField(c, objectId, fieldId)
}

// GetField operation middleware
func (siw *ServerInterfaceWrapper) GetField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetField(c, objectId, fieldId)
}

// UpdateField operation middleware
func (siw *ServerInterfaceWrapper) UpdateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateField(c, objectId, fieldId)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.ListObjects)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.CreateObject)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.DeleteObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.GetObject)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.UpdateObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.ListFields)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.CreateField)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.DeleteField)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.GetField)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.UpdateField)
	router.GET(options.BaseURL+"/healthz", wrapper.HealthCheck)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RaX3PbuBH/Khy0jzxLTtLOVW93zvmambsmk0z7kvFw1uBKxAUEEADURfXou3cA8I8o",
	"kiJpy0oyfbJk7j8sdn/7I6AHQmWupEBhDVk9EAUacrSo/bdbhjx9k7qPTJAVUWAzEhMBOZIVWZdPY6Lx",
	"c8E0pmRldYExMTTDHJzaWuocLFmRomBO0u6UUzVWM7Eh+31M3t7/gdQOOpHV46d42Ttlo6Qw6Nf1M6Tv",
	"8XOBxrpvVAqLwn8EpTijYJkUiz+MFO5/jZu/alyTFfnLosnZIjw1i1+0lvp96SS4TNFQzZQzRlbkP8BZ",
	"6i1H6GTJPiY3Uqw5oxeM4nURTGMkdUQr9/uY3Ep9z9IUxeVi+Yn6bAhpI4U6Z9Zi6kJ5IyxqAdwbuFw4",
	"ldvIoN6ibnbpX9LeykKklwvlPRpZaIo+N2vv2wmV+s78jUaw6PvzoJKVlgq1ZaHKQbEkdNEDyeHLbyg2",
	"NiOr6+UyJjkT1fcXnX6J3TLXbDO2Du/+Joger+GBpLiGgruuJD0ePHgkprgPTx4IiiInq49EcWCCxAQ0",
	"gmt6Rh0aYA6Mk5ioTAokMSm0+8aExQ1q4nxTloP7Hy20RkF3Thg1dZsVEyisTESR3wdhsFj+sSx3H8s/",
	"hokNdx/yglvm9IyRlPk9dqZdCgwrvynJd7nUKmOU3A2u8Hh5Fr+4gOpY7qXkCKIdjmL0E2fGetBbo1sP",
	"9vrIkKvEmxxNODMJLYyVeUt0DdxgLV0FE8QbvJ2oUAj2ucBp4hzukfvKbCrxuifsev1pEkZBwtIJkB8T",
	"I7VNpE5RtwJa1qJV8YTpUC31Y9M2VZCtrWx2IYTjYdw3Yxhkk7oRv0CuOHrQ2UpGMUmoq7p5TTqr3zIw",
	"CVDLtqwKaHyPnE7GjJV6l1gN9JOzNVlTSDvHkcnAxZrogk9VcyXtUw/3vF12gSD0a/gmSPyWmgQ4l38e",
	"lfgJ5RQ5znPXaJT1O1Xxc4F6N8eTQdA062icbFiVzszelhnm1sJEYtAWapJe3euduifxWP+XTX8Mo8aC",
	"SEGnHvA9qvXBo+KFBp4M+zdjAYxjQ8tHO94+rPCz/2eZ7roIQWXq19hZRo7GwKbv2VF43kIjP+i/5h6d",
	"GLDiXKP8xa/hOICg3uf3kCt0vJYVlGyBF/0pqOD+oXewaVSgUdiqkrslmMOXhJe7/NCZADGRouzUVpGh",
	"TUTBPasAQ8EnV6NzTW1/wWmkzJSA3PWikXsuYTKm6mHQnVwUWss4MGAs6G6aDidZf+Jf45oJT1w+1Ax1",
	"eDydhw4GaE6TsG31vHaI80NFu0ZG2jhrHGFdpwlTt5SmUYsWleqFScXBOjNJDgI2Yb6Mcqx+VN8Zi+W4",
	"GhRqiNcJ8B2C1omLPhMR69Z0GEJz6mSwzH9jxg5jWwrWFz6zmJtJxdxpm8YzaA27E6GMh/EI733eAu1s",
	"ZOe29jN0aZdrTueWI1xyInfs6ZLprd2ilPM45ATSOJ0lPg1ZWvxxAmGcQBAnM8JHoNB5CF5H4DzgEnrs",
	"jOjSadoOsMREwYYJqJrslLV3teTvaE/CxNNQqRt1n6ejaDqeVJvKHkwChToZfmqlBd7aRSbs31+ReEjW",
	"2zKTNPrW8W9fOqeP2M5xTjaXo0wgDZP4wMiL1+mxfcT7g9G7wSyOnI18lwPlW58U3+gAGCm7Y0Sf83be",
	"+0reLUqnxsRadiqP/CIsaqWZwejm/e9RNWujP5nNohwtOJT8IdVsiyIK5kwEIo02GkTBQUcGaaGZ3V35",
	"Q2XrzxqcqXeVqZ/evSEx2aIOb4lkeXV9tfRzUKEAxciKvLxaXr10ywCb+eJbgGKL7fUC0pyJRRXHogzA",
	"SWzQ14HrKY+8b1KyIm5evS1l4tbN3sfyqs2XSHPX5rH38F6tPtm59sckLHez+boPPgcMVoDea/TF0r+X",
	"l1bLA8/ZPg75w6GbOURif3d0QfhiuTzbbU8Peei58nHPI7muqspVxN9CEH2262AX7csyf0tU5DnoXW3T",
	"G4zSemq7YrCwcWVA6pqu3N65FpSmp5oOD7nLy1g0tjrJOkum+s7R9+0mt7rAfWezrs+8Wac2KkhE5XuT",
	"26dXU/bp4MrZq/xjXOXm4Hr2ybUQctuthtPFsI9HwGfxUF3Q70NvV2do7eJ57f9/UDyt7XvVReK3VZxO",
	"r8zyy/EMNLfYXuPVuEZ9uXuOJIdlzk1y3A/fv6IdStjy8vWett5VLp/aX9HOz+vRzOvz3ogs6l+iuHGg",
	"ip4tOSSzz4SBfXx5EgZ+hZooX64fjYHffkOH3XhO1FyEV4OTJO42iDzjlndPT09QlDLir7IhPgYfwCGj",
	"idZSl5vUtzNlwE9FhBO0yOfvWVlR6xziwqSofaDdUxle4MmUaGYtfTUOdVx+J0vuEViweCh/WTmBUjWF",
	"N8aobsuov0dCNSvjw3RqIFnLSzfKt8ClZqb0sbgZj8pWvzEeIV3PibA9J70XplwTC+f/hnDNhtgMgdvs",
	"v4M06p/++U2G9NNTAaB9dG0s2MK0f1wkP025Vupu8gfUW0YxYiYK69kdZSesIqLlMqqUhN8IuEw4af/r",
	"5dCmR/xNUuBRilvkUuXhh7GF5mRFMmvVarHgTiCTxq5+XP649B1Zujg29cF7LKP0J6Apg42QxjJqmrO5",
	"MjCHAiMvlVG4ziyjKtU71Lpr6BhQT9upmOvd/n8BAAD//3BCyvT4MAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
