// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CelValidateRequestContext.
const (
	CelValidateRequestContextDefaultExpr    CelValidateRequestContext = "default_expr"
	CelValidateRequestContextFunctionBody   CelValidateRequestContext = "function_body"
	CelValidateRequestContextValidationRule CelValidateRequestContext = "validation_rule"
	CelValidateRequestContextVisibilityExpr CelValidateRequestContext = "visibility_expr"
	CelValidateRequestContextWhenExpression CelValidateRequestContext = "when_expression"
)

// Defines values for CreateFieldRequestFieldSubtype.
const (
	CreateFieldRequestFieldSubtypeArea        CreateFieldRequestFieldSubtype = "area"
	CreateFieldRequestFieldSubtypeAssociation CreateFieldRequestFieldSubtype = "association"
	CreateFieldRequestFieldSubtypeAutoNumber  CreateFieldRequestFieldSubtype = "auto_number"
	CreateFieldRequestFieldSubtypeComposition CreateFieldRequestFieldSubtype = "composition"
	CreateFieldRequestFieldSubtypeCurrency    CreateFieldRequestFieldSubtype = "currency"
	CreateFieldRequestFieldSubtypeDate        CreateFieldRequestFieldSubtype = "date"
	CreateFieldRequestFieldSubtypeDatetime    CreateFieldRequestFieldSubtype = "datetime"
	CreateFieldRequestFieldSubtypeDecimal     CreateFieldRequestFieldSubtype = "decimal"
	CreateFieldRequestFieldSubtypeEmail       CreateFieldRequestFieldSubtype = "email"
	CreateFieldRequestFieldSubtypeInteger     CreateFieldRequestFieldSubtype = "integer"
	CreateFieldRequestFieldSubtypeMulti       CreateFieldRequestFieldSubtype = "multi"
	CreateFieldRequestFieldSubtypePercent     CreateFieldRequestFieldSubtype = "percent"
	CreateFieldRequestFieldSubtypePhone       CreateFieldRequestFieldSubtype = "phone"
	CreateFieldRequestFieldSubtypePlain       CreateFieldRequestFieldSubtype = "plain"
	CreateFieldRequestFieldSubtypePolymorphic CreateFieldRequestFieldSubtype = "polymorphic"
	CreateFieldRequestFieldSubtypeRich        CreateFieldRequestFieldSubtype = "rich"
	CreateFieldRequestFieldSubtypeSingle      CreateFieldRequestFieldSubtype = "single"
	CreateFieldRequestFieldSubtypeTime        CreateFieldRequestFieldSubtype = "time"
	CreateFieldRequestFieldSubtypeUrl         CreateFieldRequestFieldSubtype = "url"
)

// Defines values for CreateFieldRequestFieldType.
const (
	CreateFieldRequestFieldTypeBoolean   CreateFieldRequestFieldType = "boolean"
	CreateFieldRequestFieldTypeDatetime  CreateFieldRequestFieldType = "datetime"
	CreateFieldRequestFieldTypeNumber    CreateFieldRequestFieldType = "number"
	CreateFieldRequestFieldTypePicklist  CreateFieldRequestFieldType = "picklist"
	CreateFieldRequestFieldTypeReference CreateFieldRequestFieldType = "reference"
	CreateFieldRequestFieldTypeText      CreateFieldRequestFieldType = "text"
)

// Defines values for CreateFunctionRequestReturnType.
const (
	CreateFunctionRequestReturnTypeAny     CreateFunctionRequestReturnType = "any"
	CreateFunctionRequestReturnTypeBoolean CreateFunctionRequestReturnType = "boolean"
	CreateFunctionRequestReturnTypeList    CreateFunctionRequestReturnType = "list"
	CreateFunctionRequestReturnTypeMap     CreateFunctionRequestReturnType = "map"
	CreateFunctionRequestReturnTypeNumber  CreateFunctionRequestReturnType = "number"
	CreateFunctionRequestReturnTypeString  CreateFunctionRequestReturnType = "string"
)

// Defines values for CreateObjectRequestObjectType.
const (
	CreateObjectRequestObjectTypeCustom   CreateObjectRequestObjectType = "custom"
	CreateObjectRequestObjectTypeStandard CreateObjectRequestObjectType = "standard"
)

// Defines values for CreateObjectRequestVisibility.
const (
	CreateObjectRequestVisibilityControlledByParent CreateObjectRequestVisibility = "controlled_by_parent"
	CreateObjectRequestVisibilityPrivate            CreateObjectRequestVisibility = "private"
	CreateObjectRequestVisibilityPublicRead         CreateObjectRequestVisibility = "public_read"
	CreateObjectRequestVisibilityPublicReadWrite    CreateObjectRequestVisibility = "public_read_write"
)

// Defines values for CreateValidationRuleRequestSeverity.
const (
	CreateValidationRuleRequestSeverityError   CreateValidationRuleRequestSeverity = "error"
	CreateValidationRuleRequestSeverityWarning CreateValidationRuleRequestSeverity = "warning"
)

// Defines values for FieldConfigOnDelete.
const (
	Cascade  FieldConfigOnDelete = "cascade"
	Restrict FieldConfigOnDelete = "restrict"
	SetNull  FieldConfigOnDelete = "set_null"
)

// Defines values for FieldDefinitionSchemaFieldSubtype.
const (
	Area        FieldDefinitionSchemaFieldSubtype = "area"
	Association FieldDefinitionSchemaFieldSubtype = "association"
	AutoNumber  FieldDefinitionSchemaFieldSubtype = "auto_number"
	Composition FieldDefinitionSchemaFieldSubtype = "composition"
	Currency    FieldDefinitionSchemaFieldSubtype = "currency"
	Date        FieldDefinitionSchemaFieldSubtype = "date"
	Datetime    FieldDefinitionSchemaFieldSubtype = "datetime"
	Decimal     FieldDefinitionSchemaFieldSubtype = "decimal"
	Email       FieldDefinitionSchemaFieldSubtype = "email"
	Integer     FieldDefinitionSchemaFieldSubtype = "integer"
	Multi       FieldDefinitionSchemaFieldSubtype = "multi"
	Percent     FieldDefinitionSchemaFieldSubtype = "percent"
	Phone       FieldDefinitionSchemaFieldSubtype = "phone"
	Plain       FieldDefinitionSchemaFieldSubtype = "plain"
	Polymorphic FieldDefinitionSchemaFieldSubtype = "polymorphic"
	Rich        FieldDefinitionSchemaFieldSubtype = "rich"
	Single      FieldDefinitionSchemaFieldSubtype = "single"
	Time        FieldDefinitionSchemaFieldSubtype = "time"
	Url         FieldDefinitionSchemaFieldSubtype = "url"
)

// Defines values for FieldDefinitionSchemaFieldType.
const (
	FieldDefinitionSchemaFieldTypeBoolean   FieldDefinitionSchemaFieldType = "boolean"
	FieldDefinitionSchemaFieldTypeDatetime  FieldDefinitionSchemaFieldType = "datetime"
	FieldDefinitionSchemaFieldTypeNumber    FieldDefinitionSchemaFieldType = "number"
	FieldDefinitionSchemaFieldTypePicklist  FieldDefinitionSchemaFieldType = "picklist"
	FieldDefinitionSchemaFieldTypeReference FieldDefinitionSchemaFieldType = "reference"
	FieldDefinitionSchemaFieldTypeText      FieldDefinitionSchemaFieldType = "text"
)

// Defines values for FunctionReturnType.
const (
	FunctionReturnTypeAny     FunctionReturnType = "any"
	FunctionReturnTypeBoolean FunctionReturnType = "boolean"
	FunctionReturnTypeList    FunctionReturnType = "list"
	FunctionReturnTypeMap     FunctionReturnType = "map"
	FunctionReturnTypeNumber  FunctionReturnType = "number"
	FunctionReturnTypeString  FunctionReturnType = "string"
)

// Defines values for FunctionParamType.
const (
	FunctionParamTypeAny     FunctionParamType = "any"
	FunctionParamTypeBoolean FunctionParamType = "boolean"
	FunctionParamTypeList    FunctionParamType = "list"
	FunctionParamTypeMap     FunctionParamType = "map"
	FunctionParamTypeNumber  FunctionParamType = "number"
	FunctionParamTypeString  FunctionParamType = "string"
)

// Defines values for OVDefaultOn.
const (
	Create       OVDefaultOn = "create"
	Createupdate OVDefaultOn = "create,update"
	Update       OVDefaultOn = "update"
)

// Defines values for OVReadComputedType.
const (
	OVReadComputedTypeBool      OVReadComputedType = "bool"
	OVReadComputedTypeFloat     OVReadComputedType = "float"
	OVReadComputedTypeInt       OVReadComputedType = "int"
	OVReadComputedTypeString    OVReadComputedType = "string"
	OVReadComputedTypeTimestamp OVReadComputedType = "timestamp"
)

// Defines values for OVValidationSeverity.
const (
	OVValidationSeverityError   OVValidationSeverity = "error"
	OVValidationSeverityWarning OVValidationSeverity = "warning"
)

// Defines values for ObjectDefinitionObjectType.
const (
	ObjectDefinitionObjectTypeCustom   ObjectDefinitionObjectType = "custom"
	ObjectDefinitionObjectTypeStandard ObjectDefinitionObjectType = "standard"
)

// Defines values for ObjectDefinitionVisibility.
const (
	ObjectDefinitionVisibilityControlledByParent ObjectDefinitionVisibility = "controlled_by_parent"
	ObjectDefinitionVisibilityPrivate            ObjectDefinitionVisibility = "private"
	ObjectDefinitionVisibilityPublicRead         ObjectDefinitionVisibility = "public_read"
	ObjectDefinitionVisibilityPublicReadWrite    ObjectDefinitionVisibility = "public_read_write"
)

// Defines values for TemplateInfoStatus.
const (
	Applied   TemplateInfoStatus = "applied"
	Available TemplateInfoStatus = "available"
	Blocked   TemplateInfoStatus = "blocked"
)

// Defines values for UpdateFunctionRequestReturnType.
const (
	UpdateFunctionRequestReturnTypeAny     UpdateFunctionRequestReturnType = "any"
	UpdateFunctionRequestReturnTypeBoolean UpdateFunctionRequestReturnType = "boolean"
	UpdateFunctionRequestReturnTypeList    UpdateFunctionRequestReturnType = "list"
	UpdateFunctionRequestReturnTypeMap     UpdateFunctionRequestReturnType = "map"
	UpdateFunctionRequestReturnTypeNumber  UpdateFunctionRequestReturnType = "number"
	UpdateFunctionRequestReturnTypeString  UpdateFunctionRequestReturnType = "string"
)

// Defines values for UpdateObjectRequestVisibility.
const (
	ControlledByParent UpdateObjectRequestVisibility = "controlled_by_parent"
	Private            UpdateObjectRequestVisibility = "private"
	PublicRead         UpdateObjectRequestVisibility = "public_read"
	PublicReadWrite    UpdateObjectRequestVisibility = "public_read_write"
)

// Defines values for UpdateValidationRuleRequestSeverity.
const (
	UpdateValidationRuleRequestSeverityError   UpdateValidationRuleRequestSeverity = "error"
	UpdateValidationRuleRequestSeverityWarning UpdateValidationRuleRequestSeverity = "warning"
)

// Defines values for ValidationRuleSeverity.
const (
	ValidationRuleSeverityError   ValidationRuleSeverity = "error"
	ValidationRuleSeverityWarning ValidationRuleSeverity = "warning"
)

// Defines values for ListObjectsParamsObjectType.
const (
	Custom   ListObjectsParamsObjectType = "custom"
	Standard ListObjectsParamsObjectType = "standard"
)

// CelParamDef defines model for CelParamDef.
type CelParamDef struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// CelValidateError defines model for CelValidateError.
type CelValidateError struct {
	Column  *int   `json:"column,omitempty"`
	Line    *int   `json:"line,omitempty"`
	Message string `json:"message"`
}

// CelValidateRequest defines model for CelValidateRequest.
type CelValidateRequest struct {
	Context       CelValidateRequestContext `json:"context"`
	Expression    string                    `json:"expression"`
	ObjectApiName *string                   `json:"object_api_name,omitempty"`
	Params        *[]CelParamDef            `json:"params,omitempty"`
}

// CelValidateRequestContext defines model for CelValidateRequest.Context.
type CelValidateRequestContext string

// CelValidateResponse defines model for CelValidateResponse.
type CelValidateResponse struct {
	Errors     *[]CelValidateError `json:"errors,omitempty"`
	ReturnType *string             `json:"return_type,omitempty"`
	Valid      bool                `json:"valid"`
}

// CreateFieldRequest defines model for CreateFieldRequest.
type CreateFieldRequest struct {
	ApiName            string                          `json:"api_name"`
	Config             *FieldConfig                    `json:"config,omitempty"`
	Description        *string                         `json:"description,omitempty"`
	FieldSubtype       *CreateFieldRequestFieldSubtype `json:"field_subtype,omitempty"`
	FieldType          CreateFieldRequestFieldType     `json:"field_type"`
	HelpText           *string                         `json:"help_text,omitempty"`
	IsCustom           *bool                           `json:"is_custom,omitempty"`
	IsRequired         *bool                           `json:"is_required,omitempty"`
	IsUnique           *bool                           `json:"is_unique,omitempty"`
	Label              string                          `json:"label"`
	ReferencedObjectId *openapi_types.UUID             `json:"referenced_object_id,omitempty"`
	SortOrder          *int                            `json:"sort_order,omitempty"`
}

// CreateFieldRequestFieldSubtype defines model for CreateFieldRequest.FieldSubtype.
type CreateFieldRequestFieldSubtype string

// CreateFieldRequestFieldType defines model for CreateFieldRequest.FieldType.
type CreateFieldRequestFieldType string

// CreateFunctionRequest defines model for CreateFunctionRequest.
type CreateFunctionRequest struct {
	Body        string                           `json:"body"`
	Description *string                          `json:"description,omitempty"`
	Name        string                           `json:"name"`
	Params      *[]FunctionParam                 `json:"params,omitempty"`
	ReturnType  *CreateFunctionRequestReturnType `json:"return_type,omitempty"`
}

// CreateFunctionRequestReturnType defines model for CreateFunctionRequest.ReturnType.
type CreateFunctionRequestReturnType string

// CreateObjectRequest defines model for CreateObjectRequest.
type CreateObjectRequest struct {
	ApiName               string                         `json:"api_name"`
	Description           *string                        `json:"description,omitempty"`
	HasActivities         *bool                          `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                          `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                          `json:"has_notes,omitempty"`
	HasSharingRules       *bool                          `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool                          `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                          `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                          `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                          `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool                          `json:"is_queryable,omitempty"`
	IsSearchable          *bool                          `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                          `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                          `json:"is_visible_in_setup,omitempty"`
	Label                 string                         `json:"label"`
	ObjectType            CreateObjectRequestObjectType  `json:"object_type"`
	PluralLabel           string                         `json:"plural_label"`
	Visibility            *CreateObjectRequestVisibility `json:"visibility,omitempty"`
}

// CreateObjectRequestObjectType defines model for CreateObjectRequest.ObjectType.
type CreateObjectRequestObjectType string

// CreateObjectRequestVisibility defines model for CreateObjectRequest.Visibility.
type CreateObjectRequestVisibility string

// CreateObjectViewRequest defines model for CreateObjectViewRequest.
type CreateObjectViewRequest struct {
	ApiName     string              `json:"api_name"`
	Config      *ObjectViewConfig   `json:"config,omitempty"`
	Description *string             `json:"description,omitempty"`
	IsDefault   *bool               `json:"is_default,omitempty"`
	Label       string              `json:"label"`
	ObjectId    openapi_types.UUID  `json:"object_id"`
	ProfileId   *openapi_types.UUID `json:"profile_id"`
}

// CreateValidationRuleRequest defines model for CreateValidationRuleRequest.
type CreateValidationRuleRequest struct {
	ApiName      string  `json:"api_name"`
	AppliesTo    *string `json:"applies_to,omitempty"`
	Description  *string `json:"description,omitempty"`
	ErrorCode    *string `json:"error_code,omitempty"`
	ErrorMessage string  `json:"error_message"`

	// Expression CEL expression that must return true for valid data
	Expression string                               `json:"expression"`
	IsActive   *bool                                `json:"is_active,omitempty"`
	Label      string                               `json:"label"`
	Severity   *CreateValidationRuleRequestSeverity `json:"severity,omitempty"`
	SortOrder  *int                                 `json:"sort_order,omitempty"`

	// WhenExpression Optional CEL condition for when this rule applies
	WhenExpression *string `json:"when_expression,omitempty"`
}

// CreateValidationRuleRequestSeverity defines model for CreateValidationRuleRequest.Severity.
type CreateValidationRuleRequestSeverity string

// DMLRequest defines model for DMLRequest.
type DMLRequest struct {
	// Statement DML statement string
	Statement string `json:"statement"`
}

// DMLResult defines model for DMLResult.
type DMLResult struct {
	// DeletedIds IDs of deleted records
	DeletedIds *[]string `json:"deletedIds,omitempty"`

	// InsertedIds IDs of inserted records
	InsertedIds *[]string `json:"insertedIds,omitempty"`

	// RowsAffected Number of rows affected
	RowsAffected *int64 `json:"rowsAffected,omitempty"`

	// UpdatedIds IDs of updated records
	UpdatedIds *[]string `json:"updatedIds,omitempty"`
}

// ErrorBody defines model for ErrorBody.
type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// FieldConfig defines model for FieldConfig.
type FieldConfig struct {
	// DefaultExpr CEL expression for dynamic default value
	DefaultExpr *string `json:"default_expr,omitempty"`

	// DefaultOn When to apply default (create, update, create,update)
	DefaultOn        *string              `json:"default_on,omitempty"`
	DefaultValue     *string              `json:"default_value,omitempty"`
	Format           *string              `json:"format,omitempty"`
	IsReparentable   *bool                `json:"is_reparentable,omitempty"`
	MaxLength        *int                 `json:"max_length,omitempty"`
	OnDelete         *FieldConfigOnDelete `json:"on_delete,omitempty"`
	Precision        *int                 `json:"precision,omitempty"`
	RelationshipName *string              `json:"relationship_name,omitempty"`
	Scale            *int                 `json:"scale,omitempty"`
	StartValue       *int                 `json:"start_value,omitempty"`
}

// FieldConfigOnDelete defines model for FieldConfig.OnDelete.
type FieldConfigOnDelete string

// FieldDefinitionSchema defines model for FieldDefinitionSchema.
type FieldDefinitionSchema struct {
	ApiName            string                             `json:"api_name"`
	Config             FieldConfig                        `json:"config"`
	CreatedAt          time.Time                          `json:"created_at"`
	Description        string                             `json:"description"`
	FieldSubtype       *FieldDefinitionSchemaFieldSubtype `json:"field_subtype,omitempty"`
	FieldType          FieldDefinitionSchemaFieldType     `json:"field_type"`
	HelpText           string                             `json:"help_text"`
	Id                 openapi_types.UUID                 `json:"id"`
	IsCustom           bool                               `json:"is_custom"`
	IsPlatformManaged  bool                               `json:"is_platform_managed"`
	IsRequired         bool                               `json:"is_required"`
	IsSystemField      bool                               `json:"is_system_field"`
	IsUnique           bool                               `json:"is_unique"`
	Label              string                             `json:"label"`
	ObjectId           openapi_types.UUID                 `json:"object_id"`
	ReferencedObjectId *openapi_types.UUID                `json:"referenced_object_id,omitempty"`
	SortOrder          int                                `json:"sort_order"`
	UpdatedAt          time.Time                          `json:"updated_at"`
}

// FieldDefinitionSchemaFieldSubtype defines model for FieldDefinitionSchema.FieldSubtype.
type FieldDefinitionSchemaFieldSubtype string

// FieldDefinitionSchemaFieldType defines model for FieldDefinitionSchema.FieldType.
type FieldDefinitionSchemaFieldType string

// FieldDescribe defines model for FieldDescribe.
type FieldDescribe struct {
	ApiName string `json:"api_name"`
	Config  struct {
		DefaultValue *string `json:"default_value,omitempty"`
		MaxLength    *int    `json:"max_length,omitempty"`
		Precision    *int    `json:"precision,omitempty"`
		Scale        *int    `json:"scale,omitempty"`
		Values       *[]struct {
			Id        string `json:"id"`
			IsActive  bool   `json:"is_active"`
			IsDefault bool   `json:"is_default"`
			Label     string `json:"label"`
			SortOrder int    `json:"sort_order"`
			Value     string `json:"value"`
		} `json:"values,omitempty"`
	} `json:"config"`
	FieldSubtype  *string `json:"field_subtype"`
	FieldType     string  `json:"field_type"`
	IsReadOnly    bool    `json:"is_read_only"`
	IsRequired    bool    `json:"is_required"`
	IsSystemField bool    `json:"is_system_field"`
	Label         string  `json:"label"`
	SortOrder     int     `json:"sort_order"`
}

// FieldListResponse defines model for FieldListResponse.
type FieldListResponse struct {
	Data *[]FieldDefinitionSchema `json:"data,omitempty"`
}

// FieldResponse defines model for FieldResponse.
type FieldResponse struct {
	Data *FieldDefinitionSchema `json:"data,omitempty"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// FormAction defines model for FormAction.
type FormAction struct {
	Icon           *string `json:"icon,omitempty"`
	Key            *string `json:"key,omitempty"`
	Label          *string `json:"label,omitempty"`
	Type           *string `json:"type,omitempty"`
	VisibilityExpr *string `json:"visibility_expr,omitempty"`
}

// FormDescribe defines model for FormDescribe.
type FormDescribe struct {
	Actions         *[]FormAction      `json:"actions,omitempty"`
	HighlightFields *[]string          `json:"highlight_fields,omitempty"`
	ListDefaultSort *string            `json:"list_default_sort,omitempty"`
	ListFields      *[]string          `json:"list_fields,omitempty"`
	RelatedLists    *[]FormRelatedList `json:"related_lists,omitempty"`
	Sections        *[]FormSection     `json:"sections,omitempty"`
}

// FormRelatedList defines model for FormRelatedList.
type FormRelatedList struct {
	Fields *[]string `json:"fields,omitempty"`
	Label  *string   `json:"label,omitempty"`
	Limit  *int      `json:"limit,omitempty"`
	Object *string   `json:"object,omitempty"`
	Sort   *string   `json:"sort,omitempty"`
}

// FormSection defines model for FormSection.
type FormSection struct {
	Collapsed *bool     `json:"collapsed,omitempty"`
	Columns   *int      `json:"columns,omitempty"`
	Fields    *[]string `json:"fields,omitempty"`
	Key       *string   `json:"key,omitempty"`
	Label     *string   `json:"label,omitempty"`
}

// Function defines model for Function.
type Function struct {
	Body        *string             `json:"body,omitempty"`
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	Params      *[]FunctionParam    `json:"params,omitempty"`
	ReturnType  *FunctionReturnType `json:"return_type,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
}

// FunctionReturnType defines model for Function.ReturnType.
type FunctionReturnType string

// FunctionParam defines model for FunctionParam.
type FunctionParam struct {
	Description *string           `json:"description,omitempty"`
	Name        string            `json:"name"`
	Type        FunctionParamType `json:"type"`
}

// FunctionParamType defines model for FunctionParam.Type.
type FunctionParamType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// OVAction defines model for OVAction.
type OVAction struct {
	Icon           string `json:"icon"`
	Key            string `json:"key"`
	Label          string `json:"label"`
	Type           string `json:"type"`
	VisibilityExpr string `json:"visibility_expr"`
}

// OVComputed defines model for OVComputed.
type OVComputed struct {
	Expr  string `json:"expr"`
	Field string `json:"field"`
}

// OVDefault defines model for OVDefault.
type OVDefault struct {
	Expr  string      `json:"expr"`
	Field string      `json:"field"`
	On    OVDefaultOn `json:"on"`
	When  *string     `json:"when,omitempty"`
}

// OVDefaultOn defines model for OVDefault.On.
type OVDefaultOn string

// OVMutSync defines model for OVMutSync.
type OVMutSync struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// OVMutation defines model for OVMutation.
type OVMutation struct {
	Dml     string     `json:"dml"`
	Foreach *string    `json:"foreach,omitempty"`
	Sync    *OVMutSync `json:"sync,omitempty"`
	When    *string    `json:"when,omitempty"`
}

// OVQuery defines model for OVQuery.
type OVQuery struct {
	Name string  `json:"name"`
	Soql string  `json:"soql"`
	When *string `json:"when,omitempty"`
}

// OVReadComputed defines model for OVReadComputed.
type OVReadComputed struct {
	Expr string             `json:"expr"`
	Name string             `json:"name"`
	Type OVReadComputedType `json:"type"`
	When *string            `json:"when,omitempty"`
}

// OVReadComputedType defines model for OVReadComputed.Type.
type OVReadComputedType string

// OVReadConfig defines model for OVReadConfig.
type OVReadConfig struct {
	Actions  *[]OVAction       `json:"actions,omitempty"`
	Computed *[]OVReadComputed `json:"computed,omitempty"`
	Fields   *[]string         `json:"fields,omitempty"`
	Queries  *[]OVQuery        `json:"queries,omitempty"`
}

// OVValidation defines model for OVValidation.
type OVValidation struct {
	Code     *string              `json:"code,omitempty"`
	Expr     string               `json:"expr"`
	Message  string               `json:"message"`
	Severity OVValidationSeverity `json:"severity"`
	When     *string              `json:"when,omitempty"`
}

// OVValidationSeverity defines model for OVValidation.Severity.
type OVValidationSeverity string

// OVWriteConfig defines model for OVWriteConfig.
type OVWriteConfig struct {
	Computed   *[]OVComputed   `json:"computed,omitempty"`
	Defaults   *[]OVDefault    `json:"defaults,omitempty"`
	Fields     *[]string       `json:"fields,omitempty"`
	Mutations  *[]OVMutation   `json:"mutations,omitempty"`
	Validation *[]OVValidation `json:"validation,omitempty"`
}

// ObjectDefinition defines model for ObjectDefinition.
type ObjectDefinition struct {
	ApiName               string                     `json:"api_name"`
	CreatedAt             time.Time                  `json:"created_at"`
	Description           string                     `json:"description"`
	HasActivities         bool                       `json:"has_activities"`
	HasHistoryTracking    bool                       `json:"has_history_tracking"`
	HasNotes              bool                       `json:"has_notes"`
	HasSharingRules       bool                       `json:"has_sharing_rules"`
	Id                    openapi_types.UUID         `json:"id"`
	IsCreateable          bool                       `json:"is_createable"`
	IsCustomFieldsAllowed bool                       `json:"is_custom_fields_allowed"`
	IsDeleteable          bool                       `json:"is_deleteable"`
	IsDeleteableObject    bool                       `json:"is_deleteable_object"`
	IsPlatformManaged     bool                       `json:"is_platform_managed"`
	IsQueryable           bool                       `json:"is_queryable"`
	IsSearchable          bool                       `json:"is_searchable"`
	IsUpdateable          bool                       `json:"is_updateable"`
	IsVisibleInSetup      bool                       `json:"is_visible_in_setup"`
	Label                 string                     `json:"label"`
	ObjectType            ObjectDefinitionObjectType `json:"object_type"`
	PluralLabel           string                     `json:"plural_label"`
	UpdatedAt             time.Time                  `json:"updated_at"`
	Visibility            ObjectDefinitionVisibility `json:"visibility"`
}

// ObjectDefinitionObjectType defines model for ObjectDefinition.ObjectType.
type ObjectDefinitionObjectType string

// ObjectDefinitionVisibility defines model for ObjectDefinition.Visibility.
type ObjectDefinitionVisibility string

// ObjectDescribe defines model for ObjectDescribe.
type ObjectDescribe struct {
	ApiName      string          `json:"api_name"`
	Fields       []FieldDescribe `json:"fields"`
	Form         *FormDescribe   `json:"form,omitempty"`
	IsCreateable bool            `json:"is_createable"`
	IsDeleteable bool            `json:"is_deleteable"`
	IsUpdateable bool            `json:"is_updateable"`
	Label        string          `json:"label"`
	PluralLabel  string          `json:"plural_label"`
}

// ObjectListResponse defines model for ObjectListResponse.
type ObjectListResponse struct {
	Data       *[]ObjectDefinition `json:"data,omitempty"`
	Pagination *PaginationMeta     `json:"pagination,omitempty"`
}

// ObjectNavItem defines model for ObjectNavItem.
type ObjectNavItem struct {
	ApiName      string `json:"api_name"`
	IsCreateable bool   `json:"is_createable"`
	IsQueryable  bool   `json:"is_queryable"`
	Label        string `json:"label"`
	PluralLabel  string `json:"plural_label"`
}

// ObjectResponse defines model for ObjectResponse.
type ObjectResponse struct {
	Data *ObjectDefinition `json:"data,omitempty"`
}

// ObjectView defines model for ObjectView.
type ObjectView struct {
	ApiName     string              `json:"api_name"`
	Config      ObjectViewConfig    `json:"config"`
	CreatedAt   time.Time           `json:"created_at"`
	Description string              `json:"description"`
	Id          openapi_types.UUID  `json:"id"`
	IsDefault   bool                `json:"is_default"`
	Label       string              `json:"label"`
	ObjectId    openapi_types.UUID  `json:"object_id"`
	ProfileId   *openapi_types.UUID `json:"profile_id"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// ObjectViewConfig defines model for ObjectViewConfig.
type ObjectViewConfig struct {
	Read  OVReadConfig   `json:"read"`
	Write *OVWriteConfig `json:"write,omitempty"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Page       int   `json:"page"`
	PerPage    int   `json:"per_page"`
	Total      int64 `json:"total"`
	TotalPages int64 `json:"total_pages"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// SOQLRequest defines model for SOQLRequest.
type SOQLRequest struct {
	// PageSize Maximum number of records per page
	PageSize *int `json:"pageSize,omitempty"`

	// Query SOQL query string
	Query string `json:"query"`
}

// SOQLResult defines model for SOQLResult.
type SOQLResult struct {
	// Done Whether all records have been returned
	Done *bool `json:"done,omitempty"`

	// NextRecordsUrl Cursor for fetching the next page (empty if done)
	NextRecordsUrl *string `json:"nextRecordsUrl,omitempty"`

	// Records Query result records
	Records *[]map[string]interface{} `json:"records,omitempty"`

	// TotalSize Total number of records returned
	TotalSize *int `json:"totalSize,omitempty"`
}

// SetPasswordRequest defines model for SetPasswordRequest.
type SetPasswordRequest struct {
	Password string `json:"password"`
}

// TemplateApplyResponse defines model for TemplateApplyResponse.
type TemplateApplyResponse struct {
	Data *struct {
		Message    *string `json:"message,omitempty"`
		TemplateId *string `json:"template_id,omitempty"`
	} `json:"data,omitempty"`
}

// TemplateInfo defines model for TemplateInfo.
type TemplateInfo struct {
	Description *string             `json:"description,omitempty"`
	Fields      *int                `json:"fields,omitempty"`
	Id          *string             `json:"id,omitempty"`
	Label       *string             `json:"label,omitempty"`
	Objects     *int                `json:"objects,omitempty"`
	Status      *TemplateInfoStatus `json:"status,omitempty"`
}

// TemplateInfoStatus defines model for TemplateInfo.Status.
type TemplateInfoStatus string

// TemplateListResponse defines model for TemplateListResponse.
type TemplateListResponse struct {
	Data *[]TemplateInfo `json:"data,omitempty"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// TokenPairResponse defines model for TokenPairResponse.
type TokenPairResponse struct {
	Data *TokenPair `json:"data,omitempty"`
}

// UpdateFieldRequest defines model for UpdateFieldRequest.
type UpdateFieldRequest struct {
	Config      *FieldConfig `json:"config,omitempty"`
	Description *string      `json:"description,omitempty"`
	HelpText    *string      `json:"help_text,omitempty"`
	IsRequired  *bool        `json:"is_required,omitempty"`
	IsUnique    *bool        `json:"is_unique,omitempty"`
	Label       string       `json:"label"`
	SortOrder   *int         `json:"sort_order,omitempty"`
}

// UpdateFunctionRequest defines model for UpdateFunctionRequest.
type UpdateFunctionRequest struct {
	Body        string                           `json:"body"`
	Description *string                          `json:"description,omitempty"`
	Params      *[]FunctionParam                 `json:"params,omitempty"`
	ReturnType  *UpdateFunctionRequestReturnType `json:"return_type,omitempty"`
}

// UpdateFunctionRequestReturnType defines model for UpdateFunctionRequest.ReturnType.
type UpdateFunctionRequestReturnType string

// UpdateObjectRequest defines model for UpdateObjectRequest.
type UpdateObjectRequest struct {
	Description           *string                        `json:"description,omitempty"`
	HasActivities         *bool                          `json:"has_activities,omitempty"`
	HasHistoryTracking    *bool                          `json:"has_history_tracking,omitempty"`
	HasNotes              *bool                          `json:"has_notes,omitempty"`
	HasSharingRules       *bool                          `json:"has_sharing_rules,omitempty"`
	IsCreateable          *bool                          `json:"is_createable,omitempty"`
	IsCustomFieldsAllowed *bool                          `json:"is_custom_fields_allowed,omitempty"`
	IsDeleteable          *bool                          `json:"is_deleteable,omitempty"`
	IsDeleteableObject    *bool                          `json:"is_deleteable_object,omitempty"`
	IsQueryable           *bool                          `json:"is_queryable,omitempty"`
	IsSearchable          *bool                          `json:"is_searchable,omitempty"`
	IsUpdateable          *bool                          `json:"is_updateable,omitempty"`
	IsVisibleInSetup      *bool                          `json:"is_visible_in_setup,omitempty"`
	Label                 string                         `json:"label"`
	PluralLabel           string                         `json:"plural_label"`
	Visibility            *UpdateObjectRequestVisibility `json:"visibility,omitempty"`
}

// UpdateObjectRequestVisibility defines model for UpdateObjectRequest.Visibility.
type UpdateObjectRequestVisibility string

// UpdateObjectViewRequest defines model for UpdateObjectViewRequest.
type UpdateObjectViewRequest struct {
	Config      *ObjectViewConfig `json:"config,omitempty"`
	Description *string           `json:"description,omitempty"`
	IsDefault   *bool             `json:"is_default,omitempty"`
	Label       string            `json:"label"`
}

// UpdateValidationRuleRequest defines model for UpdateValidationRuleRequest.
type UpdateValidationRuleRequest struct {
	AppliesTo      *string                              `json:"applies_to,omitempty"`
	Description    *string                              `json:"description,omitempty"`
	ErrorCode      *string                              `json:"error_code,omitempty"`
	ErrorMessage   string                               `json:"error_message"`
	Expression     string                               `json:"expression"`
	IsActive       *bool                                `json:"is_active,omitempty"`
	Label          string                               `json:"label"`
	Severity       *UpdateValidationRuleRequestSeverity `json:"severity,omitempty"`
	SortOrder      *int                                 `json:"sort_order,omitempty"`
	WhenExpression *string                              `json:"when_expression,omitempty"`
}

// UpdateValidationRuleRequestSeverity defines model for UpdateValidationRuleRequest.Severity.
type UpdateValidationRuleRequestSeverity string

// UserInfo defines model for UserInfo.
type UserInfo struct {
	Email     string              `json:"email"`
	FirstName string              `json:"first_name"`
	Id        openapi_types.UUID  `json:"id"`
	IsActive  bool                `json:"is_active"`
	LastName  string              `json:"last_name"`
	ProfileId openapi_types.UUID  `json:"profile_id"`
	RoleId    *openapi_types.UUID `json:"role_id"`
	Username  string              `json:"username"`
}

// UserInfoResponse defines model for UserInfoResponse.
type UserInfoResponse struct {
	Data *UserInfo `json:"data,omitempty"`
}

// ValidationRule defines model for ValidationRule.
type ValidationRule struct {
	ApiName        string                 `json:"api_name"`
	AppliesTo      string                 `json:"applies_to"`
	CreatedAt      time.Time              `json:"created_at"`
	Description    string                 `json:"description"`
	ErrorCode      string                 `json:"error_code"`
	ErrorMessage   string                 `json:"error_message"`
	Expression     string                 `json:"expression"`
	Id             openapi_types.UUID     `json:"id"`
	IsActive       bool                   `json:"is_active"`
	Label          string                 `json:"label"`
	ObjectId       openapi_types.UUID     `json:"object_id"`
	Severity       ValidationRuleSeverity `json:"severity"`
	SortOrder      int                    `json:"sort_order"`
	UpdatedAt      time.Time              `json:"updated_at"`
	WhenExpression *string                `json:"when_expression"`
}

// ValidationRuleSeverity defines model for ValidationRule.Severity.
type ValidationRuleSeverity string

// ValidationRuleListResponse defines model for ValidationRuleListResponse.
type ValidationRuleListResponse struct {
	Data *[]ValidationRule `json:"data,omitempty"`
}

// ValidationRuleResponse defines model for ValidationRuleResponse.
type ValidationRuleResponse struct {
	Data *ValidationRule `json:"data,omitempty"`
}

// FieldId defines model for FieldId.
type FieldId = openapi_types.UUID

// FunctionId defines model for FunctionId.
type FunctionId = openapi_types.UUID

// ObjectId defines model for ObjectId.
type ObjectId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// RuleId defines model for RuleId.
type RuleId = openapi_types.UUID

// ViewId defines model for ViewId.
type ViewId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// ListObjectsParams defines parameters for ListObjects.
type ListObjectsParams struct {
	Page       *int                         `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *int                         `form:"per_page,omitempty" json:"per_page,omitempty"`
	ObjectType *ListObjectsParamsObjectType `form:"object_type,omitempty" json:"object_type,omitempty"`
}

// ListObjectsParamsObjectType defines parameters for ListObjects.
type ListObjectsParamsObjectType string

// ListObjectViewsParams defines parameters for ListObjectViews.
type ListObjectViewsParams struct {
	// ObjectId Filter by object ID
	ObjectId *openapi_types.UUID `form:"object_id,omitempty" json:"object_id,omitempty"`
}

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// ExecuteQueryGetParams defines parameters for ExecuteQueryGet.
type ExecuteQueryGetParams struct {
	// Q SOQL query string
	Q string `form:"q" json:"q"`
}

// ListRecordsParams defines parameters for ListRecords.
type ListRecordsParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// CreateRecordJSONBody defines parameters for CreateRecord.
type CreateRecordJSONBody map[string]interface{}

// UpdateRecordJSONBody defines parameters for UpdateRecord.
type UpdateRecordJSONBody map[string]interface{}

// ValidateCelExpressionJSONRequestBody defines body for ValidateCelExpression for application/json ContentType.
type ValidateCelExpressionJSONRequestBody = CelValidateRequest

// CreateFunctionJSONRequestBody defines body for CreateFunction for application/json ContentType.
type CreateFunctionJSONRequestBody = CreateFunctionRequest

// UpdateFunctionJSONRequestBody defines body for UpdateFunction for application/json ContentType.
type UpdateFunctionJSONRequestBody = UpdateFunctionRequest

// CreateObjectJSONRequestBody defines body for CreateObject for application/json ContentType.
type CreateObjectJSONRequestBody = CreateObjectRequest

// UpdateObjectJSONRequestBody defines body for UpdateObject for application/json ContentType.
type UpdateObjectJSONRequestBody = UpdateObjectRequest

// CreateFieldJSONRequestBody defines body for CreateField for application/json ContentType.
type CreateFieldJSONRequestBody = CreateFieldRequest

// UpdateFieldJSONRequestBody defines body for UpdateField for application/json ContentType.
type UpdateFieldJSONRequestBody = UpdateFieldRequest

// CreateValidationRuleJSONRequestBody defines body for CreateValidationRule for application/json ContentType.
type CreateValidationRuleJSONRequestBody = CreateValidationRuleRequest

// UpdateValidationRuleJSONRequestBody defines body for UpdateValidationRule for application/json ContentType.
type UpdateValidationRuleJSONRequestBody = UpdateValidationRuleRequest

// CreateObjectViewJSONRequestBody defines body for CreateObjectView for application/json ContentType.
type CreateObjectViewJSONRequestBody = CreateObjectViewRequest

// UpdateObjectViewJSONRequestBody defines body for UpdateObjectView for application/json ContentType.
type UpdateObjectViewJSONRequestBody = UpdateObjectViewRequest

// SetUserPasswordJSONRequestBody defines body for SetUserPassword for application/json ContentType.
type SetUserPasswordJSONRequestBody = SetPasswordRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody LogoutJSONBody

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ExecuteDMLJSONRequestBody defines body for ExecuteDML for application/json ContentType.
type ExecuteDMLJSONRequestBody = DMLRequest

// ExecuteQueryPostJSONRequestBody defines body for ExecuteQueryPost for application/json ContentType.
type ExecuteQueryPostJSONRequestBody = SOQLRequest

// CreateRecordJSONRequestBody defines body for CreateRecord for application/json ContentType.
type CreateRecordJSONRequestBody CreateRecordJSONBody

// UpdateRecordJSONRequestBody defines body for UpdateRecord for application/json ContentType.
type UpdateRecordJSONRequestBody UpdateRecordJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Validate a CEL expression
	// (POST /api/v1/admin/cel/validate)
	ValidateCelExpression(c *gin.Context)
	// List all custom functions
	// (GET /api/v1/admin/functions)
	ListFunctions(c *gin.Context)
	// Create a custom function
	// (POST /api/v1/admin/functions)
	CreateFunction(c *gin.Context)
	// Delete a custom function
	// (DELETE /api/v1/admin/functions/{functionId})
	DeleteFunction(c *gin.Context, functionId FunctionId)
	// Get a custom function by ID
	// (GET /api/v1/admin/functions/{functionId})
	GetFunction(c *gin.Context, functionId FunctionId)
	// Update a custom function
	// (PUT /api/v1/admin/functions/{functionId})
	UpdateFunction(c *gin.Context, functionId FunctionId)
	// List object definitions
	// (GET /api/v1/admin/metadata/objects)
	ListObjects(c *gin.Context, params ListObjectsParams)
	// Create object definition
	// (POST /api/v1/admin/metadata/objects)
	CreateObject(c *gin.Context)
	// Delete object definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId})
	DeleteObject(c *gin.Context, objectId ObjectId)
	// Get object definition
	// (GET /api/v1/admin/metadata/objects/{objectId})
	GetObject(c *gin.Context, objectId ObjectId)
	// Update object definition
	// (PUT /api/v1/admin/metadata/objects/{objectId})
	UpdateObject(c *gin.Context, objectId ObjectId)
	// List field definitions for object
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields)
	ListFields(c *gin.Context, objectId ObjectId)
	// Create field definition
	// (POST /api/v1/admin/metadata/objects/{objectId}/fields)
	CreateField(c *gin.Context, objectId ObjectId)
	// Delete field definition
	// (DELETE /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	DeleteField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Get field definition
	// (GET /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	GetField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// Update field definition
	// (PUT /api/v1/admin/metadata/objects/{objectId}/fields/{fieldId})
	UpdateField(c *gin.Context, objectId ObjectId, fieldId FieldId)
	// List validation rules for object
	// (GET /api/v1/admin/metadata/objects/{objectId}/rules)
	ListValidationRules(c *gin.Context, objectId ObjectId)
	// Create validation rule
	// (POST /api/v1/admin/metadata/objects/{objectId}/rules)
	CreateValidationRule(c *gin.Context, objectId ObjectId)
	// Delete validation rule
	// (DELETE /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	DeleteValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// Get validation rule
	// (GET /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	GetValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// Update validation rule
	// (PUT /api/v1/admin/metadata/objects/{objectId}/rules/{ruleId})
	UpdateValidationRule(c *gin.Context, objectId ObjectId, ruleId RuleId)
	// List object views
	// (GET /api/v1/admin/object-views)
	ListObjectViews(c *gin.Context, params ListObjectViewsParams)
	// Create an object view
	// (POST /api/v1/admin/object-views)
	CreateObjectView(c *gin.Context)
	// Delete an object view
	// (DELETE /api/v1/admin/object-views/{viewId})
	DeleteObjectView(c *gin.Context, viewId ViewId)
	// Get an object view by ID
	// (GET /api/v1/admin/object-views/{viewId})
	GetObjectView(c *gin.Context, viewId ViewId)
	// Update an object view
	// (PUT /api/v1/admin/object-views/{viewId})
	UpdateObjectView(c *gin.Context, viewId ViewId)
	// Set user password (admin)
	// (PUT /api/v1/admin/security/users/{userId}/password)
	SetUserPassword(c *gin.Context, userId openapi_types.UUID)
	// List available application templates
	// (GET /api/v1/admin/templates)
	ListTemplates(c *gin.Context)
	// Apply an application template
	// (POST /api/v1/admin/templates/{templateId}/apply)
	ApplyTemplate(c *gin.Context, templateId string)
	// Request password reset
	// (POST /api/v1/auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Authenticate user
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// Logout (revoke refresh token)
	// (POST /api/v1/auth/logout)
	Logout(c *gin.Context)
	// Get current user info
	// (GET /api/v1/auth/me)
	GetMe(c *gin.Context)
	// Refresh access token
	// (POST /api/v1/auth/refresh)
	RefreshToken(c *gin.Context)
	// Reset password with token
	// (POST /api/v1/auth/reset-password)
	ResetPassword(c *gin.Context)
	// Execute DML statement
	// (POST /api/v1/data)
	ExecuteDML(c *gin.Context)
	// List accessible objects for navigation
	// (GET /api/v1/describe)
	ListDescribeObjects(c *gin.Context)
	// Describe object with fields
	// (GET /api/v1/describe/{objectName})
	DescribeObject(c *gin.Context, objectName string)
	// Execute SOQL query (GET)
	// (GET /api/v1/query)
	ExecuteQueryGet(c *gin.Context, params ExecuteQueryGetParams)
	// Execute SOQL query (POST)
	// (POST /api/v1/query)
	ExecuteQueryPost(c *gin.Context)
	// List records for an object
	// (GET /api/v1/records/{objectName})
	ListRecords(c *gin.Context, objectName string, params ListRecordsParams)
	// Create a record
	// (POST /api/v1/records/{objectName})
	CreateRecord(c *gin.Context, objectName string)
	// Delete a record
	// (DELETE /api/v1/records/{objectName}/{recordId})
	DeleteRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Get a record by ID
	// (GET /api/v1/records/{objectName}/{recordId})
	GetRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Update a record
	// (PUT /api/v1/records/{objectName}/{recordId})
	UpdateRecord(c *gin.Context, objectName string, recordId openapi_types.UUID)
	// Health check
	// (GET /healthz)
	HealthCheck(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ValidateCelExpression operation middleware
func (siw *ServerInterfaceWrapper) ValidateCelExpression(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ValidateCelExpression(c)
}

// ListFunctions operation middleware
func (siw *ServerInterfaceWrapper) ListFunctions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFunctions(c)
}

// CreateFunction operation middleware
func (siw *ServerInterfaceWrapper) CreateFunction(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateFunction(c)
}

// DeleteFunction operation middleware
func (siw *ServerInterfaceWrapper) DeleteFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteFunction(c, functionId)
}

// GetFunction operation middleware
func (siw *ServerInterfaceWrapper) GetFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetFunction(c, functionId)
}

// UpdateFunction operation middleware
func (siw *ServerInterfaceWrapper) UpdateFunction(c *gin.Context) {

	var err error

	// ------------- Path parameter "functionId" -------------
	var functionId FunctionId

	err = runtime.BindStyledParameterWithOptions("simple", "functionId", c.Param("functionId"), &functionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter functionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateFunction(c, functionId)
}

// ListObjects operation middleware
func (siw *ServerInterfaceWrapper) ListObjects(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObjectsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "object_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "object_type", c.Request.URL.Query(), &params.ObjectType)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter object_type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjects(c, params)
}

// CreateObject operation middleware
func (siw *ServerInterfaceWrapper) CreateObject(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateObject(c)
}

// DeleteObject operation middleware
func (siw *ServerInterfaceWrapper) DeleteObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteObject(c, objectId)
}

// GetObject operation middleware
func (siw *ServerInterfaceWrapper) GetObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetObject(c, objectId)
}

// UpdateObject operation middleware
func (siw *ServerInterfaceWrapper) UpdateObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateObject(c, objectId)
}

// ListFields operation middleware
func (siw *ServerInterfaceWrapper) ListFields(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListFields(c, objectId)
}

// CreateField operation middleware
func (siw *ServerInterfaceWrapper) CreateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateField(c, objectId)
}

// DeleteField operation middleware
func (siw *ServerInterfaceWrapper) DeleteField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteField(c, objectId, fieldId)
}

// GetField operation middleware
func (siw *ServerInterfaceWrapper) GetField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetField(c, objectId, fieldId)
}

// UpdateField operation middleware
func (siw *ServerInterfaceWrapper) UpdateField(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "fieldId" -------------
	var fieldId FieldId

	err = runtime.BindStyledParameterWithOptions("simple", "fieldId", c.Param("fieldId"), &fieldId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter fieldId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateField(c, objectId, fieldId)
}

// ListValidationRules operation middleware
func (siw *ServerInterfaceWrapper) ListValidationRules(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListValidationRules(c, objectId)
}

// CreateValidationRule operation middleware
func (siw *ServerInterfaceWrapper) CreateValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateValidationRule(c, objectId)
}

// DeleteValidationRule operation middleware
func (siw *ServerInterfaceWrapper) DeleteValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteValidationRule(c, objectId, ruleId)
}

// GetValidationRule operation middleware
func (siw *ServerInterfaceWrapper) GetValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetValidationRule(c, objectId, ruleId)
}

// UpdateValidationRule operation middleware
func (siw *ServerInterfaceWrapper) UpdateValidationRule(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectId" -------------
	var objectId ObjectId

	err = runtime.BindStyledParameterWithOptions("simple", "objectId", c.Param("objectId"), &objectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "ruleId" -------------
	var ruleId RuleId

	err = runtime.BindStyledParameterWithOptions("simple", "ruleId", c.Param("ruleId"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter ruleId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateValidationRule(c, objectId, ruleId)
}

// ListObjectViews operation middleware
func (siw *ServerInterfaceWrapper) ListObjectViews(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListObjectViewsParams

	// ------------- Optional query parameter "object_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "object_id", c.Request.URL.Query(), &params.ObjectId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter object_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListObjectViews(c, params)
}

// CreateObjectView operation middleware
func (siw *ServerInterfaceWrapper) CreateObjectView(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateObjectView(c)
}

// DeleteObjectView operation middleware
func (siw *ServerInterfaceWrapper) DeleteObjectView(c *gin.Context) {

	var err error

	// ------------- Path parameter "viewId" -------------
	var viewId ViewId

	err = runtime.BindStyledParameterWithOptions("simple", "viewId", c.Param("viewId"), &viewId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteObjectView(c, viewId)
}

// GetObjectView operation middleware
func (siw *ServerInterfaceWrapper) GetObjectView(c *gin.Context) {

	var err error

	// ------------- Path parameter "viewId" -------------
	var viewId ViewId

	err = runtime.BindStyledParameterWithOptions("simple", "viewId", c.Param("viewId"), &viewId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetObjectView(c, viewId)
}

// UpdateObjectView operation middleware
func (siw *ServerInterfaceWrapper) UpdateObjectView(c *gin.Context) {

	var err error

	// ------------- Path parameter "viewId" -------------
	var viewId ViewId

	err = runtime.BindStyledParameterWithOptions("simple", "viewId", c.Param("viewId"), &viewId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter viewId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateObjectView(c, viewId)
}

// SetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) SetUserPassword(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetUserPassword(c, userId)
}

// ListTemplates operation middleware
func (siw *ServerInterfaceWrapper) ListTemplates(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTemplates(c)
}

// ApplyTemplate operation middleware
func (siw *ServerInterfaceWrapper) ApplyTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId string

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyTemplate(c, templateId)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMe(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// ExecuteDML operation middleware
func (siw *ServerInterfaceWrapper) ExecuteDML(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteDML(c)
}

// ListDescribeObjects operation middleware
func (siw *ServerInterfaceWrapper) ListDescribeObjects(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListDescribeObjects(c)
}

// DescribeObject operation middleware
func (siw *ServerInterfaceWrapper) DescribeObject(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DescribeObject(c, objectName)
}

// ExecuteQueryGet operation middleware
func (siw *ServerInterfaceWrapper) ExecuteQueryGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ExecuteQueryGetParams

	// ------------- Required query parameter "q" -------------

	if paramValue := c.Query("q"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument q is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", c.Request.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter q: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteQueryGet(c, params)
}

// ExecuteQueryPost operation middleware
func (siw *ServerInterfaceWrapper) ExecuteQueryPost(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExecuteQueryPost(c)
}

// ListRecords operation middleware
func (siw *ServerInterfaceWrapper) ListRecords(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListRecordsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRecords(c, objectName, params)
}

// CreateRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateRecord(c, objectName)
}

// DeleteRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteRecord(c, objectName, recordId)
}

// GetRecord operation middleware
func (siw *ServerInterfaceWrapper) GetRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRecord(c, objectName, recordId)
}

// UpdateRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecord(c *gin.Context) {

	var err error

	// ------------- Path parameter "objectName" -------------
	var objectName string

	err = runtime.BindStyledParameterWithOptions("simple", "objectName", c.Param("objectName"), &objectName, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter objectName: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", c.Param("recordId"), &recordId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter recordId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRecord(c, objectName, recordId)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.HealthCheck(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/admin/cel/validate", wrapper.ValidateCelExpression)
	router.GET(options.BaseURL+"/api/v1/admin/functions", wrapper.ListFunctions)
	router.POST(options.BaseURL+"/api/v1/admin/functions", wrapper.CreateFunction)
	router.DELETE(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.DeleteFunction)
	router.GET(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.GetFunction)
	router.PUT(options.BaseURL+"/api/v1/admin/functions/:functionId", wrapper.UpdateFunction)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.ListObjects)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects", wrapper.CreateObject)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.DeleteObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.GetObject)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId", wrapper.UpdateObject)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.ListFields)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields", wrapper.CreateField)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.DeleteField)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.GetField)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/fields/:fieldId", wrapper.UpdateField)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules", wrapper.ListValidationRules)
	router.POST(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules", wrapper.CreateValidationRule)
	router.DELETE(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.DeleteValidationRule)
	router.GET(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.GetValidationRule)
	router.PUT(options.BaseURL+"/api/v1/admin/metadata/objects/:objectId/rules/:ruleId", wrapper.UpdateValidationRule)
	router.GET(options.BaseURL+"/api/v1/admin/object-views", wrapper.ListObjectViews)
	router.POST(options.BaseURL+"/api/v1/admin/object-views", wrapper.CreateObjectView)
	router.DELETE(options.BaseURL+"/api/v1/admin/object-views/:viewId", wrapper.DeleteObjectView)
	router.GET(options.BaseURL+"/api/v1/admin/object-views/:viewId", wrapper.GetObjectView)
	router.PUT(options.BaseURL+"/api/v1/admin/object-views/:viewId", wrapper.UpdateObjectView)
	router.PUT(options.BaseURL+"/api/v1/admin/security/users/:userId/password", wrapper.SetUserPassword)
	router.GET(options.BaseURL+"/api/v1/admin/templates", wrapper.ListTemplates)
	router.POST(options.BaseURL+"/api/v1/admin/templates/:templateId/apply", wrapper.ApplyTemplate)
	router.POST(options.BaseURL+"/api/v1/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.GetMe)
	router.POST(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshToken)
	router.POST(options.BaseURL+"/api/v1/auth/reset-password", wrapper.ResetPassword)
	router.POST(options.BaseURL+"/api/v1/data", wrapper.ExecuteDML)
	router.GET(options.BaseURL+"/api/v1/describe", wrapper.ListDescribeObjects)
	router.GET(options.BaseURL+"/api/v1/describe/:objectName", wrapper.DescribeObject)
	router.GET(options.BaseURL+"/api/v1/query", wrapper.ExecuteQueryGet)
	router.POST(options.BaseURL+"/api/v1/query", wrapper.ExecuteQueryPost)
	router.GET(options.BaseURL+"/api/v1/records/:objectName", wrapper.ListRecords)
	router.POST(options.BaseURL+"/api/v1/records/:objectName", wrapper.CreateRecord)
	router.DELETE(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.DeleteRecord)
	router.GET(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.GetRecord)
	router.PUT(options.BaseURL+"/api/v1/records/:objectName/:recordId", wrapper.UpdateRecord)
	router.GET(options.BaseURL+"/healthz", wrapper.HealthCheck)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W3PbOLL/V0Hxv1VJ/qWMnOzM1qyrzkM2dmZ9yo69tpN5SPmoYLIlYcNbAFCOxuXv",
	"fgoXkoAI8CKJiqf2vCSWBAKN7l83Go1G8zEIsyTPUkg5C44fgxxTnAAHKj99IBBHZ5H4k6TBcZBjvgwm",
	"QYoTCI6Duf51ElD4VhAKUXDMaQGTgIVLSLB4bJ7RBPPgOCgKIlrydS4eZZySdBE8PU2CD0UacpKl/mHq",
	"BruNdHn/bwi5d5ys/Hm3Ua7wAqoRvhVA1/UQufjN7C6COS5iHhy/mQQJSUlSJPJv3S1JOSyAqn6BtnYN",
	"dObv/u3RJEjwd93/0VHnaNdFDF5OUfXjbnz6TODBO8JK/bjLCE/iYZZnKQOJ5X/g6Bq+FcC4+BRmKYdU",
	"/onzPCYhFhCb/ptlqfiuHuYvFObBcfD/prWeTNWvbHpKaUav9SBqyAhYSEkuOguOg884JpHsGYFoGzxN",
	"gvdZOo9JeEAqTgrVNaCMorAcXqheRu9JFEF6OFreSVVGacZRDjQhnEMkSDlLOdAUx7KDw5FTDosY0BXQ",
	"WkofM/4hK9LocKRcA8sKGoLkzVyO/TQJPqW44MuMkj/ggLS8K/gSUq57R6USCvyQdCVALVVY9yeGew/x",
	"lVg6TsSoj0FOsxwoJ0r1lFI/bqpoqbOPDutQ6/0X9bhufFcpujLXUqMg1ooGFXxsAsIsLpLUGKkydZMg",
	"Jim4f0mAMW1x2wksG3YQZ5ifTfJSDt/lD5AKm/wlWFWWYyasbTAJHpaQzuB7ToExIaVJad3ll8GkWidn",
	"91kkFoYVYeSexISvVYu7SVMARn8u+ahpzHBOZl4ZSo9BToNwUH+0Yc8ESoWAAFOK1w2+WrMtmdTJZA3r",
	"Bpelbg8i1EZVg1pBLC9oOvPAeKKkaPxyn2Ux4LQxUdXOOTMKmIP0w7zwMcWT4O/nkC74sl7my89vHfIX",
	"qwFZdLFCDv9eNd20FYaTEQSOEaSTOGPFfcmkEuF5jImQK6aAxUJPQrH+Q4JJHEyCfJmlAvUFFZ9KpRRj",
	"hyTB4ruwoBTSUCA9BxoKozgJcMGzWVok96ox5qD/40TZEPUfI+lCKlVSxJyI5xjLQiL1TUItyTNG9Kc8",
	"i9dJRvMlCZ06pGa4OT2J1UlQ0VKK3iInJ+HXmDAuHZ05iPmAc4wlxPmstBHtDCdsFhaMZ4nVdI5jBpMG",
	"DmXzGok9HyhS8q2Afs1jfA+xRGaNxDcOsqv5RzNtdZTmdLh5k4BllM8yGgG1CDpyurWm0lVqUxJpibJF",
	"GbWd9eqjtL+2Lv589Pe/OWjf0KTG7z20+o2wwFx4McFx8D9f8Os/7sQ/R6//Prv7/39xMWygwS6nK612",
	"DyNYKoAe0KkCGvMJzoXupWsH5t0+gGStXzRqh9fLUMJ3nOQxSB9wlZEQZrNQkjTIfg4yhUvMZjjkZEVK",
	"grrVRzyzJIxndD3jFIdfRV+9n0wzPmQgtsSCVulxsN7WIJSsx/exbRHUfs39hLRPM6ltbIbjOHvYsD4t",
	"D0cQw7Dh6ie0aen7oNxiDxmJAabhsvFEqy3No4Hck35dDDOSzhjwIu/1XGWGG7gPJl2mWdvjpoLjNMI0",
	"kmuxXHBcK1ceFxTHM//4rJuA2pO1lSynZKWW+MqpqL7Ji/uYhDMKOLI/zR4okS2EQ0mzOIZodr+e5ZgK",
	"F6LTEDlWDWuKNru6TNVnAg8/zq+rafA6dy73ohLAPtf/YYt+TrM5ETrgbJ4Wcaw0ylIHj0TrkSdN6foF",
	"WMd2rosYxhCi3OADm/HMhr0yuBNlOYIt3Aq5E5qFWWTbHHPTOcckhsixIHo6M/bKxhO/uJ+wNp125OH9",
	"6Tmqf0d8iTlKCsaR8jKQECiaZxRJWlGEOfY4wXKlhWHG0SD97S+/dNolBiugDaukYki1TSo/P2Caigfv",
	"dnJim4GABg8v5R84RoKZYZZGcicjuSaeRXxJGBJrPNIIC7Ywetbe3MaAS2dOLs69KsI45pDoqNZG6PLi",
	"HFU/o8qlNBaRjzen17fo7OPtJXoXhlmRcvTyI05ggs7SqGCcrl+hz+/OP53eoJcv3oUJvJigF7cQLtMs",
	"zhbrF686J1+T550Y0+bQnpfyO6KziDUndnbCUDZHugmiEGY0EoKofHJPsKz2u0nKgHb0X7bZagCaPbB3",
	"8zmEvPTOzBE+SrdeDCLaIVw2nNTmmKT8bz8HLgwr29VKum6yBeVPDjHJEM4/9MZsM/oWuaM3veN/sodJ",
	"axjQDrm6Y1O9wrZyDo1AmXzcNa4ZunEA1AggdpliYT6idYoTEiL9oDDChWcFUj27zNPv0gZl0visq65e",
	"6lVNy32CrFXuVdsgigqXBEskuv0YCsrpK53v5sKQ4O+zWC8ArghxlurNheUXA58JD0S4mJiFWGKDghg6",
	"5G4fmUJINoKwxigUYrkosyXJ/XFYFuLYE8hmHNMmm8y4iBs3JzAnqVw8bqpzBb93s5/gohJ7NFNiq0yJ",
	"AMHrMog31N/5vxjk3mOQTX3q57hb0Unn9jaPMRfdzBKc4gVE3oZm2NK9G18zDjrM4G1UxzJb/MIddyt7",
	"im16l9EByrKxcMhhWzdAtnaZKLBQZ0vE5GxlB5oyMeHglr3FAss4WJO/81swQfs9bG253Aumf8XpWjE6",
	"TH2LEZdj2mFbmzjrpMmzFfLEx6r9/BAd6AKnj0kuCJaORIk5S+oGieZ0XELvdgQba0FHsGDTtrodCRzN",
	"sjRej2mrthXEoFMPhxrXk3MpsK2eSm282nhOGPf7wHIv3/tUwumf9EKAPkztImOL0Z2jZXSR8SvM2ENG",
	"/We4yucwjXjphbRrj2p15x44Udk2DlMRejylr7B2fu8Hn//seyP9wGkInFS3GG05nwFnVzUPHPvbJVks",
	"Y7JYcn0SYXXbuTsWPlNpl2ZCDdyME6226V46/RDNRAfDJnytnhTK5uqYwRZMvAEPF30yNIloiHErdnsR",
	"GJOEcM/+rDrucRrNAZgsGeBKLYpxznymXWUeMTd52/BhqIY6J6SPdP1H102PaIRtWU8neF+ZRz/oIHtL",
	"L90rNEW+wzXtl0rgNeCjntt7D8POswXxZ1Lketl0El4woJ5ZbRBRtZzUPbqIufz87BdMc1pi7NqLK/23",
	"UG7T/Ml/5nTfZ0le6Ojuhj/ipkDbrG7aSv+wZfCTetux49iTQEmnhLAyVtUWsdo4lkdmLiV9WEI6cFpy",
	"WPfcLgp+s07D5tx8eOm5WVIiV429I2M3hqMk9gVJAYdL9yqpJ9F6ilzNtjcbBSlu8v8lbzX0zyBm2Tf3",
	"rPoRoq2C7MVN0DXgaAs1GW5uiQwezuNMBjeEzdWxQsZxku+AWdMEtyqkmqo78jHU865MqWOdDQ129uzM",
	"koKjy208qW8FUAJDpqTA2csHvvxc5wcMOHLy4sl/FmUfQw85dO4HH23qSgKM4dwo+p0SDj4YbSH6NrHr",
	"7dcQGZarzp5AlGhzO4SEykQ7+ltZqOnZoQG1fuCUf9Xxi6HR0RH2As3cyP65kB25jz1zHR1huf5HGlYK",
	"5LCcxx5Jjv2zGnc7UbHyHXskOPZIaOydwbjF6ct+EhL3sF3bzFA8XDai78xmIyXRPsIx2ec7dnFJqQXH",
	"HkRuKscmQDaxvoHCTcg1zISp6R774NJ2S17DTpVK07nVsZJjgekRZdZDuRasjCZ9ondmH/2sVQ/706Xn",
	"fgXr0MDBCbdDMabF4BfvHs8pGkutQ4w5XpC0WvPberuqWl4Ax22L+0e8OuOQDARoP3B0LBM/VPA1bX7x",
	"7nb205SoXwqfCTyMkjTjytz+gSHa7Q+RD5j2/UPSJayz6yoRYviKY4i6gSfpVfTcQpdgUW5H50PmZm6T",
	"GXJYF8UbVsoR1V14chyqIhbOX3nGsX1G6k8wlW1lX6zXExtz05U0jKIaanC7Y9fkr2FOgS29IW2qfp/x",
	"7Guf3bfd3D0gg+7zZTOSbqb0v/3VynL/1aE1PSlVzToi7DeX/zpvoXEBN+QPO2dfXjqwE0gvVCETlNYZ",
	"yCpHGOVAkZZXVe3k7VFXuZOJrqXSyFQV1CL5myv1/Ob0/PT9LTqLJugjTgB9uL68qHLQz88uzm7Rm6NO",
	"k6KG9vPKk1qepeDMrOVLoAjHccWSJV4BugdI9Q0KMAyrYaFT+M6v1SOfaOxIBi4oy6hMAp4DD5ckXSC+",
	"BCSekyxHLyHJ+RqRORLEvXLnwalU7kbvMrCGqJysK+EbR+oOA46vDDZYVt6XA6Q1tsaVOe6t+MmBoyar",
	"WpNlb8ZUwIZlalGvW0jEXg7e5Xm87nZz7G/bQoxcdzwjUa8z5qcW4s7SeTb8/LLeOzXV15P51uV1MG+2",
	"NC+YuY/HK0xi7WOqKzMCGfdxFn6FyL1J985+j3sLi6G9An+3wkZfYUJdAf4QGPMuS5OhC5fV36THOlbR",
	"tpt7Xk/RyYFP0tlqr6exj6IYQ7One6QI9spU7rqxNiRV0H8DUnPxcIUQ/pQ1C7zFChT7OooV/Ckj5s89",
	"FP5MI9wdWrsZNxl0Xf5wwWhnlKYL/6034A91jX1b0Qw0mL2vjJv3vne83b33+9pDLxjs43L19lepe12f",
	"7gfrgTeePzGgble3yvV2OLmU8ZbwbO9oXLtA2sZoD7E1vcJsh3Bc7wQ+2Z+RxVfmxhv8MudlzaLrykgp",
	"p93czkraTq/TVvyBEeEOczBG2HeoCRlsMvYE5P1ElceyNNscJDus07BqJsND1C12zUKCwSgLlM3bWlpo",
	"w+Lcto7scZu8oXy9NsqbK/UupmFzfGe0hEFYCNbKq0S6YDFgCvRdoa4S3stPH0oQ/ffvt2WlZ6kV8tca",
	"UEvOc1XYleglyA58naYcaE4JA/T++gKVCQDogfAlSoBjMbHXESUrSJGOliCcRmhBcVrEmKKS4J9kliKX",
	"EVHR1VXZ1burs2ASrIAqHAdHP7356UgqZw4pzklwHPz1p6Of/ipDxnwppzzFOZmu3kxxlJB0GkI81flQ",
	"ivWZ8paEAHBZMrwUFbyH+NREMlXuVVnzYS+Fcx3FXJ9sBRQqull5+u3R0TgU9Co8raKqFsiC4y82vL7c",
	"Pd1NAlYkCaZrg6cII7sKhBA2XjCZZC1cXdGrLbSyCq2c+QIcAhOq/aFqtSOvdrlCWN6C6WERmhwWs0DZ",
	"HNXzHcRh+TiOY6Q2w0Y3NYfr7+6EY+ZEv12ScizYO+te9kL+mz1Is58Q+witbK2Li8ic0p8V4lyDVHOZ",
	"GsXj5SN/736kqvM+CBeK1Qhv4sIDC7/6TR/r9yY81dWImgg6kd9bCLIk+HNz9ajYqMsXKZ783M2Tqqr6",
	"uExUU+rNxInbTv0G3M+Vo+eJ6wg4JjHbQiBD+Psb8CZz0f0anZ34zZfxYpEvbrLqJlPjpSBi6LxwyMcO",
	"Qo9k+tyR7hEW/YNBRLvhW5u+0VClWL296Svd1qlxuud1QC51mwYw9/zalkO8rMU9hp3lWw8zJFtaCGg0",
	"V9aRa9niZ5VCfZoEv/SBrf1CEQlE2/lSHaKoSuQzXa9qC1QO2+WBXZYJz+P5X/Z50QjeV7ew2gSlWhzW",
	"s9oDFrTD1UBDOxg6jc/0sXydVA/nywBPl+t1WdJpOF5/7eZA/aafbVy1nZmsHbKBTPb7ZT6GHR0e75GV",
	"2n141gpfbDBfhzlj1XvTOlyxUW2g68z8wLGX3pjY1cV6/gqtfbURrea0TvjyR5FUkxFF3ixb1RYKUuT8",
	"EIFIGiQBpkcj8zWru1gNyZQXYXa0CG2BKV0vYcSolJnKdWCnyK4k5tp0SYHs6hKNG1jZnw+1Cb9WyG1h",
	"C6aP+o2jfeJZFfA6g1ma6j+jQzWI4y1hLjezjg6tKM/BlxrI0m3t5qQ7BKbfrtsV/xrRwjqSZQ/scvUE",
	"zn+MwzWeia2yOr3eln2OParb1ZIL0OJ/rYxDT0nhuPFKOezmmG6Pq271WlE2osu1kW4wpu/lzmc8sBPm",
	"SdXoOBQvYnjmftkWp4YbYGwH4HDrMH1UL/7u4X45QNjlh21KZ/uzxS2OCgdxzu9IdU376Mej/gBHgwOZ",
	"OZ4LpV9i3+FBHcRgtiWAH9in2t5gPvejw93sn7J2r1cEHvqcHX6W7Rrw3XRPYw4U3a/LUJk8IW85rpMp",
	"m7UcO3JXdz6f27myiaxwsVMClWaMYvs2yBrss1kj1hix5N/vvE/OfvwzP/OOzLPIujJl30fWlzXHn3/q",
	"VWoCxI+PVvsxfRT/DTj8q5DU8wBQsvKZp1/1ZGTXMZ+bNUfPGOIHzMKyeNxIwWqatEG+1meJ4X7HfiOa",
	"Qt91wWeRhbULTp59Kta2prAcaFowgaNH8Z/YRppFMFx5Vznmy9olUk8FmzIe6B85kXsD/BMDWlbtGAm4",
	"jrog/TFrw6bsZ2fMvOl+5FOKC77MKPlj9O33DXAkxIxKZKCXEkGvDLAJYlwgK2uStDvrt1WrEbdUzuIe",
	"LT5vTfoWlwbKYiTIoNfosWZc/V0b96aP5Z9CQ+VLOfupZ/1Yq4q6VNLpWMuiNSUnDyEtu0qOQ1xlQ/2e",
	"5AixQlY1mRdxvH7eZ7N9ISV5IAy9C0w9sFTw5XQuX3H12jLuTgnb78Iayei6X7i1rd09m8syV/LCMYLv",
	"hHE2QRhRYMBRTNKvaImZqq/FBOnbbmArgehva4Moh2o3h0IIcbYgqZ/18j0rI3HceofLgYNZzapBDj0W",
	"0IeUl/Cutfhwq6glY4MekMtfL/FmypHxylf8vr2AB1cpdHi6XWJ3bGfPs8UCIiRo356xvddPyST0ksIq",
	"+wpITxLJSb7qloG6n+/brF6MumY1qhQ4YP5evo1YOVQH4KbYf4bGkEheNe7koua6H8q6guZtVTls/xZr",
	"o0jnc7RZslEJ0dIP383s6FkjVZoNlaXZOuXFoM/ibtUhHU1ubIQtVbWCq6V2D0u4cA6qBVzeqe9mdlWU",
	"0cnd0+8QFhxOLs5HYu3JxfkPUgc5sr6j3lCDk4vz6gb7gZJ7ds7V0bJCgnbGMYdEvRi+lL18+5UleuN1",
	"At6NbFnEv7659mNPfsoK8zsd/lT12Or7XcM3xNKcEaMTmYST4hVZ4I0kqYrTTv6XGQ8fcQJPXmHYgvhR",
	"ken6nQ4Doo7Gl8osbZ2yPuw8QJFaBhPNkZ2imfSIPtSSGhZ9MMReVX12illrsSxN/JvcgbWe9O5QK/r3",
	"f55en6rv/wu9eBcm8MJzSPxtaKRlNKNtFKd2wM2s5/zns9uGKF/+dnpr7gzUiwK9Z8MmZq4yNtZdKLOK",
	"+oEX6/8UuV9d3rgEb1gPXSu835qhAsNlXfNhp3BXeAF9sp2ugKqmIyeF7FSMfZ/vumniTz8DEYq1g1EW",
	"kz9AKnBZPF44H9XJmQGhkpRx17f2tBWFwR3M0gDhHypRZeNNzdsWqG+iSTFr54SVkS8XbFVdiJY4aIKz",
	"w8RNH9W3vXJbDLh1BQI1sw95D2urkkItnPMnsvj4sA+7PEQj+4Ne9n6IKkKKfY3MlYMYy4mzsxLfoyQe",
	"qMyK52aGj7z6+MxvVm1VX6jD+C0Bx3z5h9eX+6f8/f0Swq/71WjjxSPVxjH7Gkz6Hb5sbEeBrkgIiDCk",
	"5rPecHrVLFCop1H5uWvGIRGckKylK/du9zwLcYwiWEGc5Tq8VdBYVx49nk5j0WCZMX7869GvR9In1UM0",
	"Ns5yRE2lrDEaEbxIM8ZJyGqt1IQJnW093BMdlBHwMvqju5Ax12YHjUIeSL0GVU9LP9woZ9DsaPMSa3s/",
	"VeilJZIAcmdiTUJuRJoPWbFG13NR4nrsnePU30m2kbEy6bq543q+kYDf7Ob9Rj05VzdGtc1JW2as61kr",
	"ac0xvFXo1LhLUPcQQhw83T39bwAAAP//jJzG9DSzAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
